//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic15HttpRequestBase.h"

@class NSData, NSString;

@interface _TtC7BingDic19DailyContentRequest : _TtC7BingDic15HttpRequestBase
{
    // Error parsing type: , name: contentData
    // Error parsing type: , name: version
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithResponse:(CDUnknownBlockType)arg1;
- (void)responseWithResponseData:(id)arg1;
- (void)beginNewDataRequest;
- (void)beginCacheDataRequest;
@property(nonatomic, readonly) NSString *version; // @synthesize version;
@property(nonatomic, copy) NSData *contentData; // @synthesize contentData;

@end

