//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic28ResultPageBaseViewController.h"

@class AVAudioPlayer, NSArray, NSLayoutConstraint, NSString, NSTimer, UIButton, _TtC7BingDic22TranslateInputTextView, _TtC7BingDic7DropBox;

@interface _TtC7BingDic27TranslateRootViewController : _TtC7BingDic28ResultPageBaseViewController
{
    // Error parsing type: , name: dpOriginLang
    // Error parsing type: , name: dpTargetLang
    // Error parsing type: , name: txtView
    // Error parsing type: , name: voiceTranslateButton
    // Error parsing type: , name: photoTranslateButton
    // Error parsing type: , name: realtimeTranslateButton
    // Error parsing type: , name: consBtnRealtimeHeight
    // Error parsing type: , name: kHistoryCellId
    // Error parsing type: , name: kResultCell
    // Error parsing type: , name: kAdvertiseCell
    // Error parsing type: , name: isShowHistory
    // Error parsing type: , name: translatedText
    // Error parsing type: , name: result
    // Error parsing type: , name: needToTranslatedText
    // Error parsing type: , name: player
    // Error parsing type: , name: historyItems
    // Error parsing type: , name: errorTimer
    // Error parsing type: , name: supportVoiceCodes
    // Error parsing type: , name: isLoad
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)fullScreenActionWithOriginText:(id)arg1 targetText:(id)arg2;
- (void)shareActionWithWord:(id)arg1;
- (void)pronAction;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)translateResponseWithRequest:(id)arg1;
- (void)queryResultFailed;
- (void)tabBarClearSearchContent;
- (void)translateActionWithText:(id)arg1;
- (void)resetTextAction;
- (void)photoTranslateButtonClickedWithSender:(id)arg1;
- (void)voiceTranslateButtonClicked:(id)arg1;
- (void)btnChangeLanguageClick:(id)arg1;
- (void)targetLanguageChangeActionWithLangObject:(id)arg1;
- (void)originLanguageChangeActionWithLangObject:(id)arg1;
- (void)btnExchangeLanguageClick:(id)arg1;
- (void)initLanguageData;
- (void)dealloc;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
@property(nonatomic) _Bool isLoad; // @synthesize isLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, copy) NSArray *supportVoiceCodes; // @synthesize supportVoiceCodes;
@property(nonatomic, retain) NSTimer *errorTimer; // @synthesize errorTimer;
@property(nonatomic, copy) NSArray *historyItems; // @synthesize historyItems;
@property(nonatomic, retain) AVAudioPlayer *player; // @synthesize player;
@property(nonatomic, copy) NSString *needToTranslatedText; // @synthesize needToTranslatedText;
@property(nonatomic, copy) NSString *translatedText; // @synthesize translatedText;
@property(nonatomic) _Bool isShowHistory; // @synthesize isShowHistory;
@property(nonatomic, readonly) NSString *kAdvertiseCell; // @synthesize kAdvertiseCell;
@property(nonatomic, readonly) NSString *kResultCell; // @synthesize kResultCell;
@property(nonatomic, readonly) NSString *kHistoryCellId; // @synthesize kHistoryCellId;
@property(nonatomic) __weak NSLayoutConstraint *consBtnRealtimeHeight; // @synthesize consBtnRealtimeHeight;
@property(nonatomic) __weak UIButton *realtimeTranslateButton; // @synthesize realtimeTranslateButton;
@property(nonatomic) __weak UIButton *photoTranslateButton; // @synthesize photoTranslateButton;
@property(nonatomic) __weak UIButton *voiceTranslateButton; // @synthesize voiceTranslateButton;
@property(nonatomic) __weak _TtC7BingDic22TranslateInputTextView *txtView; // @synthesize txtView;
@property(nonatomic) __weak _TtC7BingDic7DropBox *dpTargetLang; // @synthesize dpTargetLang;
@property(nonatomic) __weak _TtC7BingDic7DropBox *dpOriginLang; // @synthesize dpOriginLang;

@end

