//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7BingDic16AdvertiseManager : SwiftObject
{
    // Error parsing type: , name: downloadCompletion
    // Error parsing type: , name: sizeDict
    // Error parsing type: , name: advertiseList
    // Error parsing type: , name: imageUrls
    // Error parsing type: , name: advertiseModel
    // Error parsing type: , name: lastRequestTime
    // Error parsing type: , name: lastRequestSuccessed
}

@end

