//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7BingDic20ResultPageCellLayout : SwiftObject
{
    // Error parsing type: , name: sectionBottomPadding
    // Error parsing type: , name: speechBottomPadding
    // Error parsing type: , name: txtHPadding
    // Error parsing type: , name: txtVPadding
    // Error parsing type: , name: inlinePartMargin
    // Error parsing type: , name: height
}

@end

