//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSArray, NSString, UIButton, UICollectionView, UIImageView, UILabel;

@interface _TtC7BingDic35BDStudyRootListDetailsTableViewCell : UITableViewCell <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    // Error parsing type: , name: imgTitle
    // Error parsing type: , name: lblTitle
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: detailsBtn
    // Error parsing type: , name: imgCellId
    // Error parsing type: , name: imgLabelCellId
    // Error parsing type: , name: itemSize
    // Error parsing type: , name: itemClickAction
    // Error parsing type: , name: detailsButtonClickAction
    // Error parsing type: , name: titleList
    // Error parsing type: , name: imageList
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)detailsButtonClicked:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
@property(nonatomic, copy) NSArray *imageList; // @synthesize imageList;
@property(nonatomic, copy) NSArray *titleList; // @synthesize titleList;
@property(nonatomic, copy) CDUnknownBlockType detailsButtonClickAction; // @synthesize detailsButtonClickAction;
@property(nonatomic, copy) CDUnknownBlockType itemClickAction; // @synthesize itemClickAction;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize;
@property(nonatomic, readonly) NSString *imgLabelCellId; // @synthesize imgLabelCellId;
@property(nonatomic, readonly) NSString *imgCellId; // @synthesize imgCellId;
@property(nonatomic) __weak UIButton *detailsBtn; // @synthesize detailsBtn;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle;
@property(nonatomic) __weak UIImageView *imgTitle; // @synthesize imgTitle;

@end

