//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic25QuickSearchViewController.h"

#import "_TtP7BingDic23SwiftJavaScriptDelegate_-Protocol.h"

@class NSDictionary, NSLayoutConstraint, NSString, NSTimer, UIImageView, UILabel, UIWebView, _TtC7BingDic23DictionarySearchManager;

@interface _TtC7BingDic25FeedsDetailViewController : _TtC7BingDic25QuickSearchViewController <_TtP7BingDic23SwiftJavaScriptDelegate_>
{
    // Error parsing type: , name: sharedContentFormat
    // Error parsing type: , name: imgSource
    // Error parsing type: , name: lblSource
    // Error parsing type: , name: lblTitle
    // Error parsing type: , name: lblTime
    // Error parsing type: , name: webView
    // Error parsing type: , name: titleHeightConstraint
    // Error parsing type: , name: webviewHeightConstraint
    // Error parsing type: , name: feedsContent
    // Error parsing type: , name: htmlContent
    // Error parsing type: , name: dictSearchMananger
    // Error parsing type: , name: errorTimer
    // Error parsing type: , name: isLoad
    // Error parsing type: , name: infoDic
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)btnShareClick:(id)arg1;
- (void)queryResultFailed;
- (void)selectText:(id)arg1;
@property(nonatomic, copy) NSDictionary *infoDic; // @synthesize infoDic;
- (void)webViewDidFinishLoad:(id)arg1;
@property(nonatomic) _Bool isLoad; // @synthesize isLoad;
- (void)feedsDetailResponseWithResponse:(id)arg1;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic, retain) NSTimer *errorTimer; // @synthesize errorTimer;
@property(nonatomic, retain) _TtC7BingDic23DictionarySearchManager *dictSearchMananger; // @synthesize dictSearchMananger;
@property(nonatomic, copy) NSString *htmlContent; // @synthesize htmlContent;
@property(nonatomic) __weak NSLayoutConstraint *webviewHeightConstraint; // @synthesize webviewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *titleHeightConstraint; // @synthesize titleHeightConstraint;
@property(nonatomic) __weak UIWebView *webView; // @synthesize webView;
@property(nonatomic) __weak UILabel *lblTime; // @synthesize lblTime;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle;
@property(nonatomic) __weak UILabel *lblSource; // @synthesize lblSource;
@property(nonatomic) __weak UIImageView *imgSource; // @synthesize imgSource;

@end

