//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class AVAudioPlayer, NSArray, NSTimer, UIButton, UILabel, UITableView, UIView, _TtC7BingDic13AudioRecorder, _TtC7BingDic19VoiceTranslateModel, _TtC7BingDic24VoiceTranslateMetersView, _TtC7BingDic7DropBox;

@interface _TtC7BingDic28VoiceTranslateViewController : UIViewController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: bottomView
    // Error parsing type: , name: changeLanguageButton
    // Error parsing type: , name: originLanguageButton
    // Error parsing type: , name: targetLanguageButton
    // Error parsing type: , name: recordButton
    // Error parsing type: , name: tipLabel
    // Error parsing type: , name: metersView
    // Error parsing type: , name: recorder
    // Error parsing type: , name: startRecordSoundID
    // Error parsing type: , name: endRecordSoundID
    // Error parsing type: , name: recordTime
    // Error parsing type: , name: translateTimer
    // Error parsing type: , name: translateLoadingCount
    // Error parsing type: , name: recordSecondView
    // Error parsing type: , name: originLanguages
    // Error parsing type: , name: targetLanguages
    // Error parsing type: , name: supportVoiceCodes
    // Error parsing type: , name: models
    // Error parsing type: , name: translateModel
    // Error parsing type: , name: meters
    // Error parsing type: , name: audioPlayer
    // Error parsing type: , name: isFirstIn
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)voiceTranslateResultCellShareEventWithCell:(id)arg1;
- (void)voiceTranslateResultCellFullScreenEventWithCell:(id)arg1;
- (void)voiceTranslateResultCellCopyEventWithCell:(id)arg1;
- (void)voiceTranslateResultCellPlaySoundEventWithCell:(id)arg1;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)checkLanguageCanChange;
- (id)filePathWithId:(id)arg1;
- (void)endRecord;
- (void)startRecord;
- (_Bool)requestRecordPermission;
- (void)tipLoadingTimerEvent;
- (void)changeLanguageButonClickedWithSender:(id)arg1;
- (void)recordButtonTouchUpOutsideEventWithSender:(id)arg1;
- (void)recordButtonTouchUpInsideEventWithSender:(id)arg1;
- (void)recordButtonTouchDragOutsideEventWithSender:(id)arg1;
- (void)recordButtonTouchDragInsideEventWithSender:(id)arg1;
- (void)recordButtonTouchDownEventWithSender:(id)arg1;
- (void)targetLanguageChangeActionWithLangObject:(id)arg1;
- (void)originLanguageChangeActionWithLangObject:(id)arg1;
- (void)recordTimeWithCurrentRecordTime:(double)arg1;
- (void)recordMetersWithAveragePowerForChannel:(float)arg1 peakPowerForChannel:(float)arg2;
- (void)originToTargetResponseWithRequest:(id)arg1;
- (void)dataToOriginResponseWithRequest:(id)arg1;
- (void)initLanguageData;
- (void)dismissSecondView;
- (void)showSecondViewWithRecordTime:(double)arg1;
- (void)resetUIState;
- (void)setupSubViews;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic) long long isFirstIn; // @synthesize isFirstIn;
@property(nonatomic, retain) AVAudioPlayer *audioPlayer; // @synthesize audioPlayer;
@property(nonatomic, copy) NSArray *meters; // @synthesize meters;
@property(nonatomic, retain) _TtC7BingDic19VoiceTranslateModel *translateModel; // @synthesize translateModel;
@property(nonatomic, copy) NSArray *models; // @synthesize models;
@property(nonatomic, copy) NSArray *supportVoiceCodes; // @synthesize supportVoiceCodes;
@property(nonatomic, copy) NSArray *targetLanguages; // @synthesize targetLanguages;
@property(nonatomic, copy) NSArray *originLanguages; // @synthesize originLanguages;
@property(nonatomic, retain) UIView *recordSecondView; // @synthesize recordSecondView;
@property(nonatomic) long long translateLoadingCount; // @synthesize translateLoadingCount;
@property(nonatomic, retain) NSTimer *translateTimer; // @synthesize translateTimer;
@property(nonatomic) double recordTime; // @synthesize recordTime;
@property(nonatomic, readonly) _TtC7BingDic13AudioRecorder *recorder; // @synthesize recorder;
@property(nonatomic, retain) _TtC7BingDic24VoiceTranslateMetersView *metersView; // @synthesize metersView;
@property(nonatomic, retain) UILabel *tipLabel; // @synthesize tipLabel;
@property(nonatomic, retain) UIButton *recordButton; // @synthesize recordButton;
@property(nonatomic, retain) _TtC7BingDic7DropBox *targetLanguageButton; // @synthesize targetLanguageButton;
@property(nonatomic, retain) _TtC7BingDic7DropBox *originLanguageButton; // @synthesize originLanguageButton;
@property(nonatomic, retain) UIButton *changeLanguageButton; // @synthesize changeLanguageButton;
@property(nonatomic, retain) UIView *bottomView; // @synthesize bottomView;
@property(nonatomic, retain) UITableView *tableView; // @synthesize tableView;

@end

