//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, NSLayoutConstraint, UIButton, UIImageView, UILabel, _TtC7BingDic18DailyWordEmbedView, _TtC7BingDic9DailyWord;

@interface _TtC7BingDic13DailyWordCell : UITableViewCell
{
    // Error parsing type: , name: lblTitle
    // Error parsing type: , name: btnChange
    // Error parsing type: , name: btnStar
    // Error parsing type: , name: imgPreview
    // Error parsing type: , name: lblWord
    // Error parsing type: , name: btnUS
    // Error parsing type: , name: btnUK
    // Error parsing type: , name: lblDesc
    // Error parsing type: , name: btnUsWidthConstraint
    // Error parsing type: , name: btnUkWidthConstraint
    // Error parsing type: , name: embingView
    // Error parsing type: , name: imgDetail
    // Error parsing type: , name: embedBtns
    // Error parsing type: , name: currentIndex
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: delegate
    // Error parsing type: , name: word
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (struct CGSize)sizeOf:(id)arg1 font:(id)arg2;
- (void)setupEmbedBtnsWith:(id)arg1;
- (void)responseWithRequest:(id)arg1;
- (void)embedBtnClicked:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)btnUkClick:(id)arg1;
- (void)btnUsClick:(id)arg1;
- (void)btnStarClick:(id)arg1;
- (void)btnChangeClick:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic, retain) _TtC7BingDic9DailyWord *word; // @synthesize word;
@property(nonatomic, copy) NSArray *dataSource; // @synthesize dataSource;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex;
@property(nonatomic, copy) NSArray *embedBtns; // @synthesize embedBtns;
@property(nonatomic) __weak UIImageView *imgDetail; // @synthesize imgDetail;
@property(nonatomic) __weak _TtC7BingDic18DailyWordEmbedView *embingView; // @synthesize embingView;
@property(nonatomic) __weak NSLayoutConstraint *btnUkWidthConstraint; // @synthesize btnUkWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *btnUsWidthConstraint; // @synthesize btnUsWidthConstraint;
@property(nonatomic) __weak UILabel *lblDesc; // @synthesize lblDesc;
@property(nonatomic) __weak UIButton *btnUK; // @synthesize btnUK;
@property(nonatomic) __weak UIButton *btnUS; // @synthesize btnUS;
@property(nonatomic) __weak UILabel *lblWord; // @synthesize lblWord;
@property(nonatomic) __weak UIImageView *imgPreview; // @synthesize imgPreview;
@property(nonatomic) __weak UIButton *btnStar; // @synthesize btnStar;
@property(nonatomic) __weak UIButton *btnChange; // @synthesize btnChange;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle;

@end

