//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic27PronounceReadBaseController.h"

@class NSDictionary, NSString, UIButton, UILabel, UITableView;

@interface _TtC7BingDic24DialogueResultController : _TtC7BingDic27PronounceReadBaseController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: lblScore
    // Error parsing type: , name: lblReviews
    // Error parsing type: , name: btnShare
    // Error parsing type: , name: btnContinue
    // Error parsing type: , name: btnUp
    // Error parsing type: , name: kSceneOralDialogueBingCellIdentifier
    // Error parsing type: , name: kSceneOralDialogueUserSampleCellIdentifier
    // Error parsing type: , name: dialogueModels
    // Error parsing type: , name: heightDict
    // Error parsing type: , name: playerDict
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)btnContinueClicked:(id)arg1;
- (void)btnShareClicked:(id)arg1;
- (void)useAgreementClick:(id)arg1;
- (void)privacyPolicyClick:(id)arg1;
- (void)btnUpClicked:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, copy) NSDictionary *heightDict; // @synthesize heightDict;
@property(nonatomic, readonly) NSString *kSceneOralDialogueUserSampleCellIdentifier; // @synthesize kSceneOralDialogueUserSampleCellIdentifier;
@property(nonatomic, readonly) NSString *kSceneOralDialogueBingCellIdentifier; // @synthesize kSceneOralDialogueBingCellIdentifier;
@property(nonatomic) __weak UIButton *btnUp; // @synthesize btnUp;
@property(nonatomic) __weak UIButton *btnContinue; // @synthesize btnContinue;
@property(nonatomic) __weak UIButton *btnShare; // @synthesize btnShare;
@property(nonatomic) __weak UILabel *lblReviews; // @synthesize lblReviews;
@property(nonatomic) __weak UILabel *lblScore; // @synthesize lblScore;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;

@end

