//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

@class NSArray, UIViewController;

@interface _TtC7BingDic18MainViewController : UITabBarController
{
    // Error parsing type: , name: arrTabItems
    // Error parsing type: , name: feedsPushDictionary
    // Error parsing type: , name: isShowActivity
}

+ (id)mainViewControllerPostToShowActivity;
+ (id)mainViewControllerPostToFeedsClear;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, retain) UIViewController *selectedViewController;
- (void)centerButtonClickedWithSender:(id)arg1;
- (void)setRedBadgeWithPosition:(long long)arg1;
- (void)resetTabbar;
- (id)getImageWithColorWithColor:(id)arg1 size:(struct CGSize)arg2;
- (void)createTabBarControllers;
- (void)replaceTabBar;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic) _Bool isShowActivity; // @synthesize isShowActivity;
@property(nonatomic) _Bool feedsPushDictionary; // @synthesize feedsPushDictionary;
@property(nonatomic, copy) NSArray *arrTabItems; // @synthesize arrTabItems;

@end

