//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSArray, NSObject, NSString, UIColor, UIFont;

@interface _TtC7BingDic26LanguageListViewController : UITableViewController
{
    // Error parsing type: , name: kCellId
    // Error parsing type: , name: textFont
    // Error parsing type: , name: headerFont
    // Error parsing type: , name: headerBackColor
    // Error parsing type: , name: selectTextColor
    // Error parsing type: , name: commonTextColor
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: historyList
    // Error parsing type: , name: currentValue
    // Error parsing type: , name: selectValueChangeAction
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)btnDoneClick;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, copy) CDUnknownBlockType selectValueChangeAction; // @synthesize selectValueChangeAction;
@property(nonatomic, retain) NSObject *currentValue; // @synthesize currentValue;
@property(nonatomic, copy) NSArray *historyList; // @synthesize historyList;
@property(nonatomic, copy) NSArray *dataSource; // @synthesize dataSource;
@property(nonatomic, readonly) UIColor *commonTextColor; // @synthesize commonTextColor;
@property(nonatomic, readonly) UIColor *selectTextColor; // @synthesize selectTextColor;
@property(nonatomic, readonly) UIColor *headerBackColor; // @synthesize headerBackColor;
@property(nonatomic, readonly) UIFont *headerFont; // @synthesize headerFont;
@property(nonatomic, readonly) UIFont *textFont; // @synthesize textFont;
@property(nonatomic, readonly) NSString *kCellId; // @synthesize kCellId;

@end

