//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSString;

@interface _TtC7BingDic18OxfordSpeechButton : UIButton
{
    // Error parsing type: , name: index
    // Error parsing type: , name: titleText
}

- (CDUnknownBlockType).cxx_destruct;
- (void)setBorderWithSelected:(_Bool)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSString *titleText; // @synthesize titleText;

@end

