//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface _TtC7BingDic4User : NSObject
{
    // Error parsing type: , name: userId
    // Error parsing type: , name: nickName
    // Error parsing type: , name: imgUrl
    // Error parsing type: , name: accessToken
    // Error parsing type: , name: refreshToken
    // Error parsing type: , name: image
    // Error parsing type: , name: channel
}

- (CDUnknownBlockType).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJsonDic:(id)arg1;
- (id)init;
@property(nonatomic, retain) UIImage *image; // @synthesize image;
@property(nonatomic, copy) NSString *refreshToken; // @synthesize refreshToken;
@property(nonatomic, copy) NSString *accessToken; // @synthesize accessToken;
@property(nonatomic, copy) NSString *imgUrl; // @synthesize imgUrl;
@property(nonatomic, copy) NSString *nickName; // @synthesize nickName;
@property(nonatomic, copy) NSString *userId; // @synthesize userId;

@end

