//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSString, UIBarButtonItem, UIButton, UICollectionView, UIView, _TtC7BingDic19ReciteWordsCategory;

@interface _TtC7BingDic37ReciteWordsCategoryListViewController : UIViewController
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: btnConfirm
    // Error parsing type: , name: nextView
    // Error parsing type: , name: btnEdit
    // Error parsing type: , name: kCellId
    // Error parsing type: , name: kAddCellId
    // Error parsing type: , name: kShowPlanSegueId
    // Error parsing type: , name: isSelectMode
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: selectCategory
    // Error parsing type: , name: isEditMode
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)btnConfirmClick:(id)arg1;
- (void)btnBackClick:(id)arg1;
- (void)deleteCategoryActionWithCategory:(id)arg1;
- (void)selectCategoryActionWithCategory:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)btnEditClick:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic) _Bool isEditMode; // @synthesize isEditMode;
@property(nonatomic, retain) _TtC7BingDic19ReciteWordsCategory *selectCategory; // @synthesize selectCategory;
@property(nonatomic, copy) NSArray *dataSource; // @synthesize dataSource;
@property(nonatomic) _Bool isSelectMode; // @synthesize isSelectMode;
@property(nonatomic, readonly) NSString *kShowPlanSegueId; // @synthesize kShowPlanSegueId;
@property(nonatomic, readonly) NSString *kAddCellId; // @synthesize kAddCellId;
@property(nonatomic, readonly) NSString *kCellId; // @synthesize kCellId;
@property(nonatomic) __weak UIBarButtonItem *btnEdit; // @synthesize btnEdit;
@property(nonatomic) __weak UIView *nextView; // @synthesize nextView;
@property(nonatomic) __weak UIButton *btnConfirm; // @synthesize btnConfirm;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

