//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSLayoutConstraint, NSString, UIButton, UILabel, UITableView, UIView, _TtC7BingDic11CollectWord, _TtC7BingDic15CollectSentence;

@interface _TtC7BingDic32BDCollectionChoiceViewController : UIViewController
{
    // Error parsing type: , name: type
    // Error parsing type: , name: topImageButton
    // Error parsing type: , name: contentView
    // Error parsing type: , name: topLabel
    // Error parsing type: , name: bottomLabel
    // Error parsing type: , name: tableView
    // Error parsing type: , name: topView
    // Error parsing type: , name: bottomView
    // Error parsing type: , name: contentViewLayoutHeight
    // Error parsing type: , name: word
    // Error parsing type: , name: sentence
    // Error parsing type: , name: wordBooks
    // Error parsing type: , name: sentenceBooks
    // Error parsing type: , name: pageName
    // Error parsing type: , name: completed
}

- (CDUnknownBlockType).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)alertTextFieldDidChangeWithNotification:(id)arg1;
- (void)topImageButtonClicked:(id)arg1;
- (void)bottomViewTappedEventWithGesture:(id)arg1;
- (void)loadData;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, copy) CDUnknownBlockType completed; // @synthesize completed;
@property(nonatomic, copy) NSString *pageName; // @synthesize pageName;
@property(nonatomic, copy) NSArray *sentenceBooks; // @synthesize sentenceBooks;
@property(nonatomic, copy) NSArray *wordBooks; // @synthesize wordBooks;
@property(nonatomic, retain) _TtC7BingDic15CollectSentence *sentence; // @synthesize sentence;
@property(nonatomic, retain) _TtC7BingDic11CollectWord *word; // @synthesize word;
@property(nonatomic) __weak NSLayoutConstraint *contentViewLayoutHeight; // @synthesize contentViewLayoutHeight;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView;
@property(nonatomic) __weak UIView *topView; // @synthesize topView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;
@property(nonatomic) __weak UILabel *bottomLabel; // @synthesize bottomLabel;
@property(nonatomic) __weak UILabel *topLabel; // @synthesize topLabel;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView;
@property(nonatomic) __weak UIButton *topImageButton; // @synthesize topImageButton;

@end

