//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIImageView, UILabel;

@interface _TtC7BingDic26ReadResultDetailHeaderView : UIView
{
    // Error parsing type: , name: bgView
    // Error parsing type: , name: leftImage
    // Error parsing type: , name: rightImage
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: titleText
    // Error parsing type: , name: expanded
    // Error parsing type: , name: delegate
    // Error parsing type: , name: section
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)tapResponseWithRecognizer:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 section:(long long)arg2;
@property(nonatomic) long long section; // @synthesize section;
@property(nonatomic, copy) NSString *titleText; // @synthesize titleText;
@property(nonatomic, retain) UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic, retain) UIImageView *rightImage; // @synthesize rightImage;
@property(nonatomic, retain) UIImageView *leftImage; // @synthesize leftImage;
@property(nonatomic, retain) UIView *bgView; // @synthesize bgView;

@end

