//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UILabel, _TtC7BingDic17FollowResultModel;

@interface _TtC7BingDic20ResultMenuDetailCell : UITableViewCell
{
    // Error parsing type: , name: wordLabel
    // Error parsing type: , name: pronunciationLabel
    // Error parsing type: , name: scoreLabel
    // Error parsing type: , name: soundButton
    // Error parsing type: , name: result
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)queryResultFailed;
- (void)wordSoundClick:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
@property(nonatomic, retain) _TtC7BingDic17FollowResultModel *result; // @synthesize result;
@property(nonatomic) __weak UIButton *soundButton; // @synthesize soundButton;
@property(nonatomic) __weak UILabel *scoreLabel; // @synthesize scoreLabel;
@property(nonatomic) __weak UILabel *pronunciationLabel; // @synthesize pronunciationLabel;
@property(nonatomic) __weak UILabel *wordLabel; // @synthesize wordLabel;

@end

