//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC7BingDic7KeyWord : NSObject
{
    // Error parsing type: , name: headWord
    // Error parsing type: , name: phonetic
    // Error parsing type: , name: definition
    // Error parsing type: , name: check
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic) _Bool check; // @synthesize check;
@property(nonatomic, copy) NSString *definition; // @synthesize definition;
@property(nonatomic, copy) NSString *phonetic; // @synthesize phonetic;
@property(nonatomic, copy) NSString *headWord; // @synthesize headWord;

@end

