//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class NSArray;

@interface _TtC7BingDic20FilterViewCellLayout : UICollectionViewFlowLayout
{
    // Error parsing type: , name: alignDirection
    // Error parsing type: , name: layoutAttributes
    // Error parsing type: , name: contentSize
}

- (CDUnknownBlockType).cxx_destruct;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (void)prepareLayout;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(nonatomic, readonly) struct CGSize collectionViewContentSize;
@property(nonatomic, copy) NSArray *layoutAttributes; // @synthesize layoutAttributes;

@end

