//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7BingDic24DictionaryModelConverter : SwiftObject
{
    // Error parsing type: , name: KEY_quickDefinitionDict
    // Error parsing type: , name: KEY_inflectionDict
    // Error parsing type: , name: KEY_enChDefinitionDict
    // Error parsing type: , name: KEY_enEnDefinitionDict
    // Error parsing type: , name: KEY_chEnDefinitionDict
    // Error parsing type: , name: KEY_chChDefinitionDict
    // Error parsing type: , name: KEY_webDecinitionDict
    // Error parsing type: , name: KEY_synonymImageDict
    // Error parsing type: , name: KEY_synonymAntonymDict
    // Error parsing type: , name: KEY_phraseDict
    // Error parsing type: , name: KEY_phraseDict2
    // Error parsing type: , name: KEY_sentenceDict
    // Error parsing type: , name: KEY_defaultResult
    // Error parsing type: , name: KEY_fayinDict
    // Error parsing type: , name: KEY_fayinDict_US
    // Error parsing type: , name: KEY_fayinDict_UK
    // Error parsing type: , name: KEY_fayinDict_PY
    // Error parsing type: , name: KEY_translationDict
    // Error parsing type: , name: KEY_oxfordDict
    // Error parsing type: , name: KEY_oxfordDict_idiom
    // Error parsing type: , name: KEY_oxfordDict_definition
    // Error parsing type: , name: KEY_oxfordDict_discriminator
    // Error parsing type: , name: KEY_oxfordDict_grammarlabels
    // Error parsing type: , name: KEY_oxfordDict_examples_sentence
    // Error parsing type: , name: KEY_oxfordDict_examples_phrase
    // Error parsing type: , name: KEY_oxfordDict_complements
}

@end

