//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSTimer;

@interface _TtC7BingDic28RadioRightNavigationItemView : UIView
{
    // Error parsing type: , name: layers
    // Error parsing type: , name: views
    // Error parsing type: , name: timer
    // Error parsing type: , name: groupAnimations
}

- (CDUnknownBlockType).cxx_destruct;
- (void)stopPlay;
- (void)startPlay;
- (void)setupSubViews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSArray *groupAnimations; // @synthesize groupAnimations;
@property(nonatomic, retain) NSTimer *timer; // @synthesize timer;
@property(nonatomic, copy) NSArray *views; // @synthesize views;
@property(nonatomic, copy) NSArray *layers; // @synthesize layers;

@end

