//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$S10RealmSwift6ObjectCN.h"

@class NSString;

@interface _TtC7BingDic7Article : _$S10RealmSwift6ObjectCN
{
    // Error parsing type: , name: id
    // Error parsing type: , name: title
    // Error parsing type: , name: downloadUrl
    // Error parsing type: , name: isRecommand
    // Error parsing type: , name: text
    // Error parsing type: , name: originUrl
    // Error parsing type: , name: playUrl
    // Error parsing type: , name: searchKeyword
    // Error parsing type: , name: sourceId
    // Error parsing type: , name: txtKeyword
    // Error parsing type: , name: downloadState
    // Error parsing type: , name: hasViewed
    // Error parsing type: , name: downloadTicket
    // Error parsing type: , name: viewTicket
}

+ (id)articleWithJsonItemWithJsonItem:(id)arg1;
+ (id)kViewTicket;
+ (id)kDownloadTicket;
+ (id)kHasViewed;
+ (id)kDownloadState;
+ (id)kTxtKeyword;
+ (id)kSourceId;
+ (id)kSearchKeyword;
+ (id)kPlayUrl;
+ (id)kOriginUrl;
+ (id)kText;
+ (id)kIsRecommand;
+ (id)kDownloadUrl;
+ (id)kTitle;
+ (id)kId;
+ (id)articleWithPersistentHisArticleWithOldArticle:(id)arg1;
+ (id)articleWithPersistentArticleWithOldArticle:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithValue:(id)arg1 schema:(id)arg2;
- (id)initWithRealm:(id)arg1 schema:(id)arg2;
- (id)initWithValue:(id)arg1;
- (id)init;
- (id)getJsonItem;
@property(nonatomic, readonly) NSString *localAudioFileName;
@property(nonatomic, readonly) NSString *localAudioFilePath;
@property(nonatomic) double viewTicket; // @synthesize viewTicket;
@property(nonatomic) double downloadTicket; // @synthesize downloadTicket;
@property(nonatomic) _Bool hasViewed; // @synthesize hasViewed;
@property(nonatomic) long long downloadState; // @synthesize downloadState;
@property(nonatomic, copy) NSString *txtKeyword; // @synthesize txtKeyword;
@property(nonatomic) long long sourceId; // @synthesize sourceId;
@property(nonatomic, copy) NSString *searchKeyword; // @synthesize searchKeyword;
@property(nonatomic, copy) NSString *playUrl; // @synthesize playUrl;
@property(nonatomic, copy) NSString *originUrl; // @synthesize originUrl;
@property(nonatomic, copy) NSString *text; // @synthesize text;
@property(nonatomic) _Bool isRecommand; // @synthesize isRecommand;
@property(nonatomic, copy) NSString *downloadUrl; // @synthesize downloadUrl;
@property(nonatomic, copy) NSString *title; // @synthesize title;
@property(nonatomic) long long id; // @synthesize id;

@end

