//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "_TtP7BingDic19AuthRequestProtocol_-Protocol.h"

@class NSString;

@interface _TtC7BingDic15AuthRequestBase : NSObject <_TtP7BingDic19AuthRequestProtocol_>
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: url
    // Error parsing type: , name: requestType
}

- (CDUnknownBlockType).cxx_destruct;
- (void)beginUserInfoParsingWithJson:(id)arg1;
- (void)beginUserInfoRequestByAccessJson:(id)arg1;
- (void)beginAccessTokenRequestByCode:(id)arg1;
- (void)beginCodeRequest;
- (_Bool)handleOpenURLWithUrl:(id)arg1;
- (void)beginRequest;
- (id)init;
@property(nonatomic, copy) NSString *url; // @synthesize url;

@end

