//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic15HttpRequestBase.h"

@class NSArray, NSString;

@interface _TtC7BingDic18ArticleListRequest : _TtC7BingDic15HttpRequestBase
{
    // Error parsing type: , name: oldUrl
    // Error parsing type: , name: newUrl
    // Error parsing type: , name: articles
    // Error parsing type: , name: id
    // Error parsing type: , name: rowValue
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithResponse:(CDUnknownBlockType)arg1;
- (void)responseWithResponseData:(id)arg1;
- (void)beginArticleListRequestWithId:(long long)arg1 row:(long long)arg2;
@property(nonatomic) long long rowValue; // @synthesize rowValue;
@property(nonatomic) long long id; // @synthesize id;
@property(nonatomic, copy) NSArray *articles; // @synthesize articles;
@property(nonatomic, readonly) NSString *newUrl; // @synthesize newUrl;
@property(nonatomic, readonly) NSString *oldUrl; // @synthesize oldUrl;

@end

