//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, _TtC7BingDic10ImageModel;

@interface _TtC7BingDic13ImageItemCell : UICollectionViewCell
{
    // Error parsing type: , name: imageV
    // Error parsing type: , name: itemSize
    // Error parsing type: , name: imageModel
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) _TtC7BingDic10ImageModel *imageModel; // @synthesize imageModel;
@property(nonatomic) __weak UIImageView *imageV; // @synthesize imageV;

@end

