//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue;

@interface _TtC7BingDic22ArticleDownloadManager : NSObject
{
    // Error parsing type: , name: operationQueue
}

+ (long long)countOfCores;
+ (id)sharedInstance;
+ (id)kDownloadListChangedNotification;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)removeDownloadOperationWithOp:(id)arg1;
- (_Bool)isDownloadingWithArticle:(id)arg1;
- (void)addDownloadItemWithArticle:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic, readonly) NSOperationQueue *operationQueue; // @synthesize operationQueue;

@end

