//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString;

@interface _TtC7BingDic27PronounceReadBaseController : UIViewController
{
    // Error parsing type: , name: dialogueTestSegueId
    // Error parsing type: , name: dialogueTestResultSegue
    // Error parsing type: , name: readTestSegueId
    // Error parsing type: , name: readScenesSegueId
    // Error parsing type: , name: isForOralDialogue
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)jumpUseAgreement;
- (void)jumpPrivacyPolicy;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)backAction;
- (void)initBackButton;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic) _Bool isForOralDialogue; // @synthesize isForOralDialogue;
@property(nonatomic, readonly) NSString *readScenesSegueId; // @synthesize readScenesSegueId;
@property(nonatomic, readonly) NSString *readTestSegueId; // @synthesize readTestSegueId;
@property(nonatomic, readonly) NSString *dialogueTestResultSegue; // @synthesize dialogueTestResultSegue;
@property(nonatomic, readonly) NSString *dialogueTestSegueId; // @synthesize dialogueTestSegueId;

@end

