//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic15HttpRequestBase.h"

@class NSString;

@interface _TtC7BingDic17SearchWordRequest : _TtC7BingDic15HttpRequestBase
{
    // Error parsing type: , name: URL_UNIFIED
    // Error parsing type: , name: result
    // Error parsing type: , name: needRequest
    // Error parsing type: , name: needBingSearchResult
    // Error parsing type: , name: word
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithResponse:(CDUnknownBlockType)arg1;
- (void)responseWithResponseData:(id)arg1;
- (_Bool)cacheJudgeWithData:(id)arg1;
- (void)beginSearchWordRequestBy:(id)arg1 needBingSearchResult:(_Bool)arg2;
@property(nonatomic) _Bool needRequest; // @synthesize needRequest;
@property(nonatomic, readonly) NSString *URL_UNIFIED; // @synthesize URL_UNIFIED;

@end

