//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XITranslatorController.h"

@class AVAudioPlayer, UIButton, UIView;

@interface _TtC7BingDic27RealtimeTranslateController : XITranslatorController
{
    // Error parsing type: , name: isHiddenAutomatically
    // Error parsing type: , name: OnClickNavigateButton
    // Error parsing type: , name: isRecording
    // Error parsing type: , name: player
    // Error parsing type: , name: btnBack
    // Error parsing type: , name: btnSetting
    // Error parsing type: , name: btnSpeak
    // Error parsing type: , name: btnNavigate
    // Error parsing type: , name: vTranslateContainer
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)textViewDidChange:(id)arg1;
- (void)showHideSubviewsWithIsShow:(_Bool)arg1;
- (void)btnNavigateClicked:(id)arg1;
- (void)btnSpeakClicked:(id)arg1;
- (void)itemSettingClicked:(id)arg1;
- (void)itemBackClicked:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) __weak UIView *vTranslateContainer; // @synthesize vTranslateContainer;
@property(nonatomic) __weak UIButton *btnNavigate; // @synthesize btnNavigate;
@property(nonatomic) __weak UIButton *btnSpeak; // @synthesize btnSpeak;
@property(nonatomic) __weak UIButton *btnSetting; // @synthesize btnSetting;
@property(nonatomic) __weak UIButton *btnBack; // @synthesize btnBack;
@property(nonatomic, retain) AVAudioPlayer *player; // @synthesize player;
@property(nonatomic) _Bool isRecording; // @synthesize isRecording;
@property(nonatomic, copy) CDUnknownBlockType OnClickNavigateButton; // @synthesize OnClickNavigateButton;
@property(nonatomic) _Bool isHiddenAutomatically; // @synthesize isHiddenAutomatically;

@end

