//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic28ResultPageBaseViewController.h"

@class NSString, UIView;

@interface _TtC7BingDic24MoreOxfordViewController : _TtC7BingDic28ResultPageBaseViewController
{
    // Error parsing type: , name: speechBtnY
    // Error parsing type: , name: speechBtnWidth
    // Error parsing type: , name: speechBtnHeight
    // Error parsing type: , name: oxfordViewModel
    // Error parsing type: , name: speechButtons
    // Error parsing type: , name: dataArray
    // Error parsing type: , name: cellArray
    // Error parsing type: , name: speechBtnContainerView
    // Error parsing type: , name: headWord
    // Error parsing type: , name: oxfordModels
    // Error parsing type: , name: currentOxfordCellLayouts
    // Error parsing type: , name: allOxfordCellLayouts
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)switchSpeechWithSender:(id)arg1;
@property(nonatomic, copy) NSString *headWord; // @synthesize headWord;
@property(nonatomic) __weak UIView *speechBtnContainerView; // @synthesize speechBtnContainerView;

@end

