//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC7BingDic15ReadScenesModel : NSObject
{
    // Error parsing type: , name: audioUrl
    // Error parsing type: , name: conversationsStr
    // Error parsing type: , name: title
    // Error parsing type: , name: type
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSString *type; // @synthesize type;
@property(nonatomic, copy) NSString *title; // @synthesize title;
@property(nonatomic, copy) NSString *conversationsStr; // @synthesize conversationsStr;
@property(nonatomic, copy) NSString *audioUrl; // @synthesize audioUrl;

@end

