//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC7BingDic24DictionaryCollectManager : NSObject
{
}

+ (id)getAllSentenceBookWithIsValid:(_Bool)arg1;
+ (id)getCurrentSampleSentenceBook;
+ (id)getDefaultSampleSentenceBook;
+ (id)getAllDailySentenceBookWithIsValid:(_Bool)arg1;
+ (id)getCurrentDailySentenceBook;
+ (id)getDefaultDailySentenceBook;
+ (void)markDeleteSentenceBookWithSbk:(id)arg1;
+ (void)deleteSentenceBookWithSbk:(id)arg1;
+ (void)setDefaultSentenceBookWithSentenceBook:(id)arg1;
+ (void)changeSentenceBookDisplayNameWithSentenceBook:(id)arg1 name:(id)arg2;
+ (id)getSentenceBookWithId:(id)arg1;
+ (void)markDeleteWordBookWithWb:(id)arg1;
+ (void)deleteWordBookWithWb:(id)arg1;
+ (void)changeWordBookDisplayNameWithWordBook:(id)arg1 name:(id)arg2;
+ (void)setDefaultWordBookWithWordBook:(id)arg1;
+ (id)createWordBookWithId:(id)arg1 name:(id)arg2 wordList:(id)arg3;
+ (id)getSearchHistoryBook;
+ (id)getCurrentWordBook;
+ (id)getDefaultWordBook;
+ (id)getAllWordBooksWithIsValid:(_Bool)arg1;
+ (id)getWordBookWithId:(id)arg1;
+ (void)removeSampleSentenceFromSampleSentenceBookWithSentence:(id)arg1;
+ (_Bool)sampleSentenceIsCollectionWithSentence:(id)arg1;
+ (void)removeDailySentenceFromDailySentenceBookWithSentence:(id)arg1;
+ (_Bool)dailySentenceIsCollectionWithSentence:(id)arg1;
+ (void)removeWordFromWordBookWithWord:(id)arg1;
+ (_Bool)wordIsCollectionWithWord:(id)arg1;
+ (void)clearCollectContent;
+ (id)defaultHistoryBookID;
+ (id)defaultWordBookID;
+ (id)defaultDailySentenceBookID;
+ (id)defaultSampleSentenceBookID;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

