//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

#import "UITextFieldDelegate-Protocol.h"

@interface _TtC7BingDic9SearchBox : UITextField <UITextFieldDelegate>
{
    // Error parsing type: , name: searchDelegate
}

- (CDUnknownBlockType).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)textFieldDidChangeWithTextField:(id)arg1;
- (void)drawPlaceholderInRect:(struct CGRect)arg1;
- (void)awakeFromNib;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

