//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC7BingDic13AudioRecorder : NSObject
{
    // Error parsing type: , name: recorder
    // Error parsing type: , name: meterUpdateFrequency
    // Error parsing type: , name: timer
    // Error parsing type: , name: recordTime
    // Error parsing type: , name: meteringEnabled
    // Error parsing type: , name: metersHandle
    // Error parsing type: , name: timeHandle
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)updateMeter;
- (void)finish;
- (void)delete;
- (void)resume;
- (void)pause;
- (void)startRecordWith:(id)arg1;
@property(nonatomic, readonly) _Bool recording;
@property(nonatomic, copy) CDUnknownBlockType timeHandle; // @synthesize timeHandle;
@property(nonatomic, copy) CDUnknownBlockType metersHandle; // @synthesize metersHandle;
@property(nonatomic) _Bool meteringEnabled; // @synthesize meteringEnabled;
@property(nonatomic) double recordTime; // @synthesize recordTime;

@end

