//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSDateFormatter, UIBarButtonItem, UIButton, UIDatePicker, UILabel, UISwitch, UIView, _TtC7BingDic19ReciteWordsCategory;

@interface _TtC7BingDic34ReciteWordsSetRemindViewController : UIViewController
{
    // Error parsing type: , name: lblRemindTitle
    // Error parsing type: , name: lblRemidTime
    // Error parsing type: , name: swRemindState
    // Error parsing type: , name: pkTime
    // Error parsing type: , name: btnFinish
    // Error parsing type: , name: finishView
    // Error parsing type: , name: btnBack
    // Error parsing type: , name: category
    // Error parsing type: , name: isAddMode
    // Error parsing type: , name: formatter
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)btnFinishClick:(id)arg1;
- (void)pickerRemindTimeChanged:(id)arg1;
- (void)swRemindStateChanged:(id)arg1;
- (void)btnBackClick:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) NSDateFormatter *formatter; // @synthesize formatter;
@property(nonatomic) _Bool isAddMode; // @synthesize isAddMode;
@property(nonatomic, retain) _TtC7BingDic19ReciteWordsCategory *category; // @synthesize category;
@property(nonatomic) __weak UIBarButtonItem *btnBack; // @synthesize btnBack;
@property(nonatomic) __weak UIView *finishView; // @synthesize finishView;
@property(nonatomic) __weak UIButton *btnFinish; // @synthesize btnFinish;
@property(nonatomic) __weak UIDatePicker *pkTime; // @synthesize pkTime;
@property(nonatomic) __weak UISwitch *swRemindState; // @synthesize swRemindState;
@property(nonatomic) __weak UILabel *lblRemidTime; // @synthesize lblRemidTime;
@property(nonatomic) __weak UILabel *lblRemindTitle; // @synthesize lblRemindTitle;

@end

