//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "DBSphereViewProtocl-Protocol.h"

@class DBSphereView, NSArray, NSString, NSTimer, UIButton, _TtC7BingDic12WordCardView, _TtC7BingDic23DictionarySearchManager;

@interface _TtC7BingDic27WordEmbeddingViewController : UIViewController <DBSphereViewProtocl>
{
    // Error parsing type: , name: sphereViewTopMargin
    // Error parsing type: , name: sphereViewLeftMargin
    // Error parsing type: , name: wordBtnWidth
    // Error parsing type: , name: wordBtnHeight
    // Error parsing type: , name: sphereHeight
    // Error parsing type: , name: sphereView
    // Error parsing type: , name: wordCard
    // Error parsing type: , name: dictSearchMananger
    // Error parsing type: , name: currentWordBtn
    // Error parsing type: , name: stopFlag
    // Error parsing type: , name: viewCompleted
    // Error parsing type: , name: source
    // Error parsing type: , name: headWord
    // Error parsing type: , name: errorTimer
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)queryResultFailed;
- (void)sphereViewDraging;
- (void)showCollectionViewWithSender:(id)arg1 word:(id)arg2;
- (void)hideWordCard;
- (void)showWordCardWithButton:(id)arg1;
- (void)alertError;
- (void)responseWithRequest:(id)arg1;
- (void)closeBtnTapped:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) NSTimer *errorTimer; // @synthesize errorTimer;
@property(nonatomic, copy) NSString *headWord; // @synthesize headWord;
@property(nonatomic, copy) NSArray *source; // @synthesize source;
@property(nonatomic) _Bool viewCompleted; // @synthesize viewCompleted;
@property(nonatomic) _Bool stopFlag; // @synthesize stopFlag;
@property(nonatomic, retain) UIButton *currentWordBtn; // @synthesize currentWordBtn;
@property(nonatomic, retain) _TtC7BingDic23DictionarySearchManager *dictSearchMananger; // @synthesize dictSearchMananger;
@property(nonatomic) __weak _TtC7BingDic12WordCardView *wordCard; // @synthesize wordCard;
@property(nonatomic) __weak DBSphereView *sphereView; // @synthesize sphereView;

@end

