//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIColor;

@interface _TtC7BingDic21ScrollPageManagerView : UIView
{
    // Error parsing type: , name: _titleView
    // Error parsing type: , name: _scrollView
    // Error parsing type: , name: titleHeight
    // Error parsing type: , name: titles
    // Error parsing type: , name: action
    // Error parsing type: , name: titleNormalColor
    // Error parsing type: , name: titleSelectColor
    // Error parsing type: , name: titleItemStyle
    // Error parsing type: , name: pageViews
}

- (CDUnknownBlockType).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)selectIndexWithIndex:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSArray *pageViews; // @synthesize pageViews;
@property(nonatomic, retain) UIColor *titleSelectColor; // @synthesize titleSelectColor;
@property(nonatomic, retain) UIColor *titleNormalColor; // @synthesize titleNormalColor;
@property(nonatomic, copy) CDUnknownBlockType action; // @synthesize action;
@property(nonatomic, copy) NSArray *titles; // @synthesize titles;
@property(nonatomic) double titleHeight; // @synthesize titleHeight;

@end

