//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic20ResultPageCellLayout.h"

@interface _TtC7BingDic20InflectionCellLayout : _TtC7BingDic20ResultPageCellLayout
{
    // Error parsing type: , name: inflectionCellTopPadding
    // Error parsing type: , name: inflectionVPadding
    // Error parsing type: , name: typeFrameList
    // Error parsing type: , name: inflectionFrameList
    // Error parsing type: , name: inflections
}

@end

