//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSString, UITableView;

@interface _TtC7BingDic26DownloadListViewController : UIViewController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: kEmptyCellId
    // Error parsing type: , name: kDownloadCellId
    // Error parsing type: , name: operations
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateList;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLoad;
@property(nonatomic, copy) NSArray *operations; // @synthesize operations;
@property(nonatomic, readonly) NSString *kDownloadCellId; // @synthesize kDownloadCellId;
@property(nonatomic, readonly) NSString *kEmptyCellId; // @synthesize kEmptyCellId;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;

@end

