//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic22SODBottomContainerView.h"

@interface _TtC7BingDic22SODBottomContainerView (BingDic)
- (void)btnRecordTouchUpInside:(id)arg1;
- (void)btnRecordTouchUpOutside:(id)arg1;
- (void)btnRecordTouchDragOutside:(id)arg1;
- (void)btnRecordTouchDragInside:(id)arg1;
- (void)btnRecordTouchDown:(id)arg1;
- (void)btnNextClicked:(id)arg1;
- (void)useAgreementClick:(id)arg1;
- (void)privacyPolicyClick:(id)arg1;
@end

