//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSString, UIButton, UITableView, _TtC7BingDic12SentenceBook;

@interface _TtC7BingDic26SentenceListViewController : UIViewController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: btnSort
    // Error parsing type: , name: kCollectionSegueId
    // Error parsing type: , name: kSentenceCellId
    // Error parsing type: , name: imgBack
    // Error parsing type: , name: type
    // Error parsing type: , name: sentenceList
    // Error parsing type: , name: firstLoad
    // Error parsing type: , name: selectHandler
    // Error parsing type: , name: userDefaultKey
    // Error parsing type: , name: defaultRawValue
    // Error parsing type: , name: sentenceBook
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)btnSortClick:(id)arg1;
- (void)btnBackClick;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) _TtC7BingDic12SentenceBook *sentenceBook; // @synthesize sentenceBook;
@property(nonatomic, copy) NSString *defaultRawValue; // @synthesize defaultRawValue;
@property(nonatomic, copy) NSString *userDefaultKey; // @synthesize userDefaultKey;
@property(nonatomic) _Bool firstLoad; // @synthesize firstLoad;
@property(nonatomic, copy) NSArray *sentenceList; // @synthesize sentenceList;
@property(nonatomic, readonly) NSString *imgBack; // @synthesize imgBack;
@property(nonatomic, readonly) NSString *kSentenceCellId; // @synthesize kSentenceCellId;
@property(nonatomic, readonly) NSString *kCollectionSegueId; // @synthesize kCollectionSegueId;
@property(nonatomic) __weak UIButton *btnSort; // @synthesize btnSort;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;

@end

