//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSDictionary, NSString, UITableView, _TtC7BingDic28RadioRightNavigationItemView;

@interface _TtC7BingDic25ChannelListViewController : UIViewController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: rightNavigationBar
    // Error parsing type: , name: kChannelCellId
    // Error parsing type: , name: kArticleListSegueId
    // Error parsing type: , name: cellHeight
    // Error parsing type: , name: channels
    // Error parsing type: , name: channelArticles
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)rightNavigationBarClicked;
- (void)responseWithRequest:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic, copy) NSDictionary *channelArticles; // @synthesize channelArticles;
@property(nonatomic, readonly) double cellHeight; // @synthesize cellHeight;
@property(nonatomic, readonly) NSString *kArticleListSegueId; // @synthesize kArticleListSegueId;
@property(nonatomic, readonly) NSString *kChannelCellId; // @synthesize kChannelCellId;
@property(nonatomic, retain) _TtC7BingDic28RadioRightNavigationItemView *rightNavigationBar; // @synthesize rightNavigationBar;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;

@end

