//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class UIButton, UILabel, UIView;

@interface _TtC7BingDic33BDStudyMyCollectionListHeaderView : UITableViewHeaderFooterView
{
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: addButton
    // Error parsing type: , name: lineView
    // Error parsing type: , name: addButtonClickedAction
    // Error parsing type: , name: index
}

- (CDUnknownBlockType).cxx_destruct;
- (void)addButtonClickedWithSender:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1;
@property(nonatomic) long long index; // @synthesize index;
@property(nonatomic, copy) CDUnknownBlockType addButtonClickedAction; // @synthesize addButtonClickedAction;
@property(nonatomic, retain) UIView *lineView; // @synthesize lineView;
@property(nonatomic, retain) UIButton *addButton; // @synthesize addButton;
@property(nonatomic, retain) UILabel *titleLabel; // @synthesize titleLabel;

@end

