//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$S10RealmSwift6ObjectCN.h"

@class NSString;

@interface _TtC7BingDic18OfflinePackageItem : _$S10RealmSwift6ObjectCN
{
    // Error parsing type: , name: id
    // Error parsing type: , name: name
    // Error parsing type: , name: url
    // Error parsing type: , name: versionNo
    // Error parsing type: , name: itemCount
    // Error parsing type: , name: size
}

+ (id)itemWithJsonItemWithJsonItem:(id)arg1;
+ (id)ignoredProperties;
+ (id)primaryKey;
+ (id)kSize;
+ (id)kItemCount;
+ (id)kVersionNo;
+ (id)kUrl;
+ (id)kName;
+ (id)kId;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithValue:(id)arg1 schema:(id)arg2;
- (id)initWithRealm:(id)arg1 schema:(id)arg2;
- (id)initWithValue:(id)arg1;
- (id)init;
@property(nonatomic, readonly) NSString *localFilePath;
@property(nonatomic) double size; // @synthesize size;
@property(nonatomic) long long itemCount; // @synthesize itemCount;
@property(nonatomic) long long versionNo; // @synthesize versionNo;
@property(nonatomic, copy) NSString *url; // @synthesize url;
@property(nonatomic, copy) NSString *name; // @synthesize name;
@property(nonatomic) long long id; // @synthesize id;

@end

