//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIImageView, UILabel, UITextView;

@interface _TtC7BingDic19AboutViewController : UIViewController
{
    // Error parsing type: , name: imgLogo
    // Error parsing type: , name: txtCopyright
    // Error parsing type: , name: lblLicense
    // Error parsing type: , name: lblPrivacy
    // Error parsing type: , name: kLicenseSegueId
    // Error parsing type: , name: kPrivacySegueId
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)lblStatementTap:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic, readonly) NSString *kPrivacySegueId; // @synthesize kPrivacySegueId;
@property(nonatomic, readonly) NSString *kLicenseSegueId; // @synthesize kLicenseSegueId;
@property(nonatomic) __weak UILabel *lblPrivacy; // @synthesize lblPrivacy;
@property(nonatomic) __weak UILabel *lblLicense; // @synthesize lblLicense;
@property(nonatomic) __weak UITextView *txtCopyright; // @synthesize txtCopyright;
@property(nonatomic) __weak UIImageView *imgLogo; // @synthesize imgLogo;

@end

