//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic25ArticleListViewController.h"

@class UIImageView, UILabel, UIView, _TtC7BingDic28RadioRightNavigationItemView;

@interface _TtC7BingDic31OnlineArticleListViewController : _TtC7BingDic25ArticleListViewController
{
    // Error parsing type: , name: imgCover
    // Error parsing type: , name: topTitleLabel
    // Error parsing type: , name: numberLabel
    // Error parsing type: , name: playButton
    // Error parsing type: , name: playButtonLabel
    // Error parsing type: , name: imgCoverBackgroundView
    // Error parsing type: , name: channel
    // Error parsing type: , name: rightNavigationBar
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)responseWithRequest:(id)arg1;
- (void)rightNavigationBarClicked;
- (void)btnPlayClick:(id)arg1;
- (void)radioPlayerCurrentArticlePlayItemChangedWithNotification:(id)arg1;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic, retain) _TtC7BingDic28RadioRightNavigationItemView *rightNavigationBar; // @synthesize rightNavigationBar;
@property(nonatomic) __weak UIView *imgCoverBackgroundView; // @synthesize imgCoverBackgroundView;
@property(nonatomic) __weak UILabel *playButtonLabel; // @synthesize playButtonLabel;
@property(nonatomic) __weak UIView *playButton; // @synthesize playButton;
@property(nonatomic) __weak UILabel *numberLabel; // @synthesize numberLabel;
@property(nonatomic) __weak UILabel *topTitleLabel; // @synthesize topTitleLabel;
@property(nonatomic) __weak UIImageView *imgCover; // @synthesize imgCover;

@end

