//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic15AuthRequestBase.h"

#import "TencentSessionDelegate-Protocol.h"

@class TencentOAuth;

@interface _TtC7BingDic13QQAuthRequest : _TtC7BingDic15AuthRequestBase <TencentSessionDelegate>
{
    // Error parsing type: , name: oAuth
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)getUserInfoResponse:(id)arg1;
- (void)tencentDidNotNetWork;
- (void)tencentDidNotLogin:(_Bool)arg1;
- (void)tencentDidLogin;
- (void)beginUserInfoParsingWithJson:(id)arg1;
- (_Bool)handleOpenURLWithUrl:(id)arg1;
- (void)beginCodeRequest;
@property(nonatomic, retain) TencentOAuth *oAuth; // @synthesize oAuth;

@end

