//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic15HttpRequestBase.h"

@class NSString;

@interface _TtC7BingDic15SentenceRequest : _TtC7BingDic15HttpRequestBase
{
    // Error parsing type: , name: URL_SENTENCE
    // Error parsing type: , name: result
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithResponse:(CDUnknownBlockType)arg1;
- (void)responseWithResponseData:(id)arg1;
- (void)beginSentenceRequestBy:(id)arg1 offset:(long long)arg2 count:(long long)arg3;
@property(nonatomic, readonly) NSString *URL_SENTENCE; // @synthesize URL_SENTENCE;

@end

