//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class _TtC7BingDic16ResultPageButton;

@interface _TtC7BingDic18SectionControlCell : UITableViewCell
{
    // Error parsing type: , name: collapseAllBtn
    // Error parsing type: , name: expandAllBtn
    // Error parsing type: , name: seeAllBtn
    // Error parsing type: , name: errorBtn
    // Error parsing type: , name: delegate
    // Error parsing type: , name: searchOnline
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)errorBtnClick:(id)arg1;
- (void)seeAllBtnClick:(id)arg1;
- (void)expandAllBtnClick:(id)arg1;
- (void)collapseAllBtnClick:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic, copy) CDUnknownBlockType searchOnline; // @synthesize searchOnline;
@property(nonatomic) __weak _TtC7BingDic16ResultPageButton *errorBtn; // @synthesize errorBtn;
@property(nonatomic) __weak _TtC7BingDic16ResultPageButton *seeAllBtn; // @synthesize seeAllBtn;
@property(nonatomic) __weak _TtC7BingDic16ResultPageButton *expandAllBtn; // @synthesize expandAllBtn;
@property(nonatomic) __weak _TtC7BingDic16ResultPageButton *collapseAllBtn; // @synthesize collapseAllBtn;

@end

