//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC7BingDic11BDCoverView : UIView
{
    // Error parsing type: , name: arrowLength
    // Error parsing type: , name: arrowTopRadius
    // Error parsing type: , name: arrowLineWidth
    // Error parsing type: , name: margin
    // Error parsing type: , name: brightFrame
    // Error parsing type: , name: rectCorner
    // Error parsing type: , name: cornerRadius
    // Error parsing type: , name: arrowFrame
    // Error parsing type: , name: arrowDirection
    // Error parsing type: , name: arrowColor
    // Error parsing type: , name: completion
}

+ (void)hide;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;

@end

