//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC7BingDic18ReciteWordsManager : NSObject
{
}

+ (void)removeNotificationWithCategory:(id)arg1;
+ (void)addNotificationFor:(id)arg1;
+ (void)removeWordWithWordString:(id)arg1;
+ (void)saveWordWithWord:(id)arg1;
+ (void)updateRemindSettingWithCategory:(id)arg1 state:(_Bool)arg2 time:(id)arg3;
+ (void)updatePlanWithCategory:(id)arg1 planCount:(long long)arg2 playDays:(long long)arg3;
+ (id)getAllCategoryList;
+ (id)getCategoryList;
+ (id)getCategoryWithGuid:(id)arg1;
+ (void)setLastCategoryWithCategory:(id)arg1;
+ (id)getLastCategory;
+ (_Bool)hasCategories;
+ (void)deleteCategoryWithCategory:(id)arg1;
+ (void)addCategoryWithCategory:(id)arg1;
+ (id)kReminderId;
+ (id)kReminderKey;
+ (id)kLastReciteWordsCategory;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

