//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, _TtC7BingDic16ResultPageButton;

@interface _TtC7BingDic11SeeMoreCell : UITableViewCell
{
    // Error parsing type: , name: isForWebContent
    // Error parsing type: , name: headWord
    // Error parsing type: , name: isClearCacheNeeded
    // Error parsing type: , name: showWebView
    // Error parsing type: , name: type
    // Error parsing type: , name: showMoreViewController
    // Error parsing type: , name: seeMoreBtn
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)seeMoreBtnTapped:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic) __weak _TtC7BingDic16ResultPageButton *seeMoreBtn; // @synthesize seeMoreBtn;
@property(nonatomic, copy) CDUnknownBlockType showWebView; // @synthesize showWebView;
@property(nonatomic) _Bool isClearCacheNeeded; // @synthesize isClearCacheNeeded;
@property(nonatomic, copy) NSString *headWord; // @synthesize headWord;
@property(nonatomic) _Bool isForWebContent; // @synthesize isForWebContent;

@end

