//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSTimer, UIButton, UIImageView, UILabel;

@interface _TtC7BingDic24BDActivityViewController : UIViewController
{
    // Error parsing type: , name: bgImageView
    // Error parsing type: , name: countLabel
    // Error parsing type: , name: jumpButton
    // Error parsing type: , name: timer
    // Error parsing type: , name: count
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)showTimerEvent;
- (void)imageTappedWithGesture:(id)arg1;
- (void)jumpButtonClicked:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic) long long count; // @synthesize count;
@property(nonatomic, retain) NSTimer *timer; // @synthesize timer;
@property(nonatomic) __weak UIButton *jumpButton; // @synthesize jumpButton;
@property(nonatomic) __weak UILabel *countLabel; // @synthesize countLabel;
@property(nonatomic) __weak UIImageView *bgImageView; // @synthesize bgImageView;

@end

