//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UITableView, _TtC7BingDic25StudyPlayArticleStateView;

@interface _TtC7BingDic19StudyViewController : UIViewController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: playView
    // Error parsing type: , name: kTitleLeftImageCell
    // Error parsing type: , name: kStudyRootListDetailsTableViewCellId
    // Error parsing type: , name: kTitleCollectCellId
    // Error parsing type: , name: kTitleViewCell
    // Error parsing type: , name: kTitleImageCell
    // Error parsing type: , name: kRadioCell
    // Error parsing type: , name: kPlayArticleTableViewCell
    // Error parsing type: , name: kWordbookSegueId
    // Error parsing type: , name: kSentenceListSegueId
    // Error parsing type: , name: kWordStockSegueId
    // Error parsing type: , name: kWordChallengeSegueId
    // Error parsing type: , name: kOralChallengeSegueId
    // Error parsing type: , name: kChannelListSegueId
    // Error parsing type: , name: kArticleListSegueId
    // Error parsing type: , name: kOfflineRadioSegueId
    // Error parsing type: , name: kReciteWordsSegueId
    // Error parsing type: , name: kReadHomeSegueId
    // Error parsing type: , name: imgMyCollection
    // Error parsing type: , name: imgWordbook
    // Error parsing type: , name: imgDailySentence
    // Error parsing type: , name: imgSampleSentence
    // Error parsing type: , name: imgWordStock
    // Error parsing type: , name: imgWordChallenge
    // Error parsing type: , name: icoXiaoY
    // Error parsing type: , name: imgXiaoY
    // Error parsing type: , name: icoAILaboratory
    // Error parsing type: , name: imgAILaboratory
    // Error parsing type: , name: icoSceneOralDialogue
    // Error parsing type: , name: imgSceneOralDialogue
    // Error parsing type: , name: imgOralChallenge
    // Error parsing type: , name: icoBingRadio
    // Error parsing type: , name: icoOfflineRadio
    // Error parsing type: , name: icoReciteWords
    // Error parsing type: , name: imgReciteWords
    // Error parsing type: , name: icoVocabularyTest
    // Error parsing type: , name: icoGrammarVocabularyTest
    // Error parsing type: , name: icoPronunciationReadingTest
    // Error parsing type: , name: imgGrammarVocabularyTest
    // Error parsing type: , name: imgPronunciationReadingTest
    // Error parsing type: , name: imgVocabularyTest
    // Error parsing type: , name: titleCellHeight
    // Error parsing type: , name: titleImageCellHeight
    // Error parsing type: , name: titleLeftImageCellHeight
    // Error parsing type: , name: aiLaboratoryBannerSize
    // Error parsing type: , name: sceneOralDialogueBannerSize
    // Error parsing type: , name: pronunciationReadingTestBannerSize
    // Error parsing type: , name: grammarVocabularyTestBannerSize
    // Error parsing type: , name: vocabularyTestBannerSize
    // Error parsing type: , name: oralTrainingBannerSize
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)didClickRadioItemWithIndex:(long long)arg1;
- (void)didClickReciteWordsWithIndex:(long long)arg1;
- (void)didClickXiaoYWithIndex:(long long)arg1;
- (void)didClickVocabularyTestItemWithIndex:(long long)arg1;
- (void)didClickGrammarVocabularyTestItemWithIndex:(long long)arg1;
- (void)didClickPronounceReadTestItemWithIndex:(long long)arg1;
- (void)didClickSceneOralDialogueItemWithIndex:(long long)arg1;
- (void)didClickAILabortoryItemWithIndex:(long long)arg1;
- (void)didClickCollectItemWithIndex:(long long)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)toMyCollectionAction;
- (void)topViewClickedWithGesture:(id)arg1;
- (void)radioPlayerPlayFailed;
- (void)radioPlayerPlayStateChanged;
- (void)updateTopPlayView;
- (void)showTopPlayView;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, readonly) struct CGSize oralTrainingBannerSize; // @synthesize oralTrainingBannerSize;
@property(nonatomic, readonly) struct CGSize vocabularyTestBannerSize; // @synthesize vocabularyTestBannerSize;
@property(nonatomic, readonly) struct CGSize grammarVocabularyTestBannerSize; // @synthesize grammarVocabularyTestBannerSize;
@property(nonatomic, readonly) struct CGSize pronunciationReadingTestBannerSize; // @synthesize pronunciationReadingTestBannerSize;
@property(nonatomic, readonly) struct CGSize sceneOralDialogueBannerSize; // @synthesize sceneOralDialogueBannerSize;
@property(nonatomic, readonly) struct CGSize aiLaboratoryBannerSize; // @synthesize aiLaboratoryBannerSize;
@property(nonatomic, readonly) double titleLeftImageCellHeight; // @synthesize titleLeftImageCellHeight;
@property(nonatomic, readonly) double titleImageCellHeight; // @synthesize titleImageCellHeight;
@property(nonatomic, readonly) double titleCellHeight; // @synthesize titleCellHeight;
@property(nonatomic, readonly) NSString *imgVocabularyTest; // @synthesize imgVocabularyTest;
@property(nonatomic, readonly) NSString *imgPronunciationReadingTest; // @synthesize imgPronunciationReadingTest;
@property(nonatomic, readonly) NSString *imgGrammarVocabularyTest; // @synthesize imgGrammarVocabularyTest;
@property(nonatomic, readonly) NSString *icoPronunciationReadingTest; // @synthesize icoPronunciationReadingTest;
@property(nonatomic, readonly) NSString *icoGrammarVocabularyTest; // @synthesize icoGrammarVocabularyTest;
@property(nonatomic, readonly) NSString *icoVocabularyTest; // @synthesize icoVocabularyTest;
@property(nonatomic, readonly) NSString *imgReciteWords; // @synthesize imgReciteWords;
@property(nonatomic, readonly) NSString *icoReciteWords; // @synthesize icoReciteWords;
@property(nonatomic, readonly) NSString *icoOfflineRadio; // @synthesize icoOfflineRadio;
@property(nonatomic, readonly) NSString *icoBingRadio; // @synthesize icoBingRadio;
@property(nonatomic, readonly) NSString *imgOralChallenge; // @synthesize imgOralChallenge;
@property(nonatomic, readonly) NSString *imgSceneOralDialogue; // @synthesize imgSceneOralDialogue;
@property(nonatomic, readonly) NSString *icoSceneOralDialogue; // @synthesize icoSceneOralDialogue;
@property(nonatomic, readonly) NSString *imgAILaboratory; // @synthesize imgAILaboratory;
@property(nonatomic, readonly) NSString *icoAILaboratory; // @synthesize icoAILaboratory;
@property(nonatomic, readonly) NSString *imgXiaoY; // @synthesize imgXiaoY;
@property(nonatomic, readonly) NSString *icoXiaoY; // @synthesize icoXiaoY;
@property(nonatomic, readonly) NSString *imgWordChallenge; // @synthesize imgWordChallenge;
@property(nonatomic, readonly) NSString *imgWordStock; // @synthesize imgWordStock;
@property(nonatomic, readonly) NSString *imgSampleSentence; // @synthesize imgSampleSentence;
@property(nonatomic, readonly) NSString *imgDailySentence; // @synthesize imgDailySentence;
@property(nonatomic, readonly) NSString *imgWordbook; // @synthesize imgWordbook;
@property(nonatomic, readonly) NSString *imgMyCollection; // @synthesize imgMyCollection;
@property(nonatomic, readonly) NSString *kReadHomeSegueId; // @synthesize kReadHomeSegueId;
@property(nonatomic, readonly) NSString *kReciteWordsSegueId; // @synthesize kReciteWordsSegueId;
@property(nonatomic, readonly) NSString *kOfflineRadioSegueId; // @synthesize kOfflineRadioSegueId;
@property(nonatomic, readonly) NSString *kArticleListSegueId; // @synthesize kArticleListSegueId;
@property(nonatomic, readonly) NSString *kChannelListSegueId; // @synthesize kChannelListSegueId;
@property(nonatomic, readonly) NSString *kOralChallengeSegueId; // @synthesize kOralChallengeSegueId;
@property(nonatomic, readonly) NSString *kWordChallengeSegueId; // @synthesize kWordChallengeSegueId;
@property(nonatomic, readonly) NSString *kWordStockSegueId; // @synthesize kWordStockSegueId;
@property(nonatomic, readonly) NSString *kSentenceListSegueId; // @synthesize kSentenceListSegueId;
@property(nonatomic, readonly) NSString *kWordbookSegueId; // @synthesize kWordbookSegueId;
@property(nonatomic, readonly) NSString *kPlayArticleTableViewCell; // @synthesize kPlayArticleTableViewCell;
@property(nonatomic, readonly) NSString *kRadioCell; // @synthesize kRadioCell;
@property(nonatomic, readonly) NSString *kTitleImageCell; // @synthesize kTitleImageCell;
@property(nonatomic, readonly) NSString *kTitleViewCell; // @synthesize kTitleViewCell;
@property(nonatomic, readonly) NSString *kTitleCollectCellId; // @synthesize kTitleCollectCellId;
@property(nonatomic, readonly) NSString *kStudyRootListDetailsTableViewCellId; // @synthesize kStudyRootListDetailsTableViewCellId;
@property(nonatomic, readonly) NSString *kTitleLeftImageCell; // @synthesize kTitleLeftImageCell;
@property(nonatomic, retain) _TtC7BingDic25StudyPlayArticleStateView *playView; // @synthesize playView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;

@end

