//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic28ResultPageBaseViewController.h"

@class NSArray, NSDictionary, NSString, NSTimer, UIButton, UIView, _TtC7BingDic14WebContentCell, _TtC7BingDic18SectionControlCell, _TtC7BingDic19QuickDefinitionCell, _TtC7BingDic22NoResultViewController, _TtC7BingDic23DictionarySearchManager;

@interface _TtC7BingDic24ResultPageViewController : _TtC7BingDic28ResultPageBaseViewController
{
    // Error parsing type: , name: translationHeaderCellIdentifier
    // Error parsing type: , name: inflectionCellIdentifier
    // Error parsing type: , name: definitionCellIdentifier
    // Error parsing type: , name: relatedWordsCellIdentifier
    // Error parsing type: , name: imageCellIdentifier
    // Error parsing type: , name: webDefinitionCellIdentifier
    // Error parsing type: , name: webResultCellIdentifier
    // Error parsing type: , name: webContentCellIdentifier
    // Error parsing type: , name: sectionHeaderIdentifier
    // Error parsing type: , name: seeMoreCellIdentifier
    // Error parsing type: , name: sectionControlCellIdentifier
    // Error parsing type: , name: seeWordEmbeddingCellIdentifier
    // Error parsing type: , name: wordEmbeddingCellHeight
    // Error parsing type: , name: sectionControllCellHeight
    // Error parsing type: , name: showWordEmbeddingSegue
    // Error parsing type: , name: showMoreSentenceSegue
    // Error parsing type: , name: showMoreOxford
    // Error parsing type: , name: showChangeOrder
    // Error parsing type: , name: noResultView
    // Error parsing type: , name: noResultVC
    // Error parsing type: , name: isPrimaryPage
    // Error parsing type: , name: query
    // Error parsing type: , name: quickDefinitionCell
    // Error parsing type: , name: sectionControlCell
    // Error parsing type: , name: webContentLayoutCell
    // Error parsing type: , name: quickDefinitionCellLayouts
    // Error parsing type: , name: oxfordCellLayouts
    // Error parsing type: , name: chCellLayouts
    // Error parsing type: , name: enCellLayouts
    // Error parsing type: , name: phraseCellLayouts
    // Error parsing type: , name: synonymCellLayouts
    // Error parsing type: , name: antonymCellLayouts
    // Error parsing type: , name: webDefinitionCellLayout
    // Error parsing type: , name: sampleSentenceCellLayouts
    // Error parsing type: , name: webResultCellHeights
    // Error parsing type: , name: webContentCellHeight
    // Error parsing type: , name: cellHeightDict
    // Error parsing type: , name: navigationBarTranslucent
    // Error parsing type: , name: isNewSearch
    // Error parsing type: , name: isEnsearchPreferred
    // Error parsing type: , name: isUpdateMenuNeeded
    // Error parsing type: , name: isReloadWebCellNeeded
    // Error parsing type: , name: dictSearchMananger
    // Error parsing type: , name: rawResult
    // Error parsing type: , name: btnQL
    // Error parsing type: , name: menuBg.storage
    // Error parsing type: , name: menuQL
    // Error parsing type: , name: isFirsrtLoad
    // Error parsing type: , name: msrKVOContext
    // Error parsing type: , name: result
    // Error parsing type: , name: errorTimer
}

+ (id)getInstanceBy:(id)arg1;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)btnQLClicked:(id)arg1;
- (void)ShowWordEmbeddingWithHeadWord:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)gotoOxfordWithHeadword:(id)arg1;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)queryResultFailed;
- (void)dealloc;
- (void)viewDidLoad;
@property(nonatomic, retain) NSTimer *errorTimer; // @synthesize errorTimer;
@property(nonatomic) __weak UIButton *btnQL; // @synthesize btnQL;
@property(nonatomic, retain) _TtC7BingDic23DictionarySearchManager *dictSearchMananger; // @synthesize dictSearchMananger;
@property(nonatomic) _Bool isReloadWebCellNeeded; // @synthesize isReloadWebCellNeeded;
@property(nonatomic) _Bool isUpdateMenuNeeded; // @synthesize isUpdateMenuNeeded;
@property(nonatomic) _Bool isEnsearchPreferred; // @synthesize isEnsearchPreferred;
@property(nonatomic) _Bool isNewSearch; // @synthesize isNewSearch;
@property(nonatomic) _Bool navigationBarTranslucent; // @synthesize navigationBarTranslucent;
@property(nonatomic, copy) NSDictionary *cellHeightDict; // @synthesize cellHeightDict;
@property(nonatomic, copy) NSArray *webResultCellHeights; // @synthesize webResultCellHeights;
@property(nonatomic, retain) _TtC7BingDic14WebContentCell *webContentLayoutCell; // @synthesize webContentLayoutCell;
@property(nonatomic, retain) _TtC7BingDic18SectionControlCell *sectionControlCell; // @synthesize sectionControlCell;
@property(nonatomic, retain) _TtC7BingDic19QuickDefinitionCell *quickDefinitionCell; // @synthesize quickDefinitionCell;
@property(nonatomic, copy) NSString *query; // @synthesize query;
@property(nonatomic) _Bool isPrimaryPage; // @synthesize isPrimaryPage;
@property(nonatomic) __weak _TtC7BingDic22NoResultViewController *noResultVC; // @synthesize noResultVC;
@property(nonatomic) __weak UIView *noResultView; // @synthesize noResultView;

@end

