//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue;

@interface _TtC7BingDic22PackageDownloadManager : NSObject
{
    // Error parsing type: , name: operationQueue
}

+ (id)sharedInstance;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (_Bool)isDownloadingWithItem:(id)arg1;
- (id)getDownloadOperationBy:(id)arg1;
- (id)addDownloadItemWithItem:(id)arg1;
@property(nonatomic, readonly) NSOperationQueue *operationQueue; // @synthesize operationQueue;

@end

