//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface _TtC7BingDic24VoiceTranslateMetersView : UIView
{
    // Error parsing type: , name: itemNum
    // Error parsing type: , name: metersLevels
}

- (CDUnknownBlockType).cxx_destruct;
- (void)reloadMetersViewWithLevels:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) NSArray *metersLevels; // @synthesize metersLevels;
@property(nonatomic) long long itemNum; // @synthesize itemNum;

@end

