//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSLayoutConstraint, NSString, UIButton, UIImageView, UILabel;

@interface _TtC7BingDic12WordCardView : UIView
{
    // Error parsing type: , name: pronVMargin
    // Error parsing type: , name: definitionBottomMargin
    // Error parsing type: , name: pronHMargin
    // Error parsing type: , name: maxDefinitionCount
    // Error parsing type: , name: topView
    // Error parsing type: , name: topTriangle
    // Error parsing type: , name: contentView
    // Error parsing type: , name: bottomView
    // Error parsing type: , name: bottomTriangle
    // Error parsing type: , name: headWordLbl
    // Error parsing type: , name: usPronBtn
    // Error parsing type: , name: ukPronBtn
    // Error parsing type: , name: definitionLbl
    // Error parsing type: , name: searchBtn
    // Error parsing type: , name: favoriteBtn
    // Error parsing type: , name: triangleWidthConstraint
    // Error parsing type: , name: topTriangleLeftConstraint
    // Error parsing type: , name: bottomTriangleLeftConstraint
    // Error parsing type: , name: contentViewHeightConstraint
    // Error parsing type: , name: delegate
    // Error parsing type: , name: definitionLabels
    // Error parsing type: , name: cardWidth
    // Error parsing type: , name: pronunciationSignature
    // Error parsing type: , name: pageString
    // Error parsing type: , name: showCollectionView
    // Error parsing type: , name: content
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setTriangleWithTopHidden:(_Bool)arg1 bottomHidden:(_Bool)arg2 tapWordCenterX:(double)arg3;
- (void)pronUkBtnClick:(id)arg1;
- (void)pronUsBtnClick:(id)arg1;
- (void)searchBtnClick:(id)arg1;
- (void)awakeFromNib;
- (void)favorateBtnClick:(id)arg1;
@property(nonatomic, copy) CDUnknownBlockType showCollectionView; // @synthesize showCollectionView;
@property(nonatomic, copy) NSString *pageString; // @synthesize pageString;
@property(nonatomic, copy) NSString *pronunciationSignature; // @synthesize pronunciationSignature;
@property(nonatomic, copy) NSArray *definitionLabels; // @synthesize definitionLabels;
@property(nonatomic) __weak NSLayoutConstraint *contentViewHeightConstraint; // @synthesize contentViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *bottomTriangleLeftConstraint; // @synthesize bottomTriangleLeftConstraint;
@property(nonatomic) __weak NSLayoutConstraint *topTriangleLeftConstraint; // @synthesize topTriangleLeftConstraint;
@property(nonatomic) __weak NSLayoutConstraint *triangleWidthConstraint; // @synthesize triangleWidthConstraint;
@property(nonatomic) __weak UIButton *favoriteBtn; // @synthesize favoriteBtn;
@property(nonatomic) __weak UIButton *searchBtn; // @synthesize searchBtn;
@property(nonatomic) __weak UILabel *definitionLbl; // @synthesize definitionLbl;
@property(nonatomic) __weak UIButton *ukPronBtn; // @synthesize ukPronBtn;
@property(nonatomic) __weak UIButton *usPronBtn; // @synthesize usPronBtn;
@property(nonatomic) __weak UILabel *headWordLbl; // @synthesize headWordLbl;
@property(nonatomic) __weak UIImageView *bottomTriangle; // @synthesize bottomTriangle;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView;
@property(nonatomic) __weak UIImageView *topTriangle; // @synthesize topTriangle;
@property(nonatomic) __weak UIView *topView; // @synthesize topView;

@end

