//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic27RealtimeTranslateController.h"

#import "IXILanguageSelectorClickListener-Protocol.h"

@interface _TtC7BingDic27RealtimeTranslateController (BingDic1) <IXILanguageSelectorClickListener>
- (void)onLanguageSelect:(_Bool)arg1 language:(id)arg2;
@end

