//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UILabel, _TtC7BingDic12ProgressView, _TtC7BingDic18OfflinePackageItem, _TtC7BingDic24PackageDownloadOperation;

@interface _TtC7BingDic27OfflinePackageTableViewCell : UITableViewCell
{
    // Error parsing type: , name: lblName
    // Error parsing type: , name: lblCount
    // Error parsing type: , name: lblSize
    // Error parsing type: , name: btnDownload
    // Error parsing type: , name: progressView
    // Error parsing type: , name: lblProgress
    // Error parsing type: , name: btnPause
    // Error parsing type: , name: item
    // Error parsing type: , name: downloadOperation
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)btnPauseClick:(id)arg1;
- (void)btnDownloadClick:(id)arg1;
- (void)updateProgressActionWithBytesWritten:(double)arg1 totalBytes:(double)arg2;
- (void)prepareForReuse;
- (void)awakeFromNib;
@property(nonatomic, retain) _TtC7BingDic24PackageDownloadOperation *downloadOperation; // @synthesize downloadOperation;
@property(nonatomic, retain) _TtC7BingDic18OfflinePackageItem *item; // @synthesize item;
@property(nonatomic) __weak UIButton *btnPause; // @synthesize btnPause;
@property(nonatomic) __weak UILabel *lblProgress; // @synthesize lblProgress;
@property(nonatomic) __weak _TtC7BingDic12ProgressView *progressView; // @synthesize progressView;
@property(nonatomic) __weak UIButton *btnDownload; // @synthesize btnDownload;
@property(nonatomic) __weak UILabel *lblSize; // @synthesize lblSize;
@property(nonatomic) __weak UILabel *lblCount; // @synthesize lblCount;
@property(nonatomic) __weak UILabel *lblName; // @synthesize lblName;

@end

