//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSMutableArray, UIButton, UILabel, UITableView, UIView, _TtC7BingDic16ResultPageButton, _TtC7BingDic24ResultPageViewController, _TtC7BingDic9SearchBox;

@interface _TtC7BingDic24DictionaryViewController : UIViewController
{
    // Error parsing type: , name: topBarView
    // Error parsing type: , name: searchBox
    // Error parsing type: , name: searchSuggestionTable
    // Error parsing type: , name: clearHistoryBtn
    // Error parsing type: , name: cancelBtn
    // Error parsing type: , name: historyTipLbl
    // Error parsing type: , name: resultPageView
    // Error parsing type: , name: resultPageVC
    // Error parsing type: , name: tableSource
    // Error parsing type: , name: showAS
    // Error parsing type: , name: trigerPasteBoardString
}

+ (id)getViewControllerOnStoryBoardWithVc:(id)arg1;
+ (id)pasteBoardCellIdentifier;
+ (id)searchSuggestionCellIdentifier;
+ (id)noResultVCIdentifier;
+ (id)dictionaryVCIdentifier;
+ (id)resultPageVCIdentifier;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (void)headerClick;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tabBarClearSearchContent;
- (void)doClearHistory;
- (void)clearHistoryBtnClick:(id)arg1;
- (void)reloadSearchSuggestionTableWithSearchText:(id)arg1;
- (void)searchBoxDoSearchWithSearchText:(id)arg1;
- (void)searchBoxTextDidChangedWithSearchText:(id)arg1;
- (void)searchBoxWillBeginEditingWithSearchText:(id)arg1;
- (void)keyboardWillChangeFrameWithNotification:(id)arg1;
- (void)clearResultPage;
- (void)refreshWithQuery:(id)arg1;
- (void)closeView:(id)arg1;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) _Bool trigerPasteBoardString; // @synthesize trigerPasteBoardString;
@property(nonatomic, retain) NSMutableArray *tableSource; // @synthesize tableSource;
@property(nonatomic) __weak _TtC7BingDic24ResultPageViewController *resultPageVC; // @synthesize resultPageVC;
@property(nonatomic) __weak UIView *resultPageView; // @synthesize resultPageView;
@property(nonatomic) __weak UILabel *historyTipLbl; // @synthesize historyTipLbl;
@property(nonatomic) __weak UIButton *cancelBtn; // @synthesize cancelBtn;
@property(nonatomic) __weak _TtC7BingDic16ResultPageButton *clearHistoryBtn; // @synthesize clearHistoryBtn;
@property(nonatomic) __weak UITableView *searchSuggestionTable; // @synthesize searchSuggestionTable;
@property(nonatomic) __weak _TtC7BingDic9SearchBox *searchBox; // @synthesize searchBox;
@property(nonatomic) __weak UIView *topBarView; // @synthesize topBarView;

@end

