//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIButton, UITableView;

@interface _TtC7BingDic26OfflineRadioViewController : UIViewController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: btnPlay
    // Error parsing type: , name: kCellId
    // Error parsing type: , name: kOfflineSegueId
    // Error parsing type: , name: kDownloadSegueId
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)updateList;
- (void)didReceiveMemoryWarning;
- (void)btnPlayClick;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, readonly) NSString *kDownloadSegueId; // @synthesize kDownloadSegueId;
@property(nonatomic, readonly) NSString *kOfflineSegueId; // @synthesize kOfflineSegueId;
@property(nonatomic, readonly) NSString *kCellId; // @synthesize kCellId;
@property(nonatomic) __weak UIButton *btnPlay; // @synthesize btnPlay;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;

@end

