//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _TtC7BingDic4User;

@interface _TtC7BingDic12UserInstance : NSObject
{
    // Error parsing type: , name: hasLogined
    // Error parsing type: , name: currentUser
}

+ (id)sharedInstance;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, retain) _TtC7BingDic4User *currentUser; // @synthesize currentUser;
@property(nonatomic) _Bool hasLogined; // @synthesize hasLogined;

@end

