//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, UIColor;

@interface _TtC7BingDic17BDActivityManager : NSObject
{
    // Error parsing type: , name: BingDictionaryLastActivityId
    // Error parsing type: , name: uploadFilePath
    // Error parsing type: , name: isNeedShow
    // Error parsing type: , name: plistDate
    // Error parsing type: , name: imageLocalPath
    // Error parsing type: , name: startTime
    // Error parsing type: , name: endTime
    // Error parsing type: , name: showTime
    // Error parsing type: , name: imageURL
    // Error parsing type: , name: activityURL
    // Error parsing type: , name: activityTitle
    // Error parsing type: , name: skipTextColor
    // Error parsing type: , name: isdownloadFailed
}

+ (id)BingDictionaryLastActivityShow;
+ (id)BDActivityBackgroundSessionId;
+ (id)share;
- (CDUnknownBlockType).cxx_destruct;
- (id)getActivityImageLocalPathWithImageId:(id)arg1 imageURL:(id)arg2;
- (void)downloadActivityImageFileWithImageLocalPath:(id)arg1 imageURL:(id)arg2;
- (void)downloadUpdateFileWithFileURL:(id)arg1;
- (void)dealPlistDataWithDicArray:(id)arg1;
- (void)chectUpdateFile;
- (id)init;
@property(nonatomic, retain) UIColor *skipTextColor; // @synthesize skipTextColor;
@property(nonatomic, copy) NSString *activityTitle; // @synthesize activityTitle;
@property(nonatomic, copy) NSString *activityURL; // @synthesize activityURL;
@property(nonatomic, copy) NSString *imageURL; // @synthesize imageURL;
@property(nonatomic) long long showTime; // @synthesize showTime;
@property(nonatomic) double endTime; // @synthesize endTime;
@property(nonatomic) double startTime; // @synthesize startTime;
@property(nonatomic, copy) NSString *imageLocalPath; // @synthesize imageLocalPath;
@property(nonatomic, retain) NSDictionary *plistDate; // @synthesize plistDate;
@property(nonatomic) _Bool isNeedShow; // @synthesize isNeedShow;
@property(nonatomic, copy) NSString *uploadFilePath; // @synthesize uploadFilePath;

@end

