//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$S10RealmSwift6ObjectCN.h"

@class NSString, _TtC7BingDic14ThumbnailModel;

@interface _TtC7BingDic10ImageModel : _$S10RealmSwift6ObjectCN
{
    // Error parsing type: , name: contentUrl
    // Error parsing type: , name: height
    // Error parsing type: , name: width
    // Error parsing type: , name: msrUrl
    // Error parsing type: , name: thumbnail
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithValue:(id)arg1 schema:(id)arg2;
- (id)initWithRealm:(id)arg1 schema:(id)arg2;
- (id)initWithValue:(id)arg1;
- (id)init;
@property(nonatomic, retain) _TtC7BingDic14ThumbnailModel *thumbnail; // @synthesize thumbnail;
@property(nonatomic, copy) NSString *msrUrl; // @synthesize msrUrl;
@property(nonatomic) double width; // @synthesize width;
@property(nonatomic) double height; // @synthesize height;
@property(nonatomic, copy) NSString *contentUrl; // @synthesize contentUrl;

@end

