//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSString;

@interface _TtC7BingDic14ResultMenuView : UIView
{
    // Error parsing type: , name: ResultMenuDetailCellIdentifier
    // Error parsing type: , name: maxCellWidth
    // Error parsing type: , name: result
    // Error parsing type: , name: x
    // Error parsing type: , name: y
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)calculateCellWidthWithText:(id)arg1 attributes:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 result:(id)arg2;
- (id)initWithResult:(id)arg1;
@property(nonatomic, copy) NSArray *result; // @synthesize result;
@property(nonatomic) double maxCellWidth; // @synthesize maxCellWidth;
@property(nonatomic, readonly) NSString *ResultMenuDetailCellIdentifier; // @synthesize ResultMenuDetailCellIdentifier;

@end

