//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString;

@interface _TtC7BingDic23OxfordSentenceViewModel : NSObject
{
    // Error parsing type: , name: isFirst
    // Error parsing type: , name: isLast
    // Error parsing type: , name: enText
    // Error parsing type: , name: chText
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithIsFirst:(_Bool)arg1 isLast:(_Bool)arg2 enText:(id)arg3 chText:(id)arg4;
@property(nonatomic, retain) NSAttributedString *chText; // @synthesize chText;
@property(nonatomic, retain) NSAttributedString *enText; // @synthesize enText;
@property(nonatomic) _Bool isLast; // @synthesize isLast;
@property(nonatomic) _Bool isFirst; // @synthesize isFirst;

@end

