//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC7BingDic11GlobalConst : NSObject
{
}

+ (id)titleColor;
+ (id)kAILabortoryGuideCellLoaded;
+ (id)kAILabortoryGuideButtonLoaded;
+ (id)kRealtimeGuideSettingLoaded;
+ (id)kRealtimeGuidePageLoaded;
+ (id)kRealtimeGuideButtonLoaded;
+ (id)kBundleVersion;
+ (id)sliderGreen;
+ (id)wordRed;
+ (id)wordGreen;
+ (id)bgLightGreen;
+ (id)resultDetailBlue;
+ (id)webContentGrey;
+ (id)backgroundGrey;
+ (id)descriptBlue;
+ (id)oxfordWordGrey;
+ (id)oxfordTagBlack;
+ (id)borderDarkGrey;
+ (id)borderGrey;
+ (id)wordLightGrey;
+ (id)wordDarkGrey;
+ (id)wordContentGrey;
+ (id)wordBlack;
+ (id)lightGreen;
+ (id)green;
+ (id)lightWhite;
+ (id)lightBlue;
+ (id)greyLine;
+ (id)purple;
+ (id)borderL2;
+ (id)l3;
+ (id)l2;
+ (id)l1;
+ (double)screenHeight;
+ (double)screenWidth;
+ (double)autoItemSize;
+ (double)itemSize;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;

@end

