//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UILabel, _TtC7BingDic10IndexLabel;

@interface _TtC7BingDic17WebDefinitionCell : UITableViewCell
{
    // Error parsing type: , name: indexLbl
    // Error parsing type: , name: definitionLbl
    // Error parsing type: , name: sourceLbl
    // Error parsing type: , name: index
    // Error parsing type: , name: content
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic, copy) NSString *index; // @synthesize index;
@property(nonatomic) __weak UILabel *sourceLbl; // @synthesize sourceLbl;
@property(nonatomic) __weak UILabel *definitionLbl; // @synthesize definitionLbl;
@property(nonatomic) __weak _TtC7BingDic10IndexLabel *indexLbl; // @synthesize indexLbl;

@end

