//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "WKScriptMessageHandler-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class NSString, UIBarButtonItem, UIProgressView, WKWebView;
@protocol UIGestureRecognizerDelegate;

@interface _TtC7BingDic29BDCommonWebViewViewController : UIViewController <WKUIDelegate, WKScriptMessageHandler>
{
    // Error parsing type: , name: rootURLString
    // Error parsing type: , name: isListenBack
    // Error parsing type: , name: isClearCacheNeeded
    // Error parsing type: , name: delegate
    // Error parsing type: , name: webView.storage
    // Error parsing type: , name: progressView.storage
    // Error parsing type: , name: backBarButtonItem.storage
    // Error parsing type: , name: closeBarButtonItem.storage
    // Error parsing type: , name: onPageClosed
    // Error parsing type: , name: firstTitle
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didReceiveServerRedirectForProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)handlePopViewController;
- (void)closeBarButtonItemClickedWithItem:(id)arg1;
- (void)backBarButtonItemClickedWithItem:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)setupSubViews;
- (void)checkBarButtonItems;
- (_Bool)navigationShouldPopOnBackButton;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, copy) NSString *firstTitle; // @synthesize firstTitle;
@property(nonatomic) _Bool onPageClosed; // @synthesize onPageClosed;
@property(nonatomic, retain) UIBarButtonItem *closeBarButtonItem;
@property(nonatomic, retain) UIBarButtonItem *backBarButtonItem;
@property(nonatomic, retain) UIProgressView *progressView;
@property(nonatomic, retain) WKWebView *webView;
@property(nonatomic, retain) id <UIGestureRecognizerDelegate> delegate; // @synthesize delegate;
@property(nonatomic) _Bool isClearCacheNeeded; // @synthesize isClearCacheNeeded;
@property(nonatomic) _Bool isListenBack; // @synthesize isListenBack;
@property(nonatomic, copy) NSString *rootURLString; // @synthesize rootURLString;

@end

