//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, _TtC7BingDic20ReadResultScoreModel;

@interface _TtC7BingDic15ResultListModel : NSObject
{
    // Error parsing type: , name: isOpen
    // Error parsing type: , name: rank
    // Error parsing type: , name: conversationStr
    // Error parsing type: , name: originalPath
    // Error parsing type: , name: savePrefixStr
    // Error parsing type: , name: resultScoreModel
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, retain) _TtC7BingDic20ReadResultScoreModel *resultScoreModel; // @synthesize resultScoreModel;
@property(nonatomic, copy) NSString *savePrefixStr; // @synthesize savePrefixStr;
@property(nonatomic, copy) NSString *originalPath; // @synthesize originalPath;
@property(nonatomic, copy) NSString *conversationStr; // @synthesize conversationStr;

@end

