//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, UIButton, UITextView, _TtC7BingDic19VoiceTranslateModel;

@interface _TtC7BingDic38VoiceTranslateFullScreenViewController : UIViewController
{
    // Error parsing type: , name: contentTextView
    // Error parsing type: , name: soundButton
    // Error parsing type: , name: copyButton
    // Error parsing type: , name: fullScreenButton
    // Error parsing type: , name: shareButton
    // Error parsing type: , name: contentModel
    // Error parsing type: , name: supportVoiceCodes
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (double)calculateHeightWithText:(id)arg1 attributes:(id)arg2;
- (void)shareButtonClickedWithSender:(id)arg1;
- (void)fullScreenButtonClickedWithSender:(id)arg1;
- (void)copyButtonClickedWithSender:(id)arg1;
- (void)soundButtonClickedWithSender:(id)arg1;
- (void)setupSubViews;
- (void)dealloc;
@property(nonatomic, readonly) long long preferredInterfaceOrientationForPresentation;
@property(nonatomic, readonly) unsigned long long supportedInterfaceOrientations;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;
@property(nonatomic, readonly) _Bool shouldAutorotate;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
- (id)initWithModel:(id)arg1;
@property(nonatomic, copy) NSArray *supportVoiceCodes; // @synthesize supportVoiceCodes;
@property(nonatomic, retain) _TtC7BingDic19VoiceTranslateModel *contentModel; // @synthesize contentModel;
@property(nonatomic, retain) UIButton *shareButton; // @synthesize shareButton;
@property(nonatomic, retain) UIButton *fullScreenButton; // @synthesize fullScreenButton;
@property(nonatomic, retain) UIButton *copyButton; // @synthesize copyButton;
@property(nonatomic, retain) UIButton *soundButton; // @synthesize soundButton;
@property(nonatomic, retain) UITextView *contentTextView; // @synthesize contentTextView;

@end

