//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface _TtC7BingDic34BDMergeWordAndSentenceBooksManager : NSObject
{
    // Error parsing type: , name: currentMergePageName
    // Error parsing type: , name: mergeWordBookRequestCount
    // Error parsing type: , name: mergeDailySentenceBookRequestCount
    // Error parsing type: , name: mergeSampleSentenceBookRequestCount
    // Error parsing type: , name: mergeRequestFailedCount
    // Error parsing type: , name: isMerging
}

+ (id)kMergeSampleSentenceBookFailedKey;
+ (id)kMergeSampleSentenceBookSuccessedKey;
+ (id)kMergeDailySentenceBookFailedKey;
+ (id)kMergeDailySentenceBookSuccessedKey;
+ (id)kMergeWordBookFailedKey;
+ (id)kMergeWordBookSuccessedKey;
+ (id)kMergeWordAndSentenceBooksCompletedKey;
+ (id)kMergeWordAndSentenceBooksKey;
+ (id)share;
- (CDUnknownBlockType).cxx_destruct;
- (void)checkMergeRequest;
- (void)checkLocalSentenceBooksWithTempIDArray:(id)arg1 isDailySentence:(_Bool)arg2;
- (void)checkLocalWordBooksWithTempIDArray:(id)arg1;
- (void)dataMergeResponseWithResponse:(id)arg1;
- (void)noteBookListRequestResponseWithResponse:(id)arg1;
- (void)mergeData;
- (id)init;
@property(nonatomic) _Bool isMerging; // @synthesize isMerging;
@property(nonatomic, copy) NSString *currentMergePageName; // @synthesize currentMergePageName;

@end

