//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class AVAudioPlayer, NSTimer, UIControl, UIImageView, UILabel;

@interface _TtC7BingDic17SODUserSampleCell : UITableViewCell
{
    // Error parsing type: , name: imgvUser
    // Error parsing type: , name: lblScore
    // Error parsing type: , name: ctlAudio
    // Error parsing type: , name: ctlAudioSample
    // Error parsing type: , name: imgvAudio
    // Error parsing type: , name: imgvAudioSample
    // Error parsing type: , name: audioPlayer
    // Error parsing type: , name: sampleAudioPlayer
    // Error parsing type: , name: preparedHandler
    // Error parsing type: , name: audioControlClickedHandler
    // Error parsing type: , name: isLoadUserAudioNeeded
    // Error parsing type: , name: isLoadWebAudioNeeded
    // Error parsing type: , name: dialogueModel
    // Error parsing type: , name: timerUser
    // Error parsing type: , name: timerSample
    // Error parsing type: , name: turnUser
    // Error parsing type: , name: turnSample
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)stopAnimationWithIsUserAudio:(_Bool)arg1;
- (void)startAnimationWithIsUserAudio:(_Bool)arg1;
- (void)updateMaskLayerWithSender:(id)arg1;
- (void)initAVAudioPlayerWithPlayerPath:(id)arg1 isWebAudio:(_Bool)arg2;
- (void)sampleAudioControlClicked:(id)arg1;
- (void)audioControlClicked:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic) double turnSample; // @synthesize turnSample;
@property(nonatomic) double turnUser; // @synthesize turnUser;
@property(nonatomic, retain) NSTimer *timerSample; // @synthesize timerSample;
@property(nonatomic, retain) NSTimer *timerUser; // @synthesize timerUser;
@property(nonatomic) _Bool isLoadWebAudioNeeded; // @synthesize isLoadWebAudioNeeded;
@property(nonatomic) _Bool isLoadUserAudioNeeded; // @synthesize isLoadUserAudioNeeded;
@property(nonatomic, copy) CDUnknownBlockType audioControlClickedHandler; // @synthesize audioControlClickedHandler;
@property(nonatomic, copy) CDUnknownBlockType preparedHandler; // @synthesize preparedHandler;
@property(nonatomic, retain) AVAudioPlayer *sampleAudioPlayer; // @synthesize sampleAudioPlayer;
@property(nonatomic, retain) AVAudioPlayer *audioPlayer; // @synthesize audioPlayer;
@property(nonatomic) __weak UIImageView *imgvAudioSample; // @synthesize imgvAudioSample;
@property(nonatomic) __weak UIImageView *imgvAudio; // @synthesize imgvAudio;
@property(nonatomic) __weak UIControl *ctlAudioSample; // @synthesize ctlAudioSample;
@property(nonatomic) __weak UIControl *ctlAudio; // @synthesize ctlAudio;
@property(nonatomic) __weak UILabel *lblScore; // @synthesize lblScore;
@property(nonatomic) __weak UIImageView *imgvUser; // @synthesize imgvUser;

@end

