//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, NSURLResponse;

@interface _TtC7BingDic15HttpRequestBase : NSObject
{
    // Error parsing type: , name: cachePolicy
    // Error parsing type: , name: httpMethod
    // Error parsing type: , name: contentType
    // Error parsing type: , name: customHeader
    // Error parsing type: , name: requestJudgement
    // Error parsing type: , name: judgeHandler
    // Error parsing type: , name: cacheJudgeHandler
    // Error parsing type: , name: response
    // Error parsing type: , name: respResult
    // Error parsing type: , name: respMessage
    // Error parsing type: , name: url
    // Error parsing type: , name: isAlreadyTrimed
    // Error parsing type: , name: timeoutInterval
    // Error parsing type: , name: clearRequest
    // Error parsing type: , name: isFinished
    // Error parsing type: , name: startTime
    // Error parsing type: , name: endTime
    // Error parsing type: , name: constTime
    // Error parsing type: , name: urlResponse
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)responseWithResponseData:(id)arg1;
- (void)createNewRequestWithRequest:(id)arg1;
@property(nonatomic, retain) NSURLResponse *urlResponse; // @synthesize urlResponse;
- (void)beginRequestWithRequestData:(id)arg1;
- (id)initWithResponse:(CDUnknownBlockType)arg1;
@property(nonatomic) double constTime; // @synthesize constTime;
@property(nonatomic) double endTime; // @synthesize endTime;
@property(nonatomic) double startTime; // @synthesize startTime;
@property(nonatomic) _Bool isFinished; // @synthesize isFinished;
@property(nonatomic) _Bool clearRequest; // @synthesize clearRequest;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval;
@property(nonatomic) _Bool isAlreadyTrimed; // @synthesize isAlreadyTrimed;
@property(nonatomic, copy) NSString *url; // @synthesize url;
@property(nonatomic, copy) NSString *respMessage; // @synthesize respMessage;
@property(nonatomic, copy) CDUnknownBlockType response; // @synthesize response;
@property(nonatomic, copy) CDUnknownBlockType cacheJudgeHandler; // @synthesize cacheJudgeHandler;
@property(nonatomic, copy) CDUnknownBlockType judgeHandler; // @synthesize judgeHandler;
@property(nonatomic, copy) NSDictionary *customHeader; // @synthesize customHeader;

@end

