//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC7BingDic23DictionarySearchManager : NSObject
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: result
    // Error parsing type: , name: needBingSearchResult
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)getPronunciationSignatureMd5StringWithPronunciationSignature:(id)arg1;
- (void)showResultToViewWithRequest:(id)arg1;
- (void)onlineResponseWithRequest:(id)arg1;
- (void)doSearchOnlineWithQuery:(id)arg1;
- (void)doSearchForWordCardWithQuery:(id)arg1;
- (void)doSearchOnlineAndIgnoreCacheWithQuery:(id)arg1;
- (void)doSearchWithQuery:(id)arg1 saveHistory:(_Bool)arg2;
@property(nonatomic) _Bool needBingSearchResult; // @synthesize needBingSearchResult;

@end

