//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7BingDic20QuickDefinitionModel : SwiftObject
{
    // Error parsing type: , name: headWord
    // Error parsing type: , name: usPronunciation
    // Error parsing type: , name: ukPronunciation
    // Error parsing type: , name: pinyin
    // Error parsing type: , name: pronunciationSignature
    // Error parsing type: , name: isNoResult
    // Error parsing type: , name: quickDefinitions
}

@end

