//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIButton, UILabel, UIView, _TtC7BingDic16NonPlanAlertView, _TtC7BingDic19ReciteWordsCategory, _TtC7BingDic19RecitedProgressView;

@interface _TtC7BingDic29ReciteWordsRootViewController : UIViewController
{
    // Error parsing type: , name: lblTitle
    // Error parsing type: , name: progressView
    // Error parsing type: , name: lblCategoryInfo
    // Error parsing type: , name: studyButton
    // Error parsing type: , name: reviewButton
    // Error parsing type: , name: maskView
    // Error parsing type: , name: alertView
    // Error parsing type: , name: kShowCategoryListSegueId
    // Error parsing type: , name: kShowSettingSegueId
    // Error parsing type: , name: kShowStudySegueId
    // Error parsing type: , name: kShowReviewSegueId
    // Error parsing type: , name: currentCategory
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)selectCategorySegue:(id)arg1;
- (void)AddCategorySegue:(id)arg1;
- (void)btnReviewClick:(id)arg1;
- (void)btnStudyClick:(id)arg1;
- (void)btnChangeCategoryClick:(id)arg1;
- (void)btnSettingClick:(id)arg1;
- (void)btnBackClick:(id)arg1;
- (void)btnBackClick;
- (void)btnCreatClick;
- (void)hideAlert;
- (void)showEmptyAlert;
- (void)initView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic, retain) _TtC7BingDic19ReciteWordsCategory *currentCategory; // @synthesize currentCategory;
@property(nonatomic, readonly) NSString *kShowReviewSegueId; // @synthesize kShowReviewSegueId;
@property(nonatomic, readonly) NSString *kShowStudySegueId; // @synthesize kShowStudySegueId;
@property(nonatomic, readonly) NSString *kShowSettingSegueId; // @synthesize kShowSettingSegueId;
@property(nonatomic, readonly) NSString *kShowCategoryListSegueId; // @synthesize kShowCategoryListSegueId;
@property(nonatomic, retain) _TtC7BingDic16NonPlanAlertView *alertView; // @synthesize alertView;
@property(nonatomic, retain) UIView *maskView; // @synthesize maskView;
@property(nonatomic) __weak UIButton *reviewButton; // @synthesize reviewButton;
@property(nonatomic) __weak UIButton *studyButton; // @synthesize studyButton;
@property(nonatomic) __weak UILabel *lblCategoryInfo; // @synthesize lblCategoryInfo;
@property(nonatomic) __weak _TtC7BingDic19RecitedProgressView *progressView; // @synthesize progressView;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle;

@end

