//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, _TtC7BingDic15CollectSentence, _TtC7BingDic9DailyWord;

@interface _TtC7BingDic9DailyItem : NSObject
{
    // Error parsing type: , name: dateToShow
    // Error parsing type: , name: dailySentence
    // Error parsing type: , name: dailyWord
    // Error parsing type: , name: news
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, copy) NSArray *news; // @synthesize news;
@property(nonatomic, retain) _TtC7BingDic9DailyWord *dailyWord; // @synthesize dailyWord;
@property(nonatomic, retain) _TtC7BingDic15CollectSentence *dailySentence; // @synthesize dailySentence;
@property(nonatomic, copy) NSString *dateToShow; // @synthesize dateToShow;

@end

