//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface _TtC7BingDic15WordDetailModel : NSObject
{
    // Error parsing type: , name: word
    // Error parsing type: , name: PronunciationScore
    // Error parsing type: , name: PhonemeDetails
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
@property(nonatomic, copy) NSArray *PhonemeDetails; // @synthesize PhonemeDetails;
@property(nonatomic, copy) NSString *word; // @synthesize word;

@end

