//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic15HttpRequestBase.h"

@class NSDictionary, NSString;

@interface _TtC7BingDic16DataMergeRequest : _TtC7BingDic15HttpRequestBase
{
    // Error parsing type: , name: resultDic
    // Error parsing type: , name: sentenceType
    // Error parsing type: , name: bookId
}

+ (id)kDailySentenceType;
+ (id)kSampleSentenceType;
+ (id)kMergeHistory;
+ (id)kmergeDict;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithResponse:(CDUnknownBlockType)arg1;
- (void)responseWithResponseData:(id)arg1;
- (void)beginMergeRequestWithData:(id)arg1 method:(id)arg2 tableId:(id)arg3 sentenceType:(id)arg4;
@property(nonatomic, copy) NSString *bookId; // @synthesize bookId;
@property(nonatomic, copy) NSString *sentenceType; // @synthesize sentenceType;
@property(nonatomic, retain) NSDictionary *resultDic; // @synthesize resultDic;

@end

