//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIButton, UILabel, _TtC7BingDic12ProgressView, _TtC7BingDic19ReciteWordsCategory;

@interface _TtC7BingDic22ReciteWordCategoryCell : UICollectionViewCell
{
    // Error parsing type: , name: lblTitle
    // Error parsing type: , name: progressView
    // Error parsing type: , name: lblProgress
    // Error parsing type: , name: btnSelect
    // Error parsing type: , name: btnDelete
    // Error parsing type: , name: selectCategoryAction
    // Error parsing type: , name: deleteCategoryAction
    // Error parsing type: , name: category
    // Error parsing type: , name: isSelectMode
    // Error parsing type: , name: isEditMode
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)btnDeleteClick:(id)arg1;
- (void)btnSelectClick:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic) _Bool isEditMode; // @synthesize isEditMode;
@property(nonatomic) _Bool isSelectMode; // @synthesize isSelectMode;
@property(nonatomic, retain) _TtC7BingDic19ReciteWordsCategory *category; // @synthesize category;
@property(nonatomic, copy) CDUnknownBlockType deleteCategoryAction; // @synthesize deleteCategoryAction;
@property(nonatomic, copy) CDUnknownBlockType selectCategoryAction; // @synthesize selectCategoryAction;
@property(nonatomic) __weak UIButton *btnDelete; // @synthesize btnDelete;
@property(nonatomic) __weak UIButton *btnSelect; // @synthesize btnSelect;
@property(nonatomic) __weak UILabel *lblProgress; // @synthesize lblProgress;
@property(nonatomic) __weak _TtC7BingDic12ProgressView *progressView; // @synthesize progressView;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle;

@end

