//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class AVAudioPlayer, NSString, NSTimer, UIControl, UIImageView, UILabel;

@interface _TtC7BingDic11SODUserCell : UITableViewCell
{
    // Error parsing type: , name: imgvUser
    // Error parsing type: , name: lblScore
    // Error parsing type: , name: ctlAudio
    // Error parsing type: , name: imgvAudio
    // Error parsing type: , name: audioPlayer
    // Error parsing type: , name: preparedHandler
    // Error parsing type: , name: audioControlClickedHandler
    // Error parsing type: , name: isLoadAudioNeeded
    // Error parsing type: , name: audioUrl
    // Error parsing type: , name: dialogueModel
    // Error parsing type: , name: cachedData
    // Error parsing type: , name: timer
    // Error parsing type: , name: turn
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)stopAnimation;
- (void)startAnimation;
- (void)updateMaskLayer;
- (void)handleVisibilityWithIsVisible:(_Bool)arg1;
- (void)initAVAudioPlayerWithData:(id)arg1 playerPath:(id)arg2;
- (void)audioControlClicked:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic) double turn; // @synthesize turn;
@property(nonatomic, retain) NSTimer *timer; // @synthesize timer;
@property(nonatomic, copy) NSString *audioUrl; // @synthesize audioUrl;
@property(nonatomic) _Bool isLoadAudioNeeded; // @synthesize isLoadAudioNeeded;
@property(nonatomic, copy) CDUnknownBlockType audioControlClickedHandler; // @synthesize audioControlClickedHandler;
@property(nonatomic, copy) CDUnknownBlockType preparedHandler; // @synthesize preparedHandler;
@property(nonatomic, retain) AVAudioPlayer *audioPlayer; // @synthesize audioPlayer;
@property(nonatomic) __weak UIImageView *imgvAudio; // @synthesize imgvAudio;
@property(nonatomic) __weak UIControl *ctlAudio; // @synthesize ctlAudio;
@property(nonatomic) __weak UILabel *lblScore; // @synthesize lblScore;
@property(nonatomic) __weak UIImageView *imgvUser; // @synthesize imgvUser;

@end

