//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC7BingDic19GuideViewController : UIViewController
{
    // Error parsing type: , name: scrollView
    // Error parsing type: , name: numOfPages
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (double)getTimeDateWithYear:(long long)arg1 month:(long long)arg2 day:(long long)arg3;
- (void)initializeLocalData;
@property(nonatomic, readonly) _Bool prefersStatusBarHidden;
- (void)viewDidLoad;

@end

