//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC7BingDic16QuikLocationMenu : UIView
{
    // Error parsing type: , name: headerBtnHandler
    // Error parsing type: , name: orderBtnHandler
    // Error parsing type: , name: showGroup
    // Error parsing type: , name: orderGroup
    // Error parsing type: , name: x
    // Error parsing type: , name: y
    // Error parsing type: , name: result
    // Error parsing type: , name: isFirstLoad
    // Error parsing type: , name: selectType
    // Error parsing type: , name: selectIndex
    // Error parsing type: , name: titles
    // Error parsing type: , name: btns
    // Error parsing type: , name: lines
    // Error parsing type: , name: btnHeight
    // Error parsing type: , name: btnWidth
}

- (CDUnknownBlockType).cxx_destruct;
- (void)orderBtnClicked;
- (void)headerBtnClickedWithSender:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) long long selectIndex; // @synthesize selectIndex;
@property(nonatomic) _Bool isFirstLoad; // @synthesize isFirstLoad;
@property(nonatomic, copy) CDUnknownBlockType orderBtnHandler; // @synthesize orderBtnHandler;

@end

