//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface _TtC7BingDic16MSRImagesManager : NSObject
{
    // Error parsing type: , name: baseUrl
    // Error parsing type: , name: word
    // Error parsing type: , name: MSRUrlGroups
    // Error parsing type: , name: MSRImagesDictionary
}

+ (id)shared;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)loadMSRImageModelIfNeeded;
- (void)varifyMSRUrlExistFor:(id)arg1 with:(CDUnknownBlockType)arg2;
@property(nonatomic, copy) NSDictionary *MSRImagesDictionary; // @synthesize MSRImagesDictionary;
@property(nonatomic, readonly) _Bool MSRUrlExist;
@property(nonatomic, copy) NSString *word; // @synthesize word;

@end

