//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic25ArticleListViewController.h"

@class NSString;

@interface _TtC7BingDic32OfflineArticleListViewController : _TtC7BingDic25ArticleListViewController
{
    // Error parsing type: , name: kFuncCellId
    // Error parsing type: , name: isDownload
    // Error parsing type: , name: channel
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)deleteArticleActionWithArticle:(id)arg1;
- (void)playInLoop;
- (void)clearHistory;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic) _Bool isDownload; // @synthesize isDownload;
@property(nonatomic, readonly) NSString *kFuncCellId; // @synthesize kFuncCellId;

@end

