//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic27PronounceReadBaseController.h"

@class NSArray, NSLayoutConstraint, UIButton, UICollectionView, UIImageView, UIView;

@interface _TtC7BingDic31ReadCategorySelectionController : _TtC7BingDic27PronounceReadBaseController
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: leftGreenView
    // Error parsing type: , name: leftGreenHeight
    // Error parsing type: , name: descriptionView
    // Error parsing type: , name: leftButton
    // Error parsing type: , name: rightButton
    // Error parsing type: , name: viewItemSize
    // Error parsing type: , name: imageArray
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)rightButtonClick:(id)arg1;
- (void)leftButtonClick:(id)arg1;
- (void)useAgreementClick:(id)arg1;
- (void)privacyPolicyClick:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, readonly) NSArray *imageArray; // @synthesize imageArray;
@property(nonatomic) __weak UIButton *rightButton; // @synthesize rightButton;
@property(nonatomic) __weak UIButton *leftButton; // @synthesize leftButton;
@property(nonatomic) __weak UIView *descriptionView; // @synthesize descriptionView;
@property(nonatomic) __weak NSLayoutConstraint *leftGreenHeight; // @synthesize leftGreenHeight;
@property(nonatomic) __weak UIImageView *leftGreenView; // @synthesize leftGreenView;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

