//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIButton, UILabel, UITableView, UIView, _TtC7BingDic13DailyWordCell, _TtC7BingDic17DailyNewsListCell, _TtC7BingDic18FeedListDataSource, _TtC7BingDic22DailyContentDataSource, _TtC7BingDic24InfiniteImagePageControl;

@interface _TtC7BingDic23FeedsRootViewController : UIViewController
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: colorView
    // Error parsing type: , name: searchField
    // Error parsing type: , name: searchBoxPlaceHolderLbl
    // Error parsing type: , name: pasteBoardContainer
    // Error parsing type: , name: pasteBoardWordDescLbl
    // Error parsing type: , name: pastBoardWordLbl
    // Error parsing type: , name: cameraBtn
    // Error parsing type: , name: carouselControl
    // Error parsing type: , name: corverView
    // Error parsing type: , name: headerHeight
    // Error parsing type: , name: dailyContentDataSource
    // Error parsing type: , name: feedsListDataSource
    // Error parsing type: , name: dailyWordCell
    // Error parsing type: , name: dailyNewsListCell
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)ShowWordEmbeddingWithHeadWord:(id)arg1;
- (void)wordEmbedActionWithWord:(id)arg1 embedWord:(id)arg2;
- (void)wordSelectActionWithWord:(id)arg1;
- (void)wordStarActionWithSender:(id)arg1 word:(id)arg2;
- (void)wordUkPronActionWithWord:(id)arg1;
- (void)wordUsPronActionWithWord:(id)arg1;
- (void)wordCollectActionWithWord:(id)arg1;
- (void)didSelectNewsWithNews:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
@property(nonatomic, retain) _TtC7BingDic17DailyNewsListCell *dailyNewsListCell; // @synthesize dailyNewsListCell;
@property(nonatomic, retain) _TtC7BingDic13DailyWordCell *dailyWordCell; // @synthesize dailyWordCell;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)finishLoadDataSourceWithDataSource:(id)arg1 isSuccess:(_Bool)arg2;
- (void)finishLoadDailyDataSourceWithDataSource:(id)arg1 isSuccess:(_Bool)arg2;
- (void)loadNewData;
- (void)showActivityWithNotification:(id)arg1;
- (void)tapImage;
- (void)searchFieldClickWithTrigerPasteBoardString:(_Bool)arg1;
- (void)btnCameraClick:(id)arg1;
- (void)pasteBoardContainerClick;
- (void)refreshFooterEvent;
- (void)reminderAlertViewWithTitle:(id)arg1;
- (void)activityReminder;
- (void)pushToSearchViewWithTrigerPasteBoardString:(_Bool)arg1;
- (void)checkUpdate;
- (void)showPasteBoardContainerIfNeeded;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)tapRootView;
- (void)viewDidLoad;
- (void)awakeFromNib;
@property(nonatomic, retain) _TtC7BingDic18FeedListDataSource *feedsListDataSource; // @synthesize feedsListDataSource;
@property(nonatomic, retain) _TtC7BingDic22DailyContentDataSource *dailyContentDataSource; // @synthesize dailyContentDataSource;
@property(nonatomic, readonly) double headerHeight; // @synthesize headerHeight;
@property(nonatomic, retain) UIView *corverView; // @synthesize corverView;
@property(nonatomic) __weak _TtC7BingDic24InfiniteImagePageControl *carouselControl; // @synthesize carouselControl;
@property(nonatomic) __weak UIButton *cameraBtn; // @synthesize cameraBtn;
@property(nonatomic) __weak UILabel *pastBoardWordLbl; // @synthesize pastBoardWordLbl;
@property(nonatomic) __weak UILabel *pasteBoardWordDescLbl; // @synthesize pasteBoardWordDescLbl;
@property(nonatomic) __weak UIView *pasteBoardContainer; // @synthesize pasteBoardContainer;
@property(nonatomic) __weak UILabel *searchBoxPlaceHolderLbl; // @synthesize searchBoxPlaceHolderLbl;
@property(nonatomic) __weak UIView *searchField; // @synthesize searchField;
@property(nonatomic) __weak UIView *colorView; // @synthesize colorView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;

@end

