//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableAttributedString, NSString;

@interface _TtC7BingDic17FollowResultModel : NSObject
{
    // Error parsing type: , name: missWord
    // Error parsing type: , name: score
    // Error parsing type: , name: pronunciationStr
    // Error parsing type: , name: pronunciation
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (id)initWithMissWord:(id)arg1 pronunciation:(id)arg2 score:(long long)arg3;
@property(nonatomic, retain) NSMutableAttributedString *pronunciation; // @synthesize pronunciation;
@property(nonatomic, copy) NSString *pronunciationStr; // @synthesize pronunciationStr;
@property(nonatomic, copy) NSString *missWord; // @synthesize missWord;

@end

