//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, UICollectionView, UILabel;

@interface _TtC7BingDic17DailyNewsListCell : UITableViewCell
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: topTitleLabel
    // Error parsing type: , name: dataSource
    // Error parsing type: , name: selectNewsAction
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic, copy) CDUnknownBlockType selectNewsAction; // @synthesize selectNewsAction;
@property(nonatomic, copy) NSArray *dataSource; // @synthesize dataSource;
@property(nonatomic) __weak UILabel *topTitleLabel; // @synthesize topTitleLabel;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

