//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSLayoutConstraint, NSURL, UIImageView;

@interface _TtC7BingDic13AdvertiseCell : UITableViewCell
{
    // Error parsing type: , name: imgv
    // Error parsing type: , name: consImgvHeight
    // Error parsing type: , name: imageUrl
    // Error parsing type: , name: ratio
    // Error parsing type: , name: defautRatio
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutImgvWithSize:(struct CGSize)arg1;
- (void)awakeFromNib;
@property(nonatomic, copy) NSURL *imageUrl; // @synthesize imageUrl;
@property(nonatomic) __weak NSLayoutConstraint *consImgvHeight; // @synthesize consImgvHeight;
@property(nonatomic) __weak UIImageView *imgv; // @synthesize imgv;

@end

