//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC7BingDic21OfflinePackageManager : NSObject
{
}

+ (id)getDownloadItems;
+ (void)downloadSuccessWithItem:(id)arg1;
+ (_Bool)hasDownloadWithItem:(id)arg1;
+ (id)getPackageBy:(long long)arg1;
+ (id)getDefaultAuthPackage;
+ (id)getDefaultQuickDefPackage;
+ (long long)kQuickPackageId;
+ (long long)kAuthPackageId;
- (id)init;

@end

