//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIColor, UIImage;

@interface _TtC7BingDic19TitleItemSelectView : UIView
{
    // Error parsing type: , name: offset
    // Error parsing type: , name: items
    // Error parsing type: , name: bottomLine
    // Error parsing type: , name: underLine
    // Error parsing type: , name: action
    // Error parsing type: , name: backImage
    // Error parsing type: , name: titles
    // Error parsing type: , name: titleNormalColor
    // Error parsing type: , name: titleSelectColor
    // Error parsing type: , name: titleItemStyle
    // Error parsing type: , name: buttonWidth
    // Error parsing type: , name: buttonHeight
    // Error parsing type: , name: contentWidth
    // Error parsing type: , name: currentSelctIndex
    // Error parsing type: , name: _scrollView
}

- (CDUnknownBlockType).cxx_destruct;
- (void)correctContentOffset;
- (void)selectItemWithIndex:(long long)arg1;
- (void)btnItemClickWithSender:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) long long currentSelctIndex; // @synthesize currentSelctIndex;
@property(nonatomic) double buttonHeight; // @synthesize buttonHeight;
@property(nonatomic) double buttonWidth; // @synthesize buttonWidth;
@property(nonatomic, retain) UIColor *titleSelectColor; // @synthesize titleSelectColor;
@property(nonatomic, retain) UIColor *titleNormalColor; // @synthesize titleNormalColor;
@property(nonatomic, copy) NSArray *titles; // @synthesize titles;
@property(nonatomic, retain) UIImage *backImage; // @synthesize backImage;
@property(nonatomic, copy) CDUnknownBlockType action; // @synthesize action;
@property(nonatomic) double offset; // @synthesize offset;

@end

