//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel, _TtC7BingDic8NewsItem;

@interface _TtC7BingDic17DailyNewsItemCell : UICollectionViewCell
{
    // Error parsing type: , name: imgPreview
    // Error parsing type: , name: lblTitle
    // Error parsing type: , name: lblDesc
    // Error parsing type: , name: lblTime
    // Error parsing type: , name: news
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
- (id)getLinePlacingWithOrString:(id)arg1 placing:(double)arg2;
@property(nonatomic, retain) _TtC7BingDic8NewsItem *news; // @synthesize news;
@property(nonatomic) __weak UILabel *lblTime; // @synthesize lblTime;
@property(nonatomic) __weak UILabel *lblDesc; // @synthesize lblDesc;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle;
@property(nonatomic) __weak UIImageView *imgPreview; // @synthesize imgPreview;

@end

