//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic15HttpRequestBase.h"

@class _TtC7BingDic4User;

@interface _TtC7BingDic12LoginRequest : _TtC7BingDic15HttpRequestBase
{
    // Error parsing type: , name: user
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithResponse:(CDUnknownBlockType)arg1;
- (void)responseWithResponseData:(id)arg1;
- (void)beginLoginRequestByPhoneWithPhoneNum:(id)arg1 andVerificationCode:(id)arg2;
- (void)beginLoginRequestByUserWithUser:(id)arg1;
@property(nonatomic, retain) _TtC7BingDic4User *user; // @synthesize user;

@end

