//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic15HttpRequestBase.h"

@class NSString;

@interface _TtC7BingDic19MoreSentenceRequest : _TtC7BingDic15HttpRequestBase
{
    // Error parsing type: , name: URL
    // Error parsing type: , name: result
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithResponse:(CDUnknownBlockType)arg1;
- (void)responseWithResponseData:(id)arg1;
- (void)beginMoreSentenceRequestWithWord:(id)arg1 filter:(id)arg2 offset:(long long)arg3 count:(long long)arg4;
@property(nonatomic, readonly) NSString *URL; // @synthesize URL;

@end

