//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSString, UIButton, UITableView, _TtC7BingDic14SentenceFilter;

@interface _TtC7BingDic10FilterView : UIView
{
    // Error parsing type: , name: tableView
    // Error parsing type: , name: btnReset
    // Error parsing type: , name: btnSure
    // Error parsing type: , name: filterViewCellID
    // Error parsing type: , name: readyHandler
    // Error parsing type: , name: meanings
    // Error parsing type: , name: filter
    // Error parsing type: , name: isFirstLoadHeight
    // Error parsing type: , name: heightDict
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)btnSureClicked:(id)arg1;
- (void)btnResetClicked:(id)arg1;
- (void)reset;
- (void)awakeFromNib;
@property(nonatomic) _Bool isFirstLoadHeight; // @synthesize isFirstLoadHeight;
@property(nonatomic, retain) _TtC7BingDic14SentenceFilter *filter; // @synthesize filter;
@property(nonatomic, copy) NSArray *meanings; // @synthesize meanings;
@property(nonatomic, copy) CDUnknownBlockType readyHandler; // @synthesize readyHandler;
@property(nonatomic, readonly) NSString *filterViewCellID; // @synthesize filterViewCellID;
@property(nonatomic) __weak UIButton *btnSure; // @synthesize btnSure;
@property(nonatomic) __weak UIButton *btnReset; // @synthesize btnReset;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView;

@end

