//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, NSString, UICollectionView;

@interface _TtC7BingDic9ImageCell : UITableViewCell
{
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: ImageItemCellId
    // Error parsing type: , name: mycontext
    // Error parsing type: , name: trueImages
    // Error parsing type: , name: word
    // Error parsing type: , name: images
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)loadTrueImagesIfNeed;
- (void)dealloc;
- (void)awakeFromNib;
@property(nonatomic, copy) NSArray *images; // @synthesize images;
@property(nonatomic, copy) NSString *word; // @synthesize word;
@property(nonatomic, copy) NSArray *trueImages; // @synthesize trueImages;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;

@end

