//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIActivityIndicatorView, UIWebView;

@interface _TtC7BingDic17WebViewController : UIViewController
{
    // Error parsing type: , name: webview
    // Error parsing type: , name: strUrl
    // Error parsing type: , name: activityView
}

+ (id)getVCFromNibWithTitle:(id)arg1 url:(id)arg2;
+ (id)nibName;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
@property(nonatomic) __weak UIActivityIndicatorView *activityView; // @synthesize activityView;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
@property(nonatomic, copy) NSString *strUrl; // @synthesize strUrl;
@property(nonatomic) __weak UIWebView *webview; // @synthesize webview;

@end

