//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSLayoutConstraint, UILabel, UIView, _TtC7BingDic7Article;

@interface _TtC7BingDic27OfflineArticleTableViewCell : UITableViewCell
{
    // Error parsing type: , name: lblTitle
    // Error parsing type: , name: lblDetail
    // Error parsing type: , name: selectView
    // Error parsing type: , name: detailLeadingConstraint
    // Error parsing type: , name: inDownloadList
    // Error parsing type: , name: article
    // Error parsing type: , name: downloadAction
    // Error parsing type: , name: deleteAction
}

+ (id)kCellId;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)initAccessoryView;
- (void)awakeFromNib;
- (void)downloadFinishNotificationWithNotification:(id)arg1;
- (void)btnDeleteClick;
- (void)btnDownloadClick;
@property(nonatomic, copy) CDUnknownBlockType deleteAction; // @synthesize deleteAction;
@property(nonatomic, copy) CDUnknownBlockType downloadAction; // @synthesize downloadAction;
@property(nonatomic, retain) _TtC7BingDic7Article *article; // @synthesize article;
@property(nonatomic) _Bool inDownloadList; // @synthesize inDownloadList;
@property(nonatomic) __weak NSLayoutConstraint *detailLeadingConstraint; // @synthesize detailLeadingConstraint;
@property(nonatomic) __weak UIView *selectView; // @synthesize selectView;
@property(nonatomic) __weak UILabel *lblDetail; // @synthesize lblDetail;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle;

@end

