//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class NSString, UIButton, UILabel, UITextView;

@interface _TtC7BingDic22TranslateInputTextView : UIView <UITextViewDelegate>
{
    // Error parsing type: , name: lblPlaceHolder
    // Error parsing type: , name: placeHolderView
    // Error parsing type: , name: lblPlaceHolderPrefix
    // Error parsing type: , name: lblPlaceHolderSuffix
    // Error parsing type: , name: btnPaste
    // Error parsing type: , name: txtView
    // Error parsing type: , name: buttonWidth
    // Error parsing type: , name: buttonHeight
    // Error parsing type: , name: buttonFontSize
    // Error parsing type: , name: accessoryViewBackColor
    // Error parsing type: , name: clearButtonColor
    // Error parsing type: , name: translateButtonColor
    // Error parsing type: , name: imgTranslate
    // Error parsing type: , name: translateAction
    // Error parsing type: , name: resetAction
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)btnTranslateClick;
- (void)btnHideKeyboardClick;
- (void)btnPasteClick:(id)arg1;
- (void)btnClearClick:(id)arg1;
- (void)checkPlaceHolder;
@property(nonatomic, copy) NSString *text;
- (_Bool)becomeFirstResponder;
- (void)awakeFromNib;
@property(nonatomic, copy) CDUnknownBlockType resetAction; // @synthesize resetAction;
@property(nonatomic, copy) CDUnknownBlockType translateAction; // @synthesize translateAction;
@property(nonatomic, readonly) NSString *imgTranslate; // @synthesize imgTranslate;
@property(nonatomic, readonly) NSString *translateButtonColor; // @synthesize translateButtonColor;
@property(nonatomic, readonly) NSString *clearButtonColor; // @synthesize clearButtonColor;
@property(nonatomic, readonly) NSString *accessoryViewBackColor; // @synthesize accessoryViewBackColor;
@property(nonatomic, readonly) double buttonFontSize; // @synthesize buttonFontSize;
@property(nonatomic, readonly) double buttonHeight; // @synthesize buttonHeight;
@property(nonatomic, readonly) double buttonWidth; // @synthesize buttonWidth;
@property(nonatomic) __weak UITextView *txtView; // @synthesize txtView;
@property(nonatomic) __weak UIButton *btnPaste; // @synthesize btnPaste;
@property(nonatomic) __weak UILabel *lblPlaceHolderSuffix; // @synthesize lblPlaceHolderSuffix;
@property(nonatomic) __weak UILabel *lblPlaceHolderPrefix; // @synthesize lblPlaceHolderPrefix;
@property(nonatomic) __weak UIView *placeHolderView; // @synthesize placeHolderView;
@property(nonatomic) __weak UILabel *lblPlaceHolder; // @synthesize lblPlaceHolder;

@end

