//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, NSString, UIButton, UICollectionView, UILabel;

@interface _TtC7BingDic14FilterViewCell : UITableViewCell
{
    // Error parsing type: , name: lblTitle
    // Error parsing type: , name: btnFold
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: filterItemCellID
    // Error parsing type: , name: titles
    // Error parsing type: , name: foldOpen
    // Error parsing type: , name: selectIndex
    // Error parsing type: , name: itemSelectHandler
    // Error parsing type: , name: foldBtnClickedHandler
    // Error parsing type: , name: meanings
    // Error parsing type: , name: type
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)resetSelectedState;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)btnFoldClicked:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
@property(nonatomic, copy) NSArray *meanings; // @synthesize meanings;
@property(nonatomic, copy) CDUnknownBlockType foldBtnClickedHandler; // @synthesize foldBtnClickedHandler;
@property(nonatomic) long long selectIndex; // @synthesize selectIndex;
@property(nonatomic) _Bool foldOpen; // @synthesize foldOpen;
@property(nonatomic, readonly) NSString *filterItemCellID; // @synthesize filterItemCellID;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UIButton *btnFold; // @synthesize btnFold;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle;

@end

