//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, _TtC7BingDic14CustomTextView, _TtC7BingDic23OxfordSentenceViewModel;

@interface _TtC7BingDic18OxfordSentenceCell : UITableViewCell
{
    // Error parsing type: , name: icon
    // Error parsing type: , name: enSentenceTV
    // Error parsing type: , name: chSentenceTV
    // Error parsing type: , name: content
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic, retain) _TtC7BingDic23OxfordSentenceViewModel *content; // @synthesize content;
@property(nonatomic) __weak _TtC7BingDic14CustomTextView *chSentenceTV; // @synthesize chSentenceTV;
@property(nonatomic) __weak _TtC7BingDic14CustomTextView *enSentenceTV; // @synthesize enSentenceTV;
@property(nonatomic) __weak UIImageView *icon; // @synthesize icon;

@end

