//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, NSLayoutConstraint, NSString, UIButton, UILabel, _TtC7BingDic30BDCanBecomeFirstResponderLabel;

@interface _TtC7BingDic19QuickDefinitionCell : UITableViewCell
{
    // Error parsing type: , name: feedbackUrlFormat
    // Error parsing type: , name: shareContentUrlFormat
    // Error parsing type: , name: shareContentFormat
    // Error parsing type: , name: headWordLbl
    // Error parsing type: , name: pronBtnUS
    // Error parsing type: , name: pronBtnUK
    // Error parsing type: , name: pinyingBtn
    // Error parsing type: , name: speechLbl
    // Error parsing type: , name: definitionLbl
    // Error parsing type: , name: toOxfordBtn
    // Error parsing type: , name: shareBtn
    // Error parsing type: , name: headWordLeftMarginConstraint
    // Error parsing type: , name: headWordRightMarginConstraint
    // Error parsing type: , name: addToWordlistBtn
    // Error parsing type: , name: showWebView
    // Error parsing type: , name: gotoOxford
    // Error parsing type: , name: showCollectionView
    // Error parsing type: , name: pronunciationSignature
    // Error parsing type: , name: pageString
    // Error parsing type: , name: currentLongPressed
    // Error parsing type: , name: content
    // Error parsing type: , name: showOxfordButton
    // Error parsing type: , name: arrLabels
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)pronUsBtnClick:(id)arg1;
- (void)pronUkBtnClick:(id)arg1;
- (void)addToWordlistBtnClick:(id)arg1;
- (void)toOxfordBtnClick:(id)arg1;
- (void)feedbackBtnClick:(id)arg1;
- (void)shareBtnClick:(id)arg1;
- (void)copyAllEvent;
- (void)copyCurrentEvent;
- (void)definitionLblLongPressed:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
@property(nonatomic, copy) NSArray *arrLabels; // @synthesize arrLabels;
@property(nonatomic) _Bool showOxfordButton; // @synthesize showOxfordButton;
@property(nonatomic) long long currentLongPressed; // @synthesize currentLongPressed;
@property(nonatomic, copy) NSString *pageString; // @synthesize pageString;
@property(nonatomic, copy) NSString *pronunciationSignature; // @synthesize pronunciationSignature;
@property(nonatomic, copy) CDUnknownBlockType showCollectionView; // @synthesize showCollectionView;
@property(nonatomic, copy) CDUnknownBlockType gotoOxford; // @synthesize gotoOxford;
@property(nonatomic, copy) CDUnknownBlockType showWebView; // @synthesize showWebView;
@property(nonatomic) __weak UIButton *addToWordlistBtn; // @synthesize addToWordlistBtn;
@property(nonatomic) __weak NSLayoutConstraint *headWordRightMarginConstraint; // @synthesize headWordRightMarginConstraint;
@property(nonatomic) __weak NSLayoutConstraint *headWordLeftMarginConstraint; // @synthesize headWordLeftMarginConstraint;
@property(nonatomic) __weak UIButton *shareBtn; // @synthesize shareBtn;
@property(nonatomic) __weak UIButton *toOxfordBtn; // @synthesize toOxfordBtn;
@property(nonatomic) __weak _TtC7BingDic30BDCanBecomeFirstResponderLabel *definitionLbl; // @synthesize definitionLbl;
@property(nonatomic) __weak UILabel *speechLbl; // @synthesize speechLbl;
@property(nonatomic) __weak UIButton *pinyingBtn; // @synthesize pinyingBtn;
@property(nonatomic) __weak UIButton *pronBtnUK; // @synthesize pronBtnUK;
@property(nonatomic) __weak UIButton *pronBtnUS; // @synthesize pronBtnUS;
@property(nonatomic) __weak UILabel *headWordLbl; // @synthesize headWordLbl;

@end

