//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface _TtC7BingDic18FeedListDataSource : NSObject
{
    // Error parsing type: , name: completeHandler
    // Error parsing type: , name: feedsList
    // Error parsing type: , name: loadType
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)infoResponseWithRequest:(id)arg1;
- (void)loadMoreData;
- (void)loadNewData;
- (id)initWithCompleteHandler:(CDUnknownBlockType)arg1;
@property(nonatomic, copy) NSArray *feedsList; // @synthesize feedsList;
@property(nonatomic, copy) CDUnknownBlockType completeHandler; // @synthesize completeHandler;

@end

