//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UMSocialShareMenuViewDelegate-Protocol.h"

@interface _TtC7BingDic16UMSharingManager : NSObject <UMSocialShareMenuViewDelegate>
{
    // Error parsing type: , name: completedAction
}

+ (id)ShareWebView;
+ (id)ShareChallengeResult;
+ (id)ShareFeeds;
+ (id)ShareTranslateResult;
+ (id)ShareSampleSentence;
+ (id)ShareDictionary;
+ (id)ShareWord;
+ (id)ShareDailySentence;
+ (id)share;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)UMSocialShareMenuViewDidDisappear;
- (void)doShareWebWithTitle:(id)arg1 content:(id)arg2 contentURL:(id)arg3 image:(id)arg4 controller:(id)arg5 completed:(CDUnknownBlockType)arg6 successed:(CDUnknownBlockType)arg7 failed:(CDUnknownBlockType)arg8;
- (void)setPostGetUrlWithLabel:(id)arg1 En_Sentence:(id)arg2 Ch_Sentence:(id)arg3 sig:(id)arg4 image:(id)arg5 type:(id)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (void)doShareWithContent:(id)arg1 image:(id)arg2 controller:(id)arg3 type:(id)arg4 completed:(CDUnknownBlockType)arg5 successed:(CDUnknownBlockType)arg6 failed:(CDUnknownBlockType)arg7;
@property(nonatomic, copy) CDUnknownBlockType completedAction; // @synthesize completedAction;

@end

