//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$S10RealmSwift6ObjectCN.h"

@class NSString;

@interface _TtC7BingDic12LanguageItem : _$S10RealmSwift6ObjectCN
{
    // Error parsing type: , name: code
    // Error parsing type: , name: name
    // Error parsing type: , name: isTarget
    // Error parsing type: , name: method
    // Error parsing type: , name: lastUseTime
    // Error parsing type: , name: mapCode
}

+ (void)languageWithItem:(id)arg1;
+ (id)unkName;
+ (id)zhName;
+ (id)zhCode;
+ (id)enName;
+ (id)enCode;
- (CDUnknownBlockType).cxx_destruct;
- (id)initWithValue:(id)arg1 schema:(id)arg2;
- (id)initWithRealm:(id)arg1 schema:(id)arg2;
- (id)initWithValue:(id)arg1;
- (id)init;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, copy) NSString *mapCode; // @synthesize mapCode;
@property(nonatomic) double lastUseTime; // @synthesize lastUseTime;
@property(nonatomic) long long method; // @synthesize method;
@property(nonatomic) _Bool isTarget; // @synthesize isTarget;
@property(nonatomic, copy) NSString *name; // @synthesize name;
@property(nonatomic, copy) NSString *code; // @synthesize code;

@end

