//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class UIButton, UILabel;

@interface _TtC7BingDic13SectionHeader : UITableViewHeaderFooterView
{
    // Error parsing type: , name: titleLbl
    // Error parsing type: , name: expandBtn
    // Error parsing type: , name: delegate
    // Error parsing type: , name: type
    // Error parsing type: , name: expanded
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)tapResponseWithRecognizer:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic) __weak UIButton *expandBtn; // @synthesize expandBtn;
@property(nonatomic) __weak UILabel *titleLbl; // @synthesize titleLbl;

@end

