//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;

@interface _TtC7BingDic16NonPlanAlertView : UIView
{
    // Error parsing type: , name: lblTitle
    // Error parsing type: , name: lblMessage
    // Error parsing type: , name: btnCreate
    // Error parsing type: , name: btnBack
    // Error parsing type: , name: createAction
    // Error parsing type: , name: backAction
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)btnBackClick:(id)arg1;
- (void)btnCreateClick:(id)arg1;
- (void)awakeFromNib;
@property(nonatomic, copy) CDUnknownBlockType backAction; // @synthesize backAction;
@property(nonatomic, copy) CDUnknownBlockType createAction; // @synthesize createAction;
@property(nonatomic) __weak UIButton *btnBack; // @synthesize btnBack;
@property(nonatomic) __weak UIButton *btnCreate; // @synthesize btnCreate;
@property(nonatomic) __weak UILabel *lblMessage; // @synthesize lblMessage;
@property(nonatomic) __weak UILabel *lblTitle; // @synthesize lblTitle;

@end

