//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC7BingDic20ResultPageCellLayout.h"

@interface _TtC7BingDic25QuickDefinitionCellLayout : _TtC7BingDic20ResultPageCellLayout
{
    // Error parsing type: , name: definitionMargin
    // Error parsing type: , name: pronBtnMargin
    // Error parsing type: , name: speechFrameList
    // Error parsing type: , name: definitionFrameList
    // Error parsing type: , name: quickDefinitionModel
}

@end

