//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7BingDic12FeedsContent : SwiftObject
{
    // Error parsing type: , name: channel
    // Error parsing type: , name: uuid
    // Error parsing type: , name: title
    // Error parsing type: , name: description
    // Error parsing type: , name: source
    // Error parsing type: , name: sourceIcon
    // Error parsing type: , name: sourceUrl
    // Error parsing type: , name: contentType
    // Error parsing type: , name: createTime
    // Error parsing type: , name: showTime
    // Error parsing type: , name: isRecommend
    // Error parsing type: , name: viewCount
    // Error parsing type: , name: showSourceUrl
    // Error parsing type: , name: feedsImage
    // Error parsing type: , name: isLight
}

@end

