//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC7BingDic23SampleSentenceViewModel : SwiftObject
{
    // Error parsing type: , name: hightlightRegex
    // Error parsing type: , name: hightlightWithIndexRegex
    // Error parsing type: , name: commonRegex
    // Error parsing type: , name: font
    // Error parsing type: , name: highlightColor
    // Error parsing type: , name: enNormalColor
    // Error parsing type: , name: chNormalColor
    // Error parsing type: , name: enAttributedString
    // Error parsing type: , name: chAttributedString
    // Error parsing type: , name: enGroupRangeDict
    // Error parsing type: , name: chGroupRangeDict
    // Error parsing type: , name: highlightWords
    // Error parsing type: , name: signature
    // Error parsing type: , name: isMoreBtn
    // Error parsing type: , name: headWord
}

@end

