//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURLCache;

@interface _TtC7BingDic12URLCacheBase : NSObject
{
    // Error parsing type: , name: kMSACacheDate
    // Error parsing type: , name: kMSAMaxTimeInterval
    // Error parsing type: , name: cache
}

+ (void)setSharedInstance:(id)arg1;
+ (id)sharedInstance;
- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)clearCache;
- (void)clearCacheFor:(id)arg1;
- (void)storeInMemoryResponseWithResponse:(id)arg1 data:(id)arg2 forRequest:(id)arg3;
- (void)storeResponseWithResponse:(id)arg1 data:(id)arg2 forRequest:(id)arg3;
- (id)cachedDataForRequestWithRequest:(id)arg1;
@property(nonatomic, retain) NSURLCache *cache; // @synthesize cache;

@end

