//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, UILabel, _TtC7BingDic14CustomTextView;

@interface _TtC7BingDic14DefinitionCell : UITableViewCell
{
    // Error parsing type: , name: speechLbl
    // Error parsing type: , name: indexLbl
    // Error parsing type: , name: definitionTextView
    // Error parsing type: , name: arrLabels
    // Error parsing type: , name: definitionTextViews
    // Error parsing type: , name: content
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic, copy) NSArray *definitionTextViews; // @synthesize definitionTextViews;
@property(nonatomic, copy) NSArray *arrLabels; // @synthesize arrLabels;
@property(nonatomic) __weak _TtC7BingDic14CustomTextView *definitionTextView; // @synthesize definitionTextView;
@property(nonatomic) __weak UILabel *indexLbl; // @synthesize indexLbl;
@property(nonatomic) __weak UILabel *speechLbl; // @synthesize speechLbl;

@end

