//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel;

@interface _TtC7BingDic22WordStockTableViewCell : UITableViewCell
{
    // Error parsing type: , name: lblWord
    // Error parsing type: , name: lblPron
    // Error parsing type: , name: lblDef
    // Error parsing type: , name: showDefinition
    // Error parsing type: , name: word
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) _Bool showDefinition; // @synthesize showDefinition;
- (void)awakeFromNib;
@property(nonatomic) __weak UILabel *lblDef; // @synthesize lblDef;
@property(nonatomic) __weak UILabel *lblPron; // @synthesize lblPron;
@property(nonatomic) __weak UILabel *lblWord; // @synthesize lblWord;

@end

