//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

#import "NSURLSessionDownloadDelegate-Protocol.h"

@class NSString;

@interface _TtC7BingDic21FileDownloadOperation : NSOperation <NSURLSessionDownloadDelegate>
{
    // Error parsing type: , name: task
    // Error parsing type: , name: downloadUrl
    // Error parsing type: , name: localPath
    // Error parsing type: , name: hasFinish
    // Error parsing type: , name: isExcuting
    // Error parsing type: , name: totalSize
    // Error parsing type: , name: currentSize
    // Error parsing type: , name: updateProgressAction
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)resume;
- (void)pause;
- (void)cancel;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (_Bool)isConcurrent;
- (_Bool)isAsynchronous;
- (void)start;
- (id)initWithUrl:(id)arg1 localPath:(id)arg2;
@property(nonatomic, copy) CDUnknownBlockType updateProgressAction; // @synthesize updateProgressAction;
@property(nonatomic) double currentSize; // @synthesize currentSize;
@property(nonatomic) double totalSize; // @synthesize totalSize;
@property(nonatomic) _Bool isExcuting; // @synthesize isExcuting;
@property(nonatomic) _Bool hasFinish; // @synthesize hasFinish;
@property(nonatomic, readonly) NSString *localPath; // @synthesize localPath;
@property(nonatomic, readonly) NSString *downloadUrl; // @synthesize downloadUrl;

// Remaining properties
@property(nonatomic, readonly) _Bool asynchronous;
@property(nonatomic, readonly) _Bool concurrent;
@property(nonatomic, readonly) _Bool executing;
@property(nonatomic, readonly) _Bool finished;

@end

