//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_$S10RealmSwift6ObjectCN.h"

@class NSString;

@interface _TtC7BingDic17SearchHistoryItem : _$S10RealmSwift6ObjectCN
{
    // Error parsing type: , name: searchText
    // Error parsing type: , name: quickDefinition
    // Error parsing type: , name: phonetic
    // Error parsing type: , name: addTime
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithValue:(id)arg1 schema:(id)arg2;
- (id)initWithRealm:(id)arg1 schema:(id)arg2;
- (id)initWithValue:(id)arg1;
- (id)init;
@property(nonatomic, copy) NSString *addTime; // @synthesize addTime;
@property(nonatomic, copy) NSString *phonetic; // @synthesize phonetic;
@property(nonatomic, copy) NSString *quickDefinition; // @synthesize quickDefinition;
@property(nonatomic, copy) NSString *searchText; // @synthesize searchText;

@end

