//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDictionary, NSString, NSURL;

@protocol _TtP7BingDic19AuthRequestProtocol_

@optional
- (void)beginUserInfoParsingWithJson:(NSDictionary *)arg1;
- (void)beginUserInfoRequestByAccessJson:(NSDictionary *)arg1;
- (void)beginAccessTokenRequestByCode:(NSString *)arg1;
- (_Bool)handleOpenURLWithUrl:(NSURL *)arg1;
- (void)beginCodeRequest;
@end

