//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class NSArray, NSMutableArray, NSMutableAttributedString, NSTextCheckingResult, UIColor;
@protocol BDAttributedLabelDelegate;

@interface BDAttributedLabel : UILabel
{
    id <BDAttributedLabelDelegate> delegate;
    NSMutableAttributedString *_attributedText;
    struct __CTFrame *textFrame;
    struct CGRect drawingRect;
    NSMutableArray *customLinks;
    NSTextCheckingResult *activeLink;
    struct CGPoint touchStartPoint;
    NSArray *attributedWords;
    NSMutableArray *similarActiveLinks;
    long long highlightedIndex;
    _Bool onlyCatchTouchesOnLinks;
    _Bool _underlineLinks;
    UIColor *linkColor;
    UIColor *highlightedLinkColor;
}

@property(nonatomic) _Bool underlineLinks; // @synthesize underlineLinks=_underlineLinks;
@property(nonatomic) long long highlightedIndex; // @synthesize highlightedIndex;
@property(retain, nonatomic) NSArray *attributedWords; // @synthesize attributedWords;
@property(nonatomic) id <BDAttributedLabelDelegate> delegate; // @synthesize delegate;
@property(nonatomic) _Bool onlyCatchTouchesOnLinks; // @synthesize onlyCatchTouchesOnLinks;
@property(retain, nonatomic) UIColor *highlightedLinkColor; // @synthesize highlightedLinkColor;
@property(retain, nonatomic) UIColor *linkColor; // @synthesize linkColor;
- (void)setNeedsDisplay;
@property(copy, nonatomic) NSMutableAttributedString *attributedText;
- (void)drawActiveLinkHighlightForRect:(struct CGRect)arg1 range:(struct _NSRange)arg2;
- (void)drawTextInRect:(struct CGRect)arg1;
- (void)resetTextFrame;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateHighlightState;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)linkAtPoint:(struct CGPoint)arg1;
- (id)linkAtCharacterIndex:(long long)arg1;
- (id)attributedTextWithLinks;
- (void)removeAllCustomLinks;
- (void)addCustomLink:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)commonInit;

@end

