//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVAudioPlayerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class AVAudioPlayer, NSOperationQueue, NSString, UIView;

@interface BDAudioEngine : NSObject <AVAudioPlayerDelegate, UIAlertViewDelegate>
{
    AVAudioPlayer *player;
    NSOperationQueue *downWorkQueue;
    _Bool interrupted;
    NSString *mediaId;
    UIView *parentView;
    NSString *audioType;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shared;
@property(copy, nonatomic) NSString *audioType; // @synthesize audioType;
@property(nonatomic) UIView *parentView; // @synthesize parentView;
@property(nonatomic) _Bool interrupted; // @synthesize interrupted;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId;
@property(retain, nonatomic) AVAudioPlayer *player; // @synthesize player;
- (void)audioPlayerEndInterruption:(id)arg1;
- (void)audioPlayerBeginInterruption:(id)arg1;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)_successDownload:(id)arg1;
- (void)_failedDownload;
- (void)_startDownloading;
- (void)stop;
- (void)playWithMID:(id)arg1 parentView:(id)arg2;
- (void)playWithMID:(id)arg1 type:(id)arg2 parentView:(id)arg3;
- (id)audioRemoteUrl;
- (void)playUrl:(id)arg1 parentView:(id)arg2;
- (void)playWithResourcePath:(id)arg1;
- (void)playWithResourcePath:(id)arg1 parentView:(id)arg2;
- (id)init;
- (id)autorelease;
- (void)forceRelease;
- (oneway void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

