//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BDHistorySearch : NSObject
{
    int hid;
    NSString *searchText;
    NSString *quickDefinition;
    NSString *phonetic;
    NSString *addTime;
}

@property(copy, nonatomic) NSString *addTime; // @synthesize addTime;
@property(copy, nonatomic) NSString *phonetic; // @synthesize phonetic;
@property(copy, nonatomic) NSString *quickDefinition; // @synthesize quickDefinition;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText;
@property(nonatomic) int hid; // @synthesize hid;
- (void)dealloc;

@end

