//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableData, NSString;

@interface BDMediaFileInfo : NSObject
{
    int taskIndex;
    NSString *resourcePath;
    NSMutableData *data;
}

@property(nonatomic) int taskIndex; // @synthesize taskIndex;
@property(retain, nonatomic) NSMutableData *data; // @synthesize data;
@property(copy, nonatomic) NSString *resourcePath; // @synthesize resourcePath;
- (void)dealloc;

@end

