//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface BDStringUserDefaults : NSObject
{
    NSArray *_stringValuelist;
}

+ (id)imageNameWithChinese:(id)arg1 english:(id)arg2;
+ (id)stringChinese:(id)arg1 english:(id)arg2;
+ (id)SettingStringByID:(int)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shared;
@property(retain, nonatomic) NSArray *stringValuelist; // @synthesize stringValuelist=_stringValuelist;
- (id)getUIString:(long long)arg1;
- (id)init;
- (id)autorelease;
- (void)forceRelease;
- (oneway void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

