//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BDUserDefaults : NSObject
{
    _Bool supportCopySearch;
    _Bool autoAddWord;
    unsigned long long _connType;
    unsigned long long _lanType;
    unsigned long long _defaultFontSize;
    long long _defaultHistoryCacheNumber;
    unsigned long long runTime;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shared;
@property(nonatomic) unsigned long long runTime; // @synthesize runTime;
@property(nonatomic) _Bool autoAddWord; // @synthesize autoAddWord;
@property(nonatomic) _Bool supportCopySearch; // @synthesize supportCopySearch;
@property(nonatomic) long long defaultHistoryCacheNumber; // @synthesize defaultHistoryCacheNumber=_defaultHistoryCacheNumber;
@property(nonatomic) unsigned long long defaultFontSize; // @synthesize defaultFontSize=_defaultFontSize;
@property(nonatomic) unsigned long long lanType; // @synthesize lanType=_lanType;
@property(nonatomic) unsigned long long connType; // @synthesize connType=_connType;
- (void)resetSystem;
- (void)getDefaultValueFromLocal;
- (id)init;
- (id)autorelease;
- (void)forceRelease;
- (oneway void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

