//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BDUtils : NSObject
{
}

+ (struct CGSize)GetTextSize:(id)arg1 withFontSize:(double)arg2 withMaxSize:(struct CGSize)arg3;
+ (id)getLocalDateStringFromString:(id)arg1;
+ (id)getURIHash:(id)arg1;
+ (id)getUTCDateFromString:(id)arg1;
+ (id)getUTCDate;
+ (id)replaceUnicode:(id)arg1;
+ (void)alertMessage:(id)arg1;
+ (void)alertTitle:(id)arg1 message:(id)arg2;
+ (_Bool)isWiFiAvailable;
+ (_Bool)isNetworkAvailable;
+ (id)colorFromHexColor:(id)arg1;
+ (id)imageCompressForWidth:(id)arg1 targetWidth:(double)arg2;
+ (id)getImageFromURL:(id)arg1;
+ (void)hideErrorMsgView:(id)arg1;
+ (void)showErrorMsgView:(id)arg1 errorMsg:(id)arg2 target:(id)arg3 selector:(SEL)arg4 showTabBar:(_Bool)arg5;
+ (void)showErrorMsgView:(id)arg1 errorMsg:(id)arg2 showTabBar:(_Bool)arg3;

@end

