//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BICoreDataCacheWriteOperationDelegate-Protocol.h"

@class NSMutableDictionary, NSOperationQueue, NSString;

@interface BICoreDataCacheOperationQueue : NSObject <BICoreDataCacheWriteOperationDelegate>
{
    NSOperationQueue *mWriteQueue;
    NSMutableDictionary *mWriteOperations;
}

- (id)dataForKey:(id)arg1;
- (void)dataDidWriteForKey:(id)arg1;
- (void)enqueueFlushOperation:(id)arg1;
- (void)enqueueDeleteOperation:(id)arg1;
- (void)enqueueWriteOperation:(id)arg1;
- (void)enqueueOperation:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

