//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BICoreDataCacheBaseOperation.h"

@class NSManagedObjectID, NSString;

@interface BICoreDataCacheDeleteOperation : BICoreDataCacheBaseOperation
{
    NSManagedObjectID *mDeleteObjectID;
    NSString *mDeleteDataFilePath;
    _Bool mDoDeleteData;
    _Bool mDoDeleteCacheObject;
}

@property _Bool doDeleteCacheObject; // @synthesize doDeleteCacheObject=mDoDeleteCacheObject;
@property _Bool doDeleteData; // @synthesize doDeleteData=mDoDeleteData;
@property(retain, nonatomic) NSString *deleteDataFilePath; // @synthesize deleteDataFilePath=mDeleteDataFilePath;
@property(retain, nonatomic) NSManagedObjectID *deleteObjectID; // @synthesize deleteObjectID=mDeleteObjectID;
- (void)dealloc;
- (void)main;

@end

