//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BICacheMetrics, BICoreDataCacheOperationQueue, BICoreDataManager, NSMutableDictionary, NSNotificationQueue, NSPersistentStore, NSString;

@interface BICoreDataCache : NSObject
{
    BICoreDataManager *mCoreDataManager;
    NSPersistentStore *mCacheStore;
    NSString *mRootDataPath;
    unsigned long long mCurrentCacheSizeBytes;
    unsigned long long mMaxCacheSizeBytes;
    _Bool mFlushingCache;
    BICoreDataCacheOperationQueue *mOperationQueue;
    NSMutableDictionary *mSaveObjectList;
    _Bool mIdleNotificationPosted;
    NSNotificationQueue *mMainQueue;
}

+ (id)fullPathForFileWithName:(id)arg1;
+ (id)instance;
+ (void)initialize;
@property(getter=isIdleNotificationPosted) _Bool idleNotificationPosted; // @synthesize idleNotificationPosted=mIdleNotificationPosted;
@property(getter=isFlushingCache) _Bool flushingCache; // @synthesize flushingCache=mFlushingCache;
@property unsigned long long currentCacheSizeBytes; // @synthesize currentCacheSizeBytes=mCurrentCacheSizeBytes;
@property(readonly, nonatomic) unsigned long long maxCacheSizeBytes; // @synthesize maxCacheSizeBytes=mMaxCacheSizeBytes;
@property(readonly, retain, nonatomic) NSString *rootDataPath; // @synthesize rootDataPath=mRootDataPath;
- (void)saveGetDataUpdates;
- (void)emptyCache;
- (void)flushCacheWithExpireDate:(id)arg1;
- (void)flushCache;
- (void)storeData:(id)arg1 expiresAt:(id)arg2 forKey:(id)arg3;
- (_Bool)getData:(id *)arg1 forKey:(id)arg2;
- (unsigned long long)cachedObjectCount;
@property(readonly, nonatomic) BICacheMetrics *cacheMetrics;
- (void)dealloc;
- (void)setupCoreDataManagerWithBundle:(id)arg1;
- (id)init;
- (void)_doIdleProcessing:(id)arg1;
- (void)_postIdleNotification;
- (void)_saveGetDataUpdates;
- (void)_flushCacheWithExpireDate:(id)arg1 forceCacheSize:(unsigned long long)arg2;
- (void)_isFullShrinkIfNecessaryForDataSize:(unsigned long long)arg1;
- (unsigned long long)_cacheSizeBytes;
- (void)_deleteDirectory:(id)arg1;
- (void)_deleteDirectoryIfExists:(id)arg1;
- (id)_readData:(id)arg1 key:(id)arg2;
- (id)_fullPathForFile;
- (_Bool)_verifyDirectory:(id)arg1;

@end

