//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSDate, NSNumber, NSString;

@interface BICoreDataCacheObject : NSManagedObject
{
}

- (void)awakeFromInsert;

// Remaining properties
@property(retain, nonatomic) NSDate *creationDate; // @dynamic creationDate;
@property(retain, nonatomic) NSString *dataFilepath; // @dynamic dataFilepath;
@property(retain, nonatomic) NSNumber *dataSize; // @dynamic dataSize;
@property(retain, nonatomic) NSDate *expiresAt; // @dynamic expiresAt;
@property(retain, nonatomic) NSString *key; // @dynamic key;
@property(retain, nonatomic) NSDate *lastRead; // @dynamic lastRead;

@end

