//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSPersistentStoreCoordinator;

@interface BICoreDataManager : NSObject
{
    NSPersistentStoreCoordinator *mPersistentStoreCoordinator;
}

@property(readonly, nonatomic) NSPersistentStoreCoordinator *persistentStoreCoordinator; // @synthesize persistentStoreCoordinator=mPersistentStoreCoordinator;
- (_Bool)saveChanges:(id)arg1;
- (id)managedObjectForUrl:(id)arg1 withManagedObjectContext:(id)arg2;
- (id)urlForManagedObject:(id)arg1;
- (id)fetchRequestForEntity:(id)arg1 withManagedObjectContext:(id)arg2;
- (id)managedObjectContextWithUndo;
- (id)managedObjectContext;
- (_Bool)removePersistentStore:(id)arg1;
- (id)addPersistentStoreFromPath:(id)arg1 storeType:(id)arg2 withOptions:(id)arg3;
- (id)addPersistentStoreFromPath:(id)arg1;
- (void)dealloc;
- (id)initWithModelNamed:(id)arg1 bundle:(id)arg2;
- (void)_logError:(id)arg1;
- (id)_managedObjectContextEnableUndo:(_Bool)arg1;

@end

