//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class BICoreDataManager, NSString;

@interface BICoreDataCacheBaseOperation : NSOperation
{
    BICoreDataManager *mCoreDataManager;
    NSString *mRootDataPath;
}

@property(retain, nonatomic) NSString *rootDataPath; // @synthesize rootDataPath=mRootDataPath;
@property(retain, nonatomic) BICoreDataManager *coreDataManager; // @synthesize coreDataManager=mCoreDataManager;
- (void)deleteCacheDataWithObjects:(id)arg1 withManagedObjectContext:(id)arg2;
- (_Bool)deleteCacheObject:(id)arg1 withContext:(id)arg2 save:(_Bool)arg3 updateCacheSize:(_Bool)arg4;
- (_Bool)deleteCacheObject:(id)arg1 save:(_Bool)arg2 updateCacheSize:(_Bool)arg3;
- (_Bool)deleteData:(id)arg1;
- (void)dealloc;
- (id)init;

@end

