//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol BINetworkURLRequestManagerDelegate;

@interface BINetworkURLRequestManager : NSObject
{
    NSMutableArray *mQueue;
    NSMutableArray *mExecuting;
    NSMutableArray *mPendingFromOtherThreads;
    unsigned long long mMaxConcurrentOperationCount;
    NSObject<BINetworkURLRequestManagerDelegate> *mDelegate;
}

@property(nonatomic) NSObject<BINetworkURLRequestManagerDelegate> *delegate; // @synthesize delegate=mDelegate;
@property(nonatomic) unsigned long long maxConcurrentOperationCount; // @synthesize maxConcurrentOperationCount=mMaxConcurrentOperationCount;
- (void)connectionDidFinishLoading:(id)arg1;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didCancelAuthenticationChallenge:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)terminate;
- (_Bool)cancelRequest:(id)arg1;
- (void)_completeRequest:(id)arg1 callDelegate:(_Bool)arg2;
- (id)_requestForConnection:(id)arg1;
- (void)_executeRequest:(id)arg1;
- (void)_executeRequests;
- (void)performRequest:(id)arg1;
- (void)_performRequestOnMainThread:(id)arg1;
- (_Bool)_isRequestPendingAndRemove:(id)arg1;
- (void)_addRequestToPendingList:(id)arg1;
- (_Bool)isNetworkActivity;
- (void)dealloc;
- (id)init;

@end

