//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BINetworkURLRequestManagerDelegate-Protocol.h"
#import "BINetworkWorkQueueDelegate-Protocol.h"

@class BINetworkURLRequestManager, BINetworkWorkQueue, NSDate, NSString, NSThread;

@interface BINetwork : NSObject <BINetworkURLRequestManagerDelegate, BINetworkWorkQueueDelegate>
{
    BINetworkURLRequestManager *mNetworkRequestManager;
    BINetworkWorkQueue *mWorkQueue;
    struct __CFDictionary *mUserSessions;
    NSThread *mNetCheckThread;
    unsigned int mReachabilityFlags;
    _Bool mConnected;
    _Bool mAppTerminating;
    NSDate *mLastConnectedCheck;
    NSString *mDefaultUserAgent;
}

+ (id)network;
+ (void)initialize;
@property(readonly) NSString *defaultUserAgent; // @synthesize defaultUserAgent=mDefaultUserAgent;
- (void)networkWorkQueueReadFromNetwork:(id)arg1;
- (void)urlRequestManagerUpdateConnectedStatusTo:(_Bool)arg1;
- (void)urlRequestManagerUpdateNetworkActivityIndicator;
- (void)urlRequestManagerCallDelegateStreamingCallback:(id)arg1;
- (void)urlRequestManagerCallDelegateBufferedCallback:(id)arg1;
- (void)userSessionDelete:(id)arg1;
- (void)userSessionDecRef:(id)arg1;
- (void)userSessionAddRef:(id)arg1;
- (void)_appWillTerminate;
- (void)initDefaultUserAgent;
@property(readonly) _Bool isGPRS;
@property(readonly) _Bool isWiFi;
@property(readonly) _Bool isOnline;
@property(readonly) _Bool isConnected;
- (_Bool)cancel:(id)arg1;
- (id)queueRequest:(id)arg1 withState:(id)arg2 andDelegate:(id)arg3 andBuffer:(_Bool)arg4;
- (void)dealloc;
- (id)init;
- (void)_updateNetworkActivityIndicator;
- (void)threadNetCheck;
- (void)checkNetwork;
- (void)_updateConnectedStatusTo:(_Bool)arg1;
- (id)logFlags:(unsigned int)arg1;

@end

