//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class BINetworkInternalRequest;

@protocol BINetworkURLRequestManagerDelegate
- (void)urlRequestManagerUpdateConnectedStatusTo:(_Bool)arg1;
- (void)urlRequestManagerUpdateNetworkActivityIndicator;
- (void)urlRequestManagerCallDelegateStreamingCallback:(BINetworkInternalRequest *)arg1;
- (void)urlRequestManagerCallDelegateBufferedCallback:(BINetworkInternalRequest *)arg1;
@end

