//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BINetworkDataInternalProtocol-Protocol.h"

@class NSData;
@protocol BINetworkDataProtocolDelegate;

@interface BINetworkDataSingleBase : NSObject <BINetworkDataInternalProtocol>
{
}

@property(nonatomic) NSObject<BINetworkDataProtocolDelegate> *delegate;
- (void)cancel;
- (void)appendData:(id)arg1;
@property(readonly, nonatomic) NSData *fullData;
- (long long)read:(char *)arg1 maxLength:(long long)arg2;
@property(readonly, nonatomic) _Bool isStreaming;

@end

