//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class BINetworkInternalRequest, BINetworkWorkQueue;

@interface BINetworkWorkOperation : NSOperation
{
    BINetworkInternalRequest *mRequest;
    BINetworkWorkQueue *mQueue;
}

@property(nonatomic) BINetworkWorkQueue *queue; // @synthesize queue=mQueue;
@property(retain, nonatomic) BINetworkInternalRequest *request; // @synthesize request=mRequest;
- (_Bool)_haveDataForRequest;
- (void)_writeCache;
- (void)_callDelegate;
- (void)main;
- (void)dealloc;

@end

