//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue;
@protocol BINetworkWorkQueueDelegate;

@interface BINetworkWorkQueue : NSObject
{
    NSOperationQueue *mCPUQueue;
    NSOperationQueue *mBlockingQueue;
    NSObject<BINetworkWorkQueueDelegate> *mDelegate;
}

@property(nonatomic) NSObject<BINetworkWorkQueueDelegate> *delegate; // @synthesize delegate=mDelegate;
- (void)terminate;
- (void)_terminateInQueue:(id)arg1;
- (_Bool)cancelRequest:(id)arg1;
- (_Bool)_cancelRequest:(id)arg1 inQueue:(id)arg2;
- (void)executeRequest:(id)arg1;
- (id)_queueForRequest:(id)arg1;
- (void)_readCacheForRequest:(id)arg1;
- (void)dealloc;
- (id)init;

@end

