//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSData, NSDictionary, NSString;

@interface BINetworkRequest : NSObject <NSCopying>
{
    NSString *mUrl;
    NSString *mMethod;
    NSData *mPostData;
    int mType;
    NSDictionary *mHeaders;
}

+ (id)bingAppHeaderValue;
+ (id)bingAppHeaderName;
@property(readonly) NSDictionary *headers; // @synthesize headers=mHeaders;
@property(readonly) NSData *postData; // @synthesize postData=mPostData;
@property(readonly) NSString *method; // @synthesize method=mMethod;
@property(readonly) int type; // @synthesize type=mType;
@property(readonly) NSString *url; // @synthesize url=mUrl;
- (void)addBingAppHeader;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)addValue:(id)arg1 forHeader:(id)arg2;
- (void)dealloc;
- (id)initWithUrl:(id)arg1 andType:(int)arg2 andMethod:(id)arg3 andPostData:(id)arg4;
- (id)initWithUrl:(id)arg1 andType:(int)arg2 andMethod:(id)arg3;
- (id)initWithUrl:(id)arg1 andType:(int)arg2;

@end

