//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue, NSString;

@interface BingDictDataCache : NSObject
{
    NSString *storagePath;
    NSOperationQueue *cacheInQueue;
    NSOperationQueue *cacheOutQueue;
}

+ (id)Instance;
@property(copy, nonatomic) NSString *storagePath; // @synthesize storagePath;
- (void)cleanDisk;
- (void)clearDisk;
- (void)removeDataForKey:(id)arg1;
- (void)removeDataForKey:(id)arg1 fromDisk:(_Bool)arg2;
- (void)queryDiskCacheForKey:(id)arg1 delegate:(id)arg2 userInfo:(id)arg3;
- (void)queryDiskCacheOperation:(id)arg1;
- (void)notifyDelegate:(id)arg1;
- (void)storeData:(id)arg1 forKey:(id)arg2;
- (void)storeData:(id)arg1 forKey:(id)arg2 toDisk:(_Bool)arg3;
- (void)storeKeyWithDataToDisk:(id)arg1;
- (id)cachePathForKey:(id)arg1;
- (void)QueryDiskCacheForKey:(id)arg1 atPath:(id)arg2 delegate:(id)arg3 userInfo:(id)arg4;
- (void)StoreData:(id)arg1 forKey:(id)arg2 atPath:(id)arg3;
- (id)init;
- (void)dealloc;

@end

