//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BIQueryService.h"

@interface BingDataService : BIQueryService
{
}

+ (id)instance;
+ (void)initialize;
- (void)callDelegate:(id)arg1 withResult:(id)arg2;
- (id)newQueryResultForData:(id)arg1 error:(id)arg2 forQuery:(id)arg3 queryId:(id)arg4 httpStatus:(int)arg5 httpHeaders:(id)arg6;
- (id)newNetworkRequest:(id)arg1;

@end

