//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class BIQuery, NSError;

@interface BIQueryResult : NSObject <NSCoding>
{
    NSError *mError;
    BIQuery *mQuery;
    id mQueryId;
    _Bool mIsPartial;
}

@property(nonatomic) _Bool isPartial; // @synthesize isPartial=mIsPartial;
@property(nonatomic) id queryId; // @synthesize queryId=mQueryId;
@property(retain, nonatomic) BIQuery *query; // @synthesize query=mQuery;
@property(retain, nonatomic) NSError *error; // @synthesize error=mError;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

