//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BINetworkProtocol-Protocol.h"

@class NSMutableDictionary, NSString;

@interface BIQueryService : NSObject <BINetworkProtocol>
{
    NSMutableDictionary *mQueryStates;
    NSObject *mLock;
    NSString *mFormCode;
}

@property(retain, nonatomic) NSString *mFormCode; // @synthesize mFormCode;
@property(readonly, nonatomic) NSString *version;
- (void)dealloc;
- (void)cancelSearch:(id)arg1;
- (void)callUIDelegate:(id)arg1;
- (void)callDelegate:(id)arg1 withResult:(id)arg2;
- (void)networkError:(id)arg1 withState:(id)arg2;
- (void)networkData:(id)arg1 withState:(id)arg2 withHttpStatus:(int)arg3 withHttpHeaders:(id)arg4;
- (_Bool)isValidHttpStatus:(int)arg1;
- (void)callDelegateForQueryId:(id)arg1 result:(id)arg2 finalCall:(_Bool)arg3;
- (void)createQueryResultForQueryState:(id)arg1 networkError:(id)arg2 networkData:(id)arg3 httpStatus:(int)arg4 httpHeaders:(id)arg5;
- (id)newQueryResultForData:(id)arg1 error:(id)arg2 forQuery:(id)arg3 queryId:(id)arg4 httpStatus:(int)arg5 httpHeaders:(id)arg6;
- (id)processQuery:(id)arg1 delegate:(id)arg2;
- (id)newNetworkRequest:(id)arg1;
- (void)deleteQueryState:(int)arg1;
- (id)getQueryStateForId:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

