//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CALayer, UIActivityIndicatorView, UILabel;
@protocol BIRefreshControlDelegate;

@interface BIRefreshControl : UIView
{
    id <BIRefreshControlDelegate> delegate;
    CALayer *arrowImage;
    int _state;
    UIActivityIndicatorView *_activityView;
    UILabel *messLabel;
    float startOffsetY;
    float currentOffsetY;
}

@property id <BIRefreshControlDelegate> delegate; // @synthesize delegate;
- (void)dealloc;
- (void)doRefreshData;
- (void)refreshScrollViewDidEndDragging:(id)arg1;
- (void)refreshScrollViewDidScroll:(id)arg1;
- (void)refreshScrollViewWillBeginDragging:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setState:(int)arg1;
- (void)animateRefreshing;
- (void)didFinshRefreshing;

@end

