//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextView.h>

@protocol CustomMenuTextViewDelegate;

@interface CustomMenuTextView : UITextView
{
    id <CustomMenuTextViewDelegate> mdelegate;
}

@property(nonatomic) id <CustomMenuTextViewDelegate> mdelegate; // @synthesize mdelegate;
- (void)copySelectedText:(id)arg1;
- (void)translate:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

