//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BIQueryService, NSFileManager, NSMutableDictionary, NSOperationQueue, NSString;

@interface DataNetworkCacheService : NSObject
{
    BIQueryService *queryService;
    int maxCacheSize;
    NSString *cacheDirectory;
    _Bool disableCache;
    _Bool updatePrioritiesOnUse;
    NSMutableDictionary *delegates;
    NSMutableDictionary *priorities;
    NSFileManager *fm;
    NSOperationQueue *fileOpQueue;
}

@property(nonatomic) _Bool updatePrioritiesOnUse; // @synthesize updatePrioritiesOnUse;
@property(nonatomic) _Bool disableCache; // @synthesize disableCache;
@property(nonatomic) int maxCacheSize; // @synthesize maxCacheSize;
@property(retain, nonatomic) BIQueryService *queryService; // @synthesize queryService;
- (void)removeTarget:(id)arg1;
- (void)cancellAllOperations;
- (id)getCacheKeyStrings;
- (_Bool)isMatchingCacheEntryExists:(id)arg1;
- (_Bool)isCacheEntryExists:(id)arg1;
- (void)updatePrioritiesFile;
- (void)dealloc;
- (void)queryFailed:(id)arg1;
- (void)querySucceeded:(id)arg1;
- (void)executeDelegate:(id)arg1 isFresh:(_Bool)arg2;
- (id)getFileNameWithString:(id)arg1;
- (id)getFileName:(id)arg1;
- (void)writeCacheData:(id)arg1 usingKeyString:(id)arg2;
- (void)writeCacheData:(id)arg1;
- (id)getCacheDataWithString:(id)arg1;
- (id)getCacheData:(id)arg1;
- (void)removeCacheDataWithString:(id)arg1;
- (void)removeCacheData:(id)arg1;
- (void)flushCache;
- (void)requestData:(id)arg1 isCacheDataOK:(_Bool)arg2 writeToCache:(_Bool)arg3 target:(id)arg4;
- (void)requestData:(id)arg1 isCacheDataOK:(_Bool)arg2 target:(id)arg3;
- (id)initWithQueryService:(id)arg1 withCacheSize:(int)arg2 withCacheDirectory:(id)arg3;

@end

