//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class BIQueryResult, NSDate;
@protocol NSCoding;

@interface DataNetworkCacheEntry : NSObject <NSCoding>
{
    BIQueryResult<NSCoding> *queryResult;
    NSDate *timestamp;
}

@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp;
@property(retain, nonatomic) BIQueryResult<NSCoding> *queryResult; // @synthesize queryResult;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithQueryResult:(id)arg1;

@end

