//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FilePathManager : NSObject
{
}

+ (id)radioFilePath:(id)arg1;
+ (id)mediaCachePath:(id)arg1;
+ (id)filePathInDocumentsDirctory:(id)arg1;
+ (id)directoryPathByCategroy:(int)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shared;
- (id)createCacheFolderWithName:(id)arg1;
- (id)createFolder:(id)arg1 parent:(id)arg2;
- (id)autorelease;
- (void)forceRelease;
- (oneway void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

