//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface FrameworkElements : NSObject
{
    NSMutableDictionary *colorDictionary;
    NSMutableDictionary *fontDictionary;
}

+ (id)sharedFramework;
- (id)getFrameworkFont:(id)arg1;
- (id)getFrameworkColor:(id)arg1 withOpacity:(double)arg2;
- (id)getFrameworkColor:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)getUIColorFromHexString:(id)arg1 withAlpha:(double)arg2;
- (id)getUIColorFromHexString:(id)arg1;

@end

