//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSOperationQueue, NSString, SqliteHelper;

@interface HistorySearchManager : NSObject
{
    SqliteHelper *sqliteUtil;
    NSOperationQueue *mOperationQueue;
    NSMutableArray *_sessionHistoryList;
    NSString *_dbPath;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shared;
@property(copy, nonatomic) NSString *dbPath; // @synthesize dbPath=_dbPath;
@property(retain, nonatomic) NSMutableArray *sessionHistoryList; // @synthesize sessionHistoryList=_sessionHistoryList;
- (void)syncSession;
- (id)queryData:(id)arg1;
- (void)cleanup;
- (void)saveHistory:(id)arg1;
- (void)createTable;
- (id)init;
- (void)dealloc;
- (id)autorelease;
- (void)forceRelease;
- (oneway void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)migrateData;
- (id)getOldData;

@end

