//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

@class ImageTabBar, NSArray;

@interface ImageTabBarController : UITabBarController
{
    ImageTabBar *tabBar;
    NSArray *tabItems;
}

+ (id)sharedImageTabBar;
@property(retain, nonatomic) NSArray *tabItems; // @synthesize tabItems;
- (void)didReceiveMemoryWarning;
- (void)onTabSelectClick:(int)arg1;
- (void)setSelectedIndex:(unsigned long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

@end

