//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface ImageTabBar : UIView
{
    id delegate;
    SEL OnTabSelect;
    NSMutableArray *tabItems;
    long long selectedIndex;
}

@property(nonatomic) SEL OnTabSelect; // @synthesize OnTabSelect;
@property(nonatomic) id delegate; // @synthesize delegate;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex;
- (void)dealloc;
- (void)animateShow:(_Bool)arg1;
- (void)onSelectItemClick:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1:(id)arg2;

@end

