//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BingDataQuery.h"

@interface ImageCacheQuery : BingDataQuery
{
    struct CGSize maxImageSize;
    _Bool isFresh;
}

- (id)initWithUrl:(id)arg1 andMaxImageSize:(struct CGSize)arg2;
- (id)initWithUrl:(id)arg1 forType:(int)arg2;
- (id)initWithUrl:(id)arg1;
- (id)cacheKey;
@property(readonly) struct CGSize maxImageSize;
@property _Bool isFresh;

@end

