//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;

@interface ImageTabItem : UIView
{
    id delegate;
    SEL OnTabItemSelect;
    _Bool selected;
    UIButton *itemButton;
    UIView *_backgroundView;
    UILabel *_titleLabel;
}

@property(nonatomic) SEL OnTabItemSelect; // @synthesize OnTabItemSelect;
@property(nonatomic) id delegate; // @synthesize delegate;
- (void)dealloc;
@property(nonatomic) _Bool selected; // @synthesize selected;
- (void)setItemContentWithDictionary:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 normalIcon:(id)arg2 selectedIcon:(id)arg3;
- (void)onItemSelectClick;

@end

