//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSString;
@protocol IXISpeechTranslateResultListener;

@protocol IXICommonTranslatorProtocol <NSObject>
- (void)translateContent:(NSString *)arg1;
- (void)end;
- (void)send:(NSData *)arg1;
- (void)begin;
- (void)setTranslateResultListener:(id <IXISpeechTranslateResultListener>)arg1;
- (void)setTargetLanguage:(NSString *)arg1;
- (void)setSourceLanguage:(NSString *)arg1;
- (unsigned long long)translateMode;
@end

