//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSData, NSString;
@protocol IXIOCRNetworkListener;

@protocol IXIOCRNetworkService
- (void)ocrTranslateWithPath:(NSString *)arg1 languageCode:(NSString *)arg2 networkListener:(id <IXIOCRNetworkListener>)arg3;
- (void)ocrTranslateWithBitmap:(NSData *)arg1 languageCode:(NSString *)arg2 networkListener:(id <IXIOCRNetworkListener>)arg3;
@end

