//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol IXIResponseModelProtocol <NSObject>
+ (id)modelWithDict:(NSDictionary *)arg1;
@property(copy, nonatomic) NSString *srText;
@property(copy, nonatomic) NSString *text;

@optional
@property(copy, nonatomic) NSString *errorMessage;
@property(copy, nonatomic) NSString *audiourl;
@property(copy, nonatomic) NSString *audio;
@property(copy, nonatomic) NSString *impressionID;
@property(copy, nonatomic) NSString *responseType;
@property(copy, nonatomic) NSString *type;
@end

