//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol IXIRealtimeRecorderProtocol
+ (id)recorderWithMetersCallback:(void (^)(double))arg1 finishCallback:(void (^)(NSData *))arg2;
+ (id)recorderWithRealtimeCallback:(void (^)(NSData *))arg1 metersCallback:(void (^)(double))arg2;
+ (id)recorderWithRealtimeCallback:(void (^)(NSData *))arg1;
+ (id)recorderWithRealtimeCallback:(void (^)(NSData *))arg1 metersCallback:(void (^)(double))arg2 finishCallback:(void (^)(NSData *))arg3;
- (void)stop;
- (void)stopNoFinish;
- (void)pause;
- (void)start;
@end

