//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface LocalWordsListManager : NSObject
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shared;
- (long long)countOfWords:(id)arg1 isTotalWords:(_Bool)arg2;
- (id)queryWords:(id)arg1 isTotalWords:(_Bool)arg2;
- (void)clearUpWordlist:(id)arg1;
- (void)deleteWords:(id)arg1 inWordList:(id)arg2;
- (void)deleteWord:(id)arg1 inWordList:(id)arg2;
- (void)addWords:(id)arg1 inWordList:(id)arg2 checkingFirst:(_Bool)arg3;
- (void)addWord:(id)arg1 inWordList:(id)arg2;
- (_Bool)isExsitWord:(id)arg1 inWordList:(id)arg2;
- (_Bool)isEmptyWordList:(id)arg1;
- (id)autorelease;
- (void)forceRelease;
- (oneway void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)localNotebook;
- (void)checkLocalNotebookExisting;

@end

