//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabase, NSOperationQueue;

@interface LocalDictManager : NSObject
{
    NSOperationQueue *automatchQueue;
    NSOperationQueue *searchQueue;
    FMDatabase *dbManager;
    FMDatabase *dbManager_auto;
    FMDatabase *dbSpotlight;
}

+ (id)instance;
- (id)queryRangeByCursor:(long long)arg1 length:(long long)arg2;
- (void)searchWord:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)copyToSearch:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getQuickDefinition:(id)arg1;
- (void)automatch:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;
- (void)dealloc;

@end

