//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface NewsRateView : UIView
{
    float rate;
    int _numberOfStar;
    UIView *_normalStarsView;
    UIView *_highlightedStarsView;
}

@property(readonly, nonatomic) int numberOfStar; // @synthesize numberOfStar=_numberOfStar;
@property(retain, nonatomic) UIView *highlightedStarsView; // @synthesize highlightedStarsView=_highlightedStarsView;
@property(retain, nonatomic) UIView *normalStarsView; // @synthesize normalStarsView=_normalStarsView;
@property(nonatomic) float rate; // @synthesize rate;
- (id)creatStarViewWithColor:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 numberOfStar:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

