//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (XICustom)
- (id)XI_HmacSHA1WithKey:(id)arg1;
- (id)XI_base64Decoded;
- (id)XI_base64Encoded;
- (id)XI_trim;
- (id)XI_localizedStringWithBundleId:(id)arg1;
- (id)XI_localizedString;
@end

