//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (BDCategory)
- (BOOL)firstLetter;
- (_Bool)isPunctuation;
- (_Bool)isContainEnglish;
- (_Bool)isEnglish;
- (_Bool)containChinese;
- (_Bool)isChinese;
- (_Bool)isNumbers;
- (id)clearAllPunctuations;
- (id)stringByTrimmingWhitespaceCharacters;
- (_Bool)isEmptyOrWhitespace;
- (_Bool)isWhitespace;
- (_Bool)isNumber;
- (_Bool)isAlpha;
@end

