//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSNumber, NSString;

@interface PersistentWordUnit : NSManagedObject
{
}

- (void)setValueWithWordUnit:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSNumber *correctcount; // @dynamic correctcount;
@property(retain, nonatomic) NSNumber *delegateflag; // @dynamic delegateflag;
@property(retain, nonatomic) NSString *headword; // @dynamic headword;
@property(retain, nonatomic) NSString *modifiedtime; // @dynamic modifiedtime;
@property(retain, nonatomic) NSString *notebookID; // @dynamic notebookID;
@property(retain, nonatomic) NSString *notedesp; // @dynamic notedesp;
@property(retain, nonatomic) NSString *phonetic; // @dynamic phonetic;
@property(retain, nonatomic) NSString *quickdef; // @dynamic quickdef;
@property(retain, nonatomic) NSNumber *wrongcount; // @dynamic wrongcount;

@end

