//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSObject, NSString, UIImage;

@interface ScalingOperation : NSOperation
{
    id target;
    UIImage *image;
    NSString *url;
    _Bool animate;
    struct CGSize maxSize;
    NSObject *object;
}

@property(retain, nonatomic) NSObject *object; // @synthesize object;
@property struct CGSize maxSize; // @synthesize maxSize;
@property(retain, nonatomic) NSString *url; // @synthesize url;
@property(nonatomic) _Bool animate; // @synthesize animate;
@property(retain, nonatomic) UIImage *image; // @synthesize image;
@property(nonatomic) id target; // @synthesize target;
- (void)setNewImage:(id)arg1;
- (void)dealloc;
- (void)main;

@end

