//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIWebViewDelegate-Protocol.h"

@class BIShellLoadingView, NSString, NSURLRequest, UIWebView;

@interface SharingWebViewController : UIViewController <UIWebViewDelegate>
{
    BIShellLoadingView *loadingView;
    UIWebView *webView;
    NSURLRequest *request;
    id delegate;
}

@property(nonatomic) id delegate; // @synthesize delegate;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)cancel:(id)arg1;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)LoadRequest:(id)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

