//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BIQueryResult.h"

@class NSString;

@interface SharingResult : BIQueryResult
{
    id resultDict;
    NSString *resultRawString;
}

@property(retain, nonatomic) NSString *resultRawString; // @synthesize resultRawString;
@property(retain, nonatomic) id resultDict; // @synthesize resultDict;
- (void)dealloc;

@end

