//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BIQuery.h"

@class NSData, NSString;

@interface SharingQuery : BIQuery
{
    _Bool isMultiPartForm;
    int Type;
    NSString *Url;
    NSData *PostData;
}

@property(nonatomic) int Type; // @synthesize Type;
@property(nonatomic) _Bool isMultiPartForm; // @synthesize isMultiPartForm;
@property(retain, nonatomic) NSData *PostData; // @synthesize PostData;
@property(retain, nonatomic) NSString *Url; // @synthesize Url;
- (void)dealloc;

@end

