//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface TCBorderView : UIView
{
    UIColor *borderColor;
    struct UIEdgeInsets _borderSides;
}

@property(nonatomic) struct UIEdgeInsets borderSides; // @synthesize borderSides=_borderSides;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

