//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (XICustom)
+ (void)XI_forceLinkerLoad_;
+ (id)XI_colorWithHexString:(id)arg1 alpha:(double)arg2;
+ (id)XI_colorWithHexString:(id)arg1;
+ (id)XI_colorWithHex:(unsigned long long)arg1 alpha:(double)arg2;
+ (id)XI_colorWithHex:(unsigned long long)arg1;
@end

