//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (XICustom)
- (id)getButtonWithFrame:(struct CGRect)arg1 action:(SEL)arg2 title:(id)arg3 color:(id)arg4 image:(id)arg5 font:(id)arg6;
@end

