//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (autoresizing)
- (struct CGPoint)centerPoint;
- (void)setCenterInView:(id)arg1 left:(float)arg2 size:(struct CGSize)arg3;
- (void)setCenterInView:(id)arg1 top:(float)arg2 size:(struct CGSize)arg3;
- (void)setCenterInView:(id)arg1 size:(struct CGSize)arg2;
- (void)setSizeInView:(id)arg1 margin:(struct CGRect)arg2;
- (void)addSubview:(id)arg1 size:(struct CGSize)arg2;
- (void)addSubview:(id)arg1 margin:(struct CGRect)arg2;
- (void)addSubviewTop:(id)arg1 middleView:(id)arg2 bottomView:(id)arg3 topHeight:(double)arg4 bottomHeight:(double)arg5;
- (void)addSubviewLeft:(id)arg1 middleView:(id)arg2 rightView:(id)arg3 lefWidth:(double)arg4 rightWidth:(double)arg5;
- (void)addSubviewLeft:(id)arg1 middleView:(id)arg2 rightView:(id)arg3 lefWidth:(double)arg4 rightWidth:(double)arg5 margin:(struct CGRect)arg6;
@end

