//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ImageCacheDelegate-Protocol.h"

@class ImageCacheService, NSString, UIImage, UIImageView, UILabel;
@protocol ViewCardDelegate;

@interface ViewCard : UIView <ImageCacheDelegate>
{
    UIImageView *imageView;
    UIImageView *smallImageView;
    UILabel *label;
    UILabel *primaryLabel;
    UILabel *secondaryLabel;
    UIView *labelBackground;
    UIImageView *imagePlaceHolderView;
    UILabel *titleLabel;
    UIView *touchFeedbackView;
    _Bool resizeLabelToText;
    struct CGSize padding;
    int cardStyle;
    NSString *imageUrl;
    _Bool flip;
    id <ViewCardDelegate> delegate;
    id dataToPassOnTap;
    ImageCacheService *cacheService;
    UIImage *originalImage;
    _Bool shouldScalingImage;
    _Bool hasImage;
    _Bool shouldCorpImage;
}

+ (id)newControlInstanceWithStyle:(int)arg1;
+ (id)newControlInstanceWithStyle:(int)arg1 withFrame:(struct CGRect)arg2;
+ (id)newControlInstanceWithStyle:(int)arg1 withFrame:(struct CGRect)arg2 andPadding:(struct CGSize)arg3;
@property(nonatomic) _Bool shouldCorpImage; // @synthesize shouldCorpImage;
@property(nonatomic) _Bool shouldScalingImage; // @synthesize shouldScalingImage;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage;
@property struct CGSize padding; // @synthesize padding;
@property(nonatomic) _Bool resizeLabelToText; // @synthesize resizeLabelToText;
@property(retain, nonatomic) UIView *touchFeedbackView; // @synthesize touchFeedbackView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel;
@property(retain, nonatomic) UIImageView *imagePlaceHolderView; // @synthesize imagePlaceHolderView;
@property(retain, nonatomic) UIView *labelBackground; // @synthesize labelBackground;
@property(retain, nonatomic) UILabel *secondaryLabel; // @synthesize secondaryLabel;
@property(retain, nonatomic) UILabel *primaryLabel; // @synthesize primaryLabel;
@property(retain, nonatomic) UILabel *label; // @synthesize label;
@property(retain, nonatomic) ImageCacheService *cacheService; // @synthesize cacheService;
@property(retain, nonatomic) UIImageView *smallImageView; // @synthesize smallImageView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
@property(nonatomic) _Bool hasImage; // @synthesize hasImage;
@property(retain, nonatomic) id dataToPassOnTap; // @synthesize dataToPassOnTap;
@property(nonatomic) id <ViewCardDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl;
@property(nonatomic) int cardStyle; // @synthesize cardStyle;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (void)setBackgroundImageType:(id)arg1 withContentStretch:(long long)arg2;
- (void)imageReceived:(id)arg1 isFresh:(_Bool)arg2;
- (void)waitForImageUrl:(id)arg1 withFlip:(_Bool)arg2 withCacheService:(id)arg3;
- (void)waitForImageUrl:(id)arg1 withCacheService:(id)arg2;
- (void)setTitle:(id)arg1 withDescription:(id)arg2;
- (void)setTitle:(id)arg1;
- (void)setImage:(id)arg1 withAnimation:(_Bool)arg2;
- (void)cardTapped:(id)arg1;
- (void)setPrimaryLabelText:(id)arg1 withSecondaryLabelText:(id)arg2;
- (void)releaseDelegate:(id)arg1;
- (void)awakeFromNib;

@end

