//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSMutableCopying-Protocol.h"

@class NSDate, NSString;

@interface WordUnit : NSObject <NSCoding, NSCopying, NSMutableCopying>
{
    NSString *headWord;
    NSString *phonetic;
    NSString *quickDefinition;
    NSString *lastModefiedTime;
    NSString *wordnote;
    NSDate *lastModefiedDate;
    _Bool deleteFlag;
    int correctCountInTest;
    int wrongCountInTest;
    double familiarty;
    NSDate *_lastModefiedDate;
}

@property(copy, nonatomic) NSString *wordnote; // @synthesize wordnote;
@property(copy, nonatomic) NSDate *lastModefiedDate; // @synthesize lastModefiedDate=_lastModefiedDate;
@property(nonatomic) int wrongCountInTest; // @synthesize wrongCountInTest;
@property(nonatomic) int correctCountInTest; // @synthesize correctCountInTest;
@property(nonatomic) _Bool deleteFlag; // @synthesize deleteFlag;
@property(copy, nonatomic) NSString *lastModefiedTime; // @synthesize lastModefiedTime;
@property(copy, nonatomic) NSString *quickDefinition; // @synthesize quickDefinition;
@property(copy, nonatomic) NSString *phonetic; // @synthesize phonetic;
@property(copy, nonatomic) NSString *headWord; // @synthesize headWord;
- (id)description;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
@property(readonly, nonatomic) double familiarty; // @synthesize familiarty;
- (id)init;

@end

