//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IXIAudioRecordViewProtocol-Protocol.h"

@class NSLayoutConstraint, NSString, UIButton, XIVoiceMetersView;
@protocol IXICommonTranslatorProtocol, IXISpeechTranslateProcessListener, IXISpeechTranslateResultListener;

@interface XIAudioRecordView : UIView <IXIAudioRecordViewProtocol>
{
    _Bool _isRecording;
    id <IXICommonTranslatorProtocol> _textTranslator;
    id <IXICommonTranslatorProtocol> _speechTranslator;
    UIButton *_recordButton;
    id <IXICommonTranslatorProtocol> _combinitionTranslator;
    id <IXISpeechTranslateProcessListener> _processListener;
    id <IXISpeechTranslateResultListener> _resultListener;
    XIVoiceMetersView *_metersView;
    NSLayoutConstraint *_consBtnRecordWidth;
    NSLayoutConstraint *_consBtnRecordHeight;
    NSLayoutConstraint *_consBtnRecordBottom;
    NSLayoutConstraint *_consBtnRecordTop;
    NSString *_srText;
}

@property(copy, nonatomic) NSString *srText; // @synthesize srText=_srText;
@property(nonatomic) _Bool isRecording; // @synthesize isRecording=_isRecording;
@property(nonatomic) __weak NSLayoutConstraint *consBtnRecordTop; // @synthesize consBtnRecordTop=_consBtnRecordTop;
@property(nonatomic) __weak NSLayoutConstraint *consBtnRecordBottom; // @synthesize consBtnRecordBottom=_consBtnRecordBottom;
@property(nonatomic) __weak NSLayoutConstraint *consBtnRecordHeight; // @synthesize consBtnRecordHeight=_consBtnRecordHeight;
@property(nonatomic) __weak NSLayoutConstraint *consBtnRecordWidth; // @synthesize consBtnRecordWidth=_consBtnRecordWidth;
@property(nonatomic) __weak XIVoiceMetersView *metersView; // @synthesize metersView=_metersView;
@property(nonatomic) __weak id <IXISpeechTranslateResultListener> resultListener; // @synthesize resultListener=_resultListener;
@property(nonatomic) __weak id <IXISpeechTranslateProcessListener> processListener; // @synthesize processListener=_processListener;
@property(retain, nonatomic) id <IXICommonTranslatorProtocol> combinitionTranslator; // @synthesize combinitionTranslator=_combinitionTranslator;
@property(nonatomic) __weak UIButton *recordButton; // @synthesize recordButton=_recordButton;
@property(retain, nonatomic) id <IXICommonTranslatorProtocol> textTranslator; // @synthesize textTranslator=_textTranslator;
- (void).cxx_destruct;
- (void)OnRecordVoicePower:(double)arg1;
- (void)OnTranslateError:(id)arg1;
- (void)OnSpeechToTextResult:(id)arg1;
- (void)OnTranslateResult:(id)arg1;
- (void)setSpeechTranslateResultListener:(id)arg1;
- (void)setSpeechTranslateProcessListener:(id)arg1;
- (void)setTargetLanguage:(id)arg1;
- (void)setSourceLanguage:(id)arg1;
@property(retain, nonatomic) id <IXICommonTranslatorProtocol> speechTranslator; // @synthesize speechTranslator=_speechTranslator;
- (void)showHideMetersView:(_Bool)arg1;
- (void)setupSubviews;
- (void)btnRecordTouchUpOutside:(id)arg1;
- (void)btnRecordTouchDragOutside:(id)arg1;
- (void)btnRecordTouchDragInside:(id)arg1;
- (void)btnRecordTouchDown:(id)arg1;
- (void)btnRecordTouchUpInside:(id)arg1;
- (unsigned long long)translatorControllerMode;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

