//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, XIConversationCardMessageCellConfigurations, XIConversationCardMessageItemModel;

@interface XIConversationCardMessageItemTableViewCell : UITableViewCell
{
    UIImageView *_contentImageView;
    UILabel *_contentTitleLabel;
    UILabel *_contentDateLabel;
    XIConversationCardMessageCellConfigurations *_cardConfig;
    XIConversationCardMessageItemModel *_cardItemModel;
}

@property(retain, nonatomic) XIConversationCardMessageItemModel *cardItemModel; // @synthesize cardItemModel=_cardItemModel;
@property(retain, nonatomic) XIConversationCardMessageCellConfigurations *cardConfig; // @synthesize cardConfig=_cardConfig;
@property(retain, nonatomic) UILabel *contentDateLabel; // @synthesize contentDateLabel=_contentDateLabel;
@property(retain, nonatomic) UILabel *contentTitleLabel; // @synthesize contentTitleLabel=_contentTitleLabel;
@property(retain, nonatomic) UIImageView *contentImageView; // @synthesize contentImageView=_contentImageView;
- (void).cxx_destruct;
- (void)cellLongPressed:(id)arg1;
- (void)reloadCellWithModel:(id)arg1;
- (void)setupSubViewsWithModel:(id)arg1 config:(id)arg2;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithModel:(id)arg1 config:(id)arg2;

@end

