//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface XIConversationDataBaseManager : NSObject
{
    struct sqlite3 *_database;
    NSString *_databaseTableName;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedManager;
@property(retain, nonatomic) NSString *databaseTableName; // @synthesize databaseTableName=_databaseTableName;
- (void).cxx_destruct;
- (void)cleanDataBase;
- (void)removeTableWithName:(id)arg1;
- (void)removeAllMessage;
- (void)removeMessageWithModel:(id)arg1;
- (id)getMessagesWithStartTime:(double)arg1 count:(int)arg2;
- (_Bool)saveMessageWithModel:(id)arg1;
- (_Bool)createTableWithName:(id)arg1;
- (_Bool)openSqlite;
- (id)init;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopy;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)copy;

@end

