//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class XIConversationImageMessageModel, XIConversationImagePreviewViewController;

@protocol XIConversationImagePreviewViewControllerDelegate <NSObject>

@optional
- (void)conversationImagePreviewViewControllerDidExit:(XIConversationImagePreviewViewController *)arg1;
- (void)conversationImagePreviewViewController:(XIConversationImagePreviewViewController *)arg1 shouldDownloadImage:(XIConversationImageMessageModel *)arg2;
- (_Bool)conversationImagePreviewViewControllerShowNoPhotosPermissionAlert:(XIConversationImagePreviewViewController *)arg1;
@end

