//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XIConversationMessageTableViewCell.h"

@class NSString, UITextView, XIConversationTextMessageCellConfigurations, XIConversationTextMessageModel;
@protocol XIConversationTextMessageTableViewCellDelegate;

@interface XIConversationTextMessageTableViewCell : XIConversationMessageTableViewCell
{
    UITextView *_textView;
    id <XIConversationTextMessageTableViewCellDelegate> _textDelegate;
    XIConversationTextMessageCellConfigurations *_textConfig;
    XIConversationTextMessageModel *_textModel;
}

@property(retain, nonatomic) XIConversationTextMessageModel *textModel; // @synthesize textModel=_textModel;
@property(nonatomic) __weak XIConversationTextMessageCellConfigurations *textConfig; // @synthesize textConfig=_textConfig;
@property(nonatomic) __weak id <XIConversationTextMessageTableViewCellDelegate> textDelegate; // @synthesize textDelegate=_textDelegate;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)onlyTap:(id)arg1;
- (void)longPressed:(id)arg1;
- (void)reloadCellWithModel:(id)arg1;
- (void)setupSubViewWithModel:(id)arg1 config:(id)arg2;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithModel:(id)arg1 config:(id)arg2;
- (void)setDelegateLoadCustomAvatar:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

