//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XIConversationMessageModel.h"

@class NSString;

@interface XIConversationImageMessageModel : XIConversationMessageModel
{
    NSString *_imageURL;
    NSString *_imageLocalPath;
    NSString *_imageLocalFullPath;
    struct CGSize _imageSize;
    struct CGRect _imageRect;
}

+ (id)modelWithModel:(id)arg1;
@property(nonatomic) struct CGRect imageRect; // @synthesize imageRect=_imageRect;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(retain, nonatomic) NSString *imageLocalFullPath; // @synthesize imageLocalFullPath=_imageLocalFullPath;
@property(retain, nonatomic) NSString *imageLocalPath; // @synthesize imageLocalPath=_imageLocalPath;
@property(retain, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (void)readJSONString:(id)arg1;
- (id)translateToJSON;
- (void)calculateCellContentSize:(id)arg1;
- (void)setCellHeight:(double)arg1;
- (void)setSender:(_Bool)arg1;
- (void)setType:(unsigned long long)arg1;

@end

