//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIImage, XIConversationImageMessageModel, XIConversationImagePreviewCollectionViewCell;

@protocol XIConversationImagePreviewCollectionViewCellDelegate <NSObject>

@optional
- (void)conversationImagePreviewCollectionViewCell:(XIConversationImagePreviewCollectionViewCell *)arg1 shouldDownloadImage:(XIConversationImageMessageModel *)arg2;
- (void)conversationImagePreviewCollectionViewCell:(XIConversationImagePreviewCollectionViewCell *)arg1 longPressedWithImage:(UIImage *)arg2;
- (void)conversationImagePreviewCollectionViewCellDidTappedScrollView:(XIConversationImagePreviewCollectionViewCell *)arg1;
@end

