//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "XIConversationAudioMessageTableViewCellDelegate-Protocol.h"
#import "XIConversationCardMessageTableViewCellDelegate-Protocol.h"
#import "XIConversationHttpRequestManagerDelegate-Protocol.h"
#import "XIConversationImageMessageTableViewCellDelegate-Protocol.h"
#import "XIConversationImagePreviewViewControllerDelegate-Protocol.h"
#import "XIConversationInputViewDelegate-Protocol.h"
#import "XIConversationMessageTableViewCellDelegate-Protocol.h"
#import "XIConversationRecordingManagerDelegate-Protocol.h"
#import "XIConversationTextMessageTableViewCellDelegate-Protocol.h"

@class NSMutableArray, NSObject, NSString, UIImageView, UITableView, XIConversationAudioMessageCellConfigurations, XIConversationBlankMessageCellConfigurations, XIConversationCardMessageCellConfigurations, XIConversationConfiguration, XIConversationImageMessageCellConfigurations, XIConversationInputView, XIConversationRecordingTipView, XIConversationTextMessageCellConfigurations, XIConversationTipsCellConfigurations;
@protocol OS_dispatch_queue, XIConversationViewControllerFunctionsDelegate, XIConversationViewControllerUIDelegate;

@interface XIConversationViewController : UIViewController <XIConversationInputViewDelegate, XIConversationMessageTableViewCellDelegate, XIConversationRecordingManagerDelegate, XIConversationHttpRequestManagerDelegate, XIConversationCardMessageTableViewCellDelegate, XIConversationImageMessageTableViewCellDelegate, XIConversationImagePreviewViewControllerDelegate, XIConversationAudioMessageTableViewCellDelegate, XIConversationTextMessageTableViewCellDelegate>
{
    NSObject<OS_dispatch_queue> *_dataQueue;
    _Bool _initByManager;
    _Bool _isNoMoreData;
    _Bool _isLoadLocalData;
    _Bool _isLoaded;
    _Bool _shouldScrollToBottom;
    _Bool _isShowingInputContent;
    _Bool _isShowingImagePreview;
    id <XIConversationViewControllerUIDelegate> _uiDelegate;
    id <XIConversationViewControllerFunctionsDelegate> _functionDelegate;
    XIConversationInputView *_contentInputView;
    XIConversationConfiguration *_configuration;
    XIConversationTextMessageCellConfigurations *_senderTextConfig;
    XIConversationImageMessageCellConfigurations *_senderImageConfig;
    XIConversationAudioMessageCellConfigurations *_senderAudioConfig;
    XIConversationBlankMessageCellConfigurations *_receiverBlanlConfig;
    XIConversationTextMessageCellConfigurations *_receiverTextConfig;
    XIConversationImageMessageCellConfigurations *_receiverImageConfig;
    XIConversationAudioMessageCellConfigurations *_receiverAudioConfig;
    XIConversationCardMessageCellConfigurations *_receiverCardConfig;
    XIConversationTipsCellConfigurations *_timeConfig;
    UIImageView *_backgroundView;
    UITableView *_tableView;
    XIConversationRecordingTipView *_recordingTipView;
    NSMutableArray *_messages;
    double _lastTipTime;
    double _farthestTipTime;
}

@property(nonatomic) _Bool isShowingImagePreview; // @synthesize isShowingImagePreview=_isShowingImagePreview;
@property(nonatomic) _Bool isShowingInputContent; // @synthesize isShowingInputContent=_isShowingInputContent;
@property(nonatomic) double farthestTipTime; // @synthesize farthestTipTime=_farthestTipTime;
@property(nonatomic) double lastTipTime; // @synthesize lastTipTime=_lastTipTime;
@property(retain, nonatomic) NSMutableArray *messages; // @synthesize messages=_messages;
@property(retain, nonatomic) XIConversationRecordingTipView *recordingTipView; // @synthesize recordingTipView=_recordingTipView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) XIConversationTipsCellConfigurations *timeConfig; // @synthesize timeConfig=_timeConfig;
@property(retain, nonatomic) XIConversationCardMessageCellConfigurations *receiverCardConfig; // @synthesize receiverCardConfig=_receiverCardConfig;
@property(retain, nonatomic) XIConversationAudioMessageCellConfigurations *receiverAudioConfig; // @synthesize receiverAudioConfig=_receiverAudioConfig;
@property(retain, nonatomic) XIConversationImageMessageCellConfigurations *receiverImageConfig; // @synthesize receiverImageConfig=_receiverImageConfig;
@property(retain, nonatomic) XIConversationTextMessageCellConfigurations *receiverTextConfig; // @synthesize receiverTextConfig=_receiverTextConfig;
@property(retain, nonatomic) XIConversationBlankMessageCellConfigurations *receiverBlanlConfig; // @synthesize receiverBlanlConfig=_receiverBlanlConfig;
@property(retain, nonatomic) XIConversationAudioMessageCellConfigurations *senderAudioConfig; // @synthesize senderAudioConfig=_senderAudioConfig;
@property(retain, nonatomic) XIConversationImageMessageCellConfigurations *senderImageConfig; // @synthesize senderImageConfig=_senderImageConfig;
@property(retain, nonatomic) XIConversationTextMessageCellConfigurations *senderTextConfig; // @synthesize senderTextConfig=_senderTextConfig;
@property(nonatomic) _Bool shouldScrollToBottom; // @synthesize shouldScrollToBottom=_shouldScrollToBottom;
@property(nonatomic) _Bool isLoaded; // @synthesize isLoaded=_isLoaded;
@property(nonatomic) _Bool isLoadLocalData; // @synthesize isLoadLocalData=_isLoadLocalData;
@property(nonatomic) _Bool isNoMoreData; // @synthesize isNoMoreData=_isNoMoreData;
@property(nonatomic) _Bool initByManager; // @synthesize initByManager=_initByManager;
@property(readonly, nonatomic) XIConversationConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) XIConversationInputView *contentInputView; // @synthesize contentInputView=_contentInputView;
@property(nonatomic) __weak id <XIConversationViewControllerFunctionsDelegate> functionDelegate; // @synthesize functionDelegate=_functionDelegate;
@property(nonatomic) __weak id <XIConversationViewControllerUIDelegate> uiDelegate; // @synthesize uiDelegate=_uiDelegate;
- (void).cxx_destruct;
- (void)conversationImagePreviewViewControllerDidExit:(id)arg1;
- (void)conversationImagePreviewViewController:(id)arg1 shouldDownloadImage:(id)arg2;
- (_Bool)conversationImagePreviewViewControllerShowNoPhotosPermissionAlert:(id)arg1;
- (void)conversationRecordingManagerCompleteRecording:(id)arg1 audioDuration:(float)arg2;
- (void)conversationRecordingManagerRecordingAveragePowerForChannel:(float)arg1 peakPowerForChannel:(float)arg2;
- (void)conversationHttpRequestManager:(id)arg1 requestFailed:(id)arg2 messageModel:(id)arg3 requestModel:(id)arg4;
- (void)conversationHttpRequestManager:(id)arg1 requestSuccessed:(id)arg2 messageModel:(id)arg3 requestModel:(id)arg4;
- (void)conversationCardMessageTableViewCell:(id)arg1 didTappedItemModel:(id)arg2;
- (void)conversationAudioMessageTableViewCellPlayAudioFileNotExists:(id)arg1;
- (void)conversationImageMessageTableViewCellDidClickedImageView:(id)arg1;
- (void)conversationTextMessageTableViewCell:(id)arg1 didClickedLinkWithModel:(id)arg2 linkModel:(id)arg3;
- (void)conversationMessageTableViewCellErrorButtonDidClicked:(id)arg1;
- (void)conversationMessageTableViewCellXiaoIceAvatarDidClicked:(id)arg1;
- (void)conversationMessageTableViewCell:(id)arg1 shouldLoadCustomUserAvatar:(id)arg2;
- (void)conversationInputView:(id)arg1 didClickedReturnButton:(id)arg2;
- (void)conversationInputView:(id)arg1 touchUpOutsideRecordingButton:(id)arg2;
- (void)conversationInputView:(id)arg1 touchUpInsideRecordingButton:(id)arg2;
- (void)conversationInputView:(id)arg1 touchDragOutsideRecordingButton:(id)arg2;
- (void)conversationInputView:(id)arg1 touchDragInsideRecordingButton:(id)arg2;
- (void)conversationInputView:(id)arg1 touchDownRecordingButton:(id)arg2;
- (void)conversationInputViewDidClickedImagePickerFunction:(id)arg1;
- (void)conversationInputViewDidClickedCameraFunction:(id)arg1;
- (void)conversationInputView:(id)arg1 didChangedFrameWithDuration:(double)arg2 beginFrame:(struct CGRect)arg3 endFrame:(struct CGRect)arg4;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollToBottom;
- (void)downloadImageMessage:(id)arg1;
- (void)downloadAudioMessage:(id)arg1;
- (id)compressOriginalImage:(id)arg1;
- (void)getCellConfig:(long long)arg1 isSender:(_Bool)arg2;
- (void)requestRecordPermission;
- (void)setConfiguration:(id)arg1;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)closeKeyboard:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)addNotification;
- (void)insertWelcomeString;
- (void)dealDatas:(id)arg1 isSend:(_Bool)arg2;
- (id)dealModels:(id)arg1 isSend:(_Bool)arg2 save:(_Bool)arg3;
- (void)resendData:(id)arg1;
- (void)sendData:(id)arg1;
- (void)loadData;
- (void)hiddenRecordingTips;
- (void)showRecordingTips;
- (void)setupSubViews;
- (void)reloadView;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

