//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIImageView, XIConversationMessageTableViewCell;

@protocol XIConversationMessageTableViewCellDelegate <NSObject>

@optional
- (void)conversationMessageTableViewCellErrorButtonDidClicked:(XIConversationMessageTableViewCell *)arg1;
- (void)conversationMessageTableViewCellXiaoIceAvatarDidClicked:(XIConversationMessageTableViewCell *)arg1;
- (void)conversationMessageTableViewCell:(XIConversationMessageTableViewCell *)arg1 shouldLoadCustomUserAvatar:(UIImageView *)arg2;
@end

