//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface XIConversationMessageModel : NSObject
{
    _Bool _sender;
    _Bool _unsave;
    unsigned long long _type;
    double _messageTime;
    long long _messageStatus;
    long long _mediaStatus;
    NSString *_cellIdentifier;
    double _cellHeight;
    double _bubbleToAvatarSpace;
    double _bubbleTop;
    double _bubbleBottom;
    struct CGRect _avatarFrame;
    struct CGRect _bubbleRect;
    struct UIEdgeInsets _bubbleContentInset;
    struct CGRect _statusRect;
}

@property(nonatomic) struct CGRect statusRect; // @synthesize statusRect=_statusRect;
@property(nonatomic) struct UIEdgeInsets bubbleContentInset; // @synthesize bubbleContentInset=_bubbleContentInset;
@property(nonatomic) double bubbleBottom; // @synthesize bubbleBottom=_bubbleBottom;
@property(nonatomic) struct CGRect bubbleRect; // @synthesize bubbleRect=_bubbleRect;
@property(nonatomic) double bubbleTop; // @synthesize bubbleTop=_bubbleTop;
@property(nonatomic) double bubbleToAvatarSpace; // @synthesize bubbleToAvatarSpace=_bubbleToAvatarSpace;
@property(nonatomic) struct CGRect avatarFrame; // @synthesize avatarFrame=_avatarFrame;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(retain, nonatomic) NSString *cellIdentifier; // @synthesize cellIdentifier=_cellIdentifier;
@property(nonatomic, getter=isUnsave) _Bool unsave; // @synthesize unsave=_unsave;
@property(nonatomic) long long mediaStatus; // @synthesize mediaStatus=_mediaStatus;
@property(nonatomic) long long messageStatus; // @synthesize messageStatus=_messageStatus;
@property(nonatomic) double messageTime; // @synthesize messageTime=_messageTime;
@property(nonatomic, getter=isSender) _Bool sender; // @synthesize sender=_sender;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)calculateCellContentSize:(id)arg1;

@end

