//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XIConversationMessageTableViewCell.h"

@class UIImageView, XIConversationImageMessageCellConfigurations, XIConversationImageMessageModel;
@protocol XIConversationImageMessageTableViewCellDelegate;

@interface XIConversationImageMessageTableViewCell : XIConversationMessageTableViewCell
{
    id <XIConversationImageMessageTableViewCellDelegate> _imageDelegate;
    UIImageView *_contentImageView;
    XIConversationImageMessageCellConfigurations *_imageConfig;
    XIConversationImageMessageModel *_imageModel;
}

@property(retain, nonatomic) XIConversationImageMessageModel *imageModel; // @synthesize imageModel=_imageModel;
@property(retain, nonatomic) XIConversationImageMessageCellConfigurations *imageConfig; // @synthesize imageConfig=_imageConfig;
@property(retain, nonatomic) UIImageView *contentImageView; // @synthesize contentImageView=_contentImageView;
@property(nonatomic) id <XIConversationImageMessageTableViewCellDelegate> imageDelegate; // @synthesize imageDelegate=_imageDelegate;
- (void).cxx_destruct;
- (void)longPressed:(id)arg1;
- (void)contentImageViewDidClicked:(id)arg1;
- (void)reloadCellWithModel:(id)arg1;
- (void)setupSubViewWithModel:(id)arg1 config:(id)arg2;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithModel:(id)arg1 config:(id)arg2;
- (void)setDelegateLoadCustomAvatar:(_Bool)arg1;

@end

