//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary, NSOperationQueue, NSURLSessionConfiguration;

@interface XIConversationUrlCacheConfig : NSObject
{
    NSMutableDictionary *_urlDict;
    NSMutableArray *_nonCachedUrl;
    long long _updateInterval;
    NSURLSessionConfiguration *_config;
    NSOperationQueue *_forgeroundNetQueue;
    NSOperationQueue *_backgroundNetQueue;
}

+ (id)instance;
@property(retain, nonatomic) NSOperationQueue *backgroundNetQueue; // @synthesize backgroundNetQueue=_backgroundNetQueue;
@property(retain, nonatomic) NSOperationQueue *forgeroundNetQueue; // @synthesize forgeroundNetQueue=_forgeroundNetQueue;
@property(retain, nonatomic) NSURLSessionConfiguration *config; // @synthesize config=_config;
@property(nonatomic) long long updateInterval; // @synthesize updateInterval=_updateInterval;
@property(retain, nonatomic) NSMutableArray *nonCachedUrl; // @synthesize nonCachedUrl=_nonCachedUrl;
@property(retain, nonatomic) NSMutableDictionary *urlDict; // @synthesize urlDict=_urlDict;
- (void).cxx_destruct;
- (_Bool)isNonCachedUrl:(id)arg1;
- (void)clearUrlDict;

@end

