//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVAudioRecorderDelegate-Protocol.h"

@class AVAudioRecorder, NSString, NSTimer;
@protocol XIConversationRecordingManagerDelegate;

@interface XIConversationRecordingManager : NSObject <AVAudioRecorderDelegate>
{
    _Bool _canRecording;
    _Bool _isRecording;
    id <XIConversationRecordingManagerDelegate> _delegate;
    AVAudioRecorder *_recorder;
    NSString *_filePath;
    double _duration;
    NSTimer *_recorderTimer;
    double _startTime;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedManager;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSTimer *recorderTimer; // @synthesize recorderTimer=_recorderTimer;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) AVAudioRecorder *recorder; // @synthesize recorder=_recorder;
@property(nonatomic) __weak id <XIConversationRecordingManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) _Bool isRecording; // @synthesize isRecording=_isRecording;
@property(nonatomic) _Bool canRecording; // @synthesize canRecording=_canRecording;
- (void).cxx_destruct;
- (void)audioRecorderDidFinishRecording:(id)arg1 successfully:(_Bool)arg2;
- (void)recorderTimerEvent;
- (void)cancelRecording;
- (void)stopRecording;
- (void)startRecordingWithFilePath:(id)arg1;
- (void)startRecording;
- (id)init;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopy;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)copy;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

