//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XIConversationMessageModel.h"

@class NSString;

@interface XIConversationAudioMessageModel : XIConversationMessageModel
{
    NSString *_audioURL;
    NSString *_audioLocalPath;
    NSString *_audioLocalFullPath;
    double _audioDuration;
    struct CGRect _animateImageRect;
    struct CGRect _durationRect;
    struct CGRect _unreadRect;
}

+ (id)modelWithModel:(id)arg1;
@property(nonatomic) struct CGRect unreadRect; // @synthesize unreadRect=_unreadRect;
@property(nonatomic) struct CGRect durationRect; // @synthesize durationRect=_durationRect;
@property(nonatomic) struct CGRect animateImageRect; // @synthesize animateImageRect=_animateImageRect;
@property(nonatomic) double audioDuration; // @synthesize audioDuration=_audioDuration;
@property(retain, nonatomic) NSString *audioLocalFullPath; // @synthesize audioLocalFullPath=_audioLocalFullPath;
@property(retain, nonatomic) NSString *audioLocalPath; // @synthesize audioLocalPath=_audioLocalPath;
@property(retain, nonatomic) NSString *audioURL; // @synthesize audioURL=_audioURL;
- (void).cxx_destruct;
- (void)readJSONString:(id)arg1;
- (id)translateToJSON;
- (void)calculateCellContentSize:(id)arg1;
- (void)setCellHeight:(double)arg1;
- (void)setSender:(_Bool)arg1;
- (void)setType:(unsigned long long)arg1;

@end

