//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface XIConversationTextMessageLinkModel : NSObject
{
    NSString *_linkString;
    NSString *_linkURL;
    NSArray *_linkeRects;
    struct _NSRange _linkRange;
}

@property(retain, nonatomic) NSArray *linkeRects; // @synthesize linkeRects=_linkeRects;
@property(nonatomic) struct _NSRange linkRange; // @synthesize linkRange=_linkRange;
@property(retain, nonatomic) NSString *linkURL; // @synthesize linkURL=_linkURL;
@property(retain, nonatomic) NSString *linkString; // @synthesize linkString=_linkString;
- (void).cxx_destruct;

@end

