//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface XICoreLib : NSObject
{
}

+ (id)sharedManager;
- (id)infoWithKey:(long long)arg1;
- (id)HmacSHA1WithString:(id)arg1 key:(id)arg2;
- (id)getSignatureWithRequestURL:(id)arg1 Method:(id)arg2 Body:(id)arg3 Timestamp:(id)arg4 UserId:(id)arg5;
- (id)getSignatureWithRequest:(id)arg1 Timestamp:(id)arg2 UserId:(id)arg3;
@property(readonly, nonatomic) _Bool isAuthorized;
- (id)init;

@end

