//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XIConversationMessageTableViewCell.h"

@class XIConversationBlankMessageCellConfigurations;

@interface XIConversationBlankMessageTableViewCell : XIConversationMessageTableViewCell
{
    XIConversationBlankMessageCellConfigurations *_blankConfig;
}

@property(nonatomic) __weak XIConversationBlankMessageCellConfigurations *blankConfig; // @synthesize blankConfig=_blankConfig;
- (void).cxx_destruct;
- (void)reloadCellWithModel:(id)arg1;
- (void)setupSubViewWithModel:(id)arg1 config:(id)arg2;
- (id)initWithModel:(id)arg1 config:(id)arg2;
- (void)setDelegateLoadCustomAvatar:(_Bool)arg1;

@end

