//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, UIImage;

@interface XIConversationMessageCellConfigurations : NSObject
{
    _Bool _isSender;
    long long _type;
    UIImage *_customAvatarImage;
    double _bubbleToAvatarSpace;
    double _bubbleTopSpace;
    double _bubbleBottomSpace;
    long long _statusViewAlignment;
    double _statusViewToBubbleSpace;
    NSArray *_menuActions;
    struct CGSize _statusViewSize;
    struct CGRect _avatarImageViewFrame;
    struct UIEdgeInsets _bubbleCapInsets;
    struct UIEdgeInsets _contentViewInset;
}

@property(retain, nonatomic) NSArray *menuActions; // @synthesize menuActions=_menuActions;
@property(nonatomic) double statusViewToBubbleSpace; // @synthesize statusViewToBubbleSpace=_statusViewToBubbleSpace;
@property(nonatomic) struct CGSize statusViewSize; // @synthesize statusViewSize=_statusViewSize;
@property(nonatomic) long long statusViewAlignment; // @synthesize statusViewAlignment=_statusViewAlignment;
@property(nonatomic) struct UIEdgeInsets contentViewInset; // @synthesize contentViewInset=_contentViewInset;
@property(nonatomic) double bubbleBottomSpace; // @synthesize bubbleBottomSpace=_bubbleBottomSpace;
@property(nonatomic) double bubbleTopSpace; // @synthesize bubbleTopSpace=_bubbleTopSpace;
@property(nonatomic) double bubbleToAvatarSpace; // @synthesize bubbleToAvatarSpace=_bubbleToAvatarSpace;
@property(nonatomic) struct UIEdgeInsets bubbleCapInsets; // @synthesize bubbleCapInsets=_bubbleCapInsets;
@property(nonatomic) struct CGRect avatarImageViewFrame; // @synthesize avatarImageViewFrame=_avatarImageViewFrame;
@property(retain, nonatomic) UIImage *customAvatarImage; // @synthesize customAvatarImage=_customAvatarImage;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
@property(readonly, nonatomic) _Bool isSender; // @synthesize isSender=_isSender;
- (void).cxx_destruct;
- (id)initWithType:(long long)arg1 isSender:(_Bool)arg2;

@end

