//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XIConversationMessageTableViewCell.h"

@class NSString, UITableView, XIConversationCardMessageCellConfigurations, XIConversationCardMessageModel;
@protocol XIConversationCardMessageTableViewCellDelegate;

@interface XIConversationCardMessageTableViewCell : XIConversationMessageTableViewCell
{
    id <XIConversationCardMessageTableViewCellDelegate> _cardDelegate;
    UITableView *_tableView;
    XIConversationCardMessageModel *_cardModel;
    XIConversationCardMessageCellConfigurations *_config;
}

@property(retain, nonatomic) XIConversationCardMessageCellConfigurations *config; // @synthesize config=_config;
@property(retain, nonatomic) XIConversationCardMessageModel *cardModel; // @synthesize cardModel=_cardModel;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <XIConversationCardMessageTableViewCellDelegate> cardDelegate; // @synthesize cardDelegate=_cardDelegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)reloadCellWithModel:(id)arg1;
- (void)setupSubViewWithModel:(id)arg1 config:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithModel:(id)arg1 config:(id)arg2;
- (void)setDelegateLoadCustomAvatar:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

