//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface XIConversationHttpResponseModel : NSObject
{
    NSString *_service;
    NSArray *_answer;
}

@property(retain, nonatomic) NSArray *answer; // @synthesize answer=_answer;
@property(retain, nonatomic) NSString *service; // @synthesize service=_service;
- (void).cxx_destruct;

@end

