//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XIConversationMessageCellConfigurations.h"

@class NSDictionary, UIColor, UIFont;

@interface XIConversationTextMessageCellConfigurations : XIConversationMessageCellConfigurations
{
    UIColor *_textColor;
    UIFont *_font;
    NSDictionary *_attributedText;
}

@property(retain, nonatomic) NSDictionary *attributedText; // @synthesize attributedText=_attributedText;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
- (void).cxx_destruct;
- (void)setStatusViewSize:(struct CGSize)arg1;
- (void)setStatusViewAlignment:(long long)arg1;
- (void)setContentViewInset:(struct UIEdgeInsets)arg1;
- (void)setBubbleBottomSpace:(double)arg1;
- (void)setBubbleTopSpace:(double)arg1;
- (void)setBubbleToAvatarSpace:(double)arg1;
- (void)setBubbleCapInsets:(struct UIEdgeInsets)arg1;
- (void)setAvatarImageViewFrame:(struct CGRect)arg1;
- (void)setCustomAvatarImage:(id)arg1;
- (id)initWithType:(long long)arg1 isSender:(_Bool)arg2;
- (id)initWithSender:(_Bool)arg1;

@end

