//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface XIConversationFilesManager : NSObject
{
}

+ (_Bool)creatFileWithPath:(id)arg1;
+ (_Bool)creatDirectory:(id)arg1;
+ (id)getXiaoIceDirectoryCachesPath;
+ (id)getXiaoIceDirectoryPath;
+ (id)getXiaoIceCachesPath;
+ (id)getXiaoIcePath;
+ (id)getComponentsPath:(id)arg1;
+ (id)regetFileFrontOfPath:(id)arg1;
+ (id)regetFilePath:(id)arg1;
+ (id)getFilePathWithType:(long long)arg1;

@end

