//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XIConversationMessageCellConfigurations.h"

@class NSDictionary, UIColor, UIFont;

@interface XIConversationCardMessageCellConfigurations : XIConversationMessageCellConfigurations
{
    UIColor *_textColor;
    UIColor *_dateColor;
    UIFont *_font;
    UIFont *_dateFont;
    NSDictionary *_attributedText;
    double _cardItemHeight;
    double _cardItemImageLeftSpace;
    double _cardItemImageTopSpace;
    double _cardItemImageBottomSpace;
    double _cardItemImageWidth;
    double _cardItemTitleToImageSpace;
    double _cardItemTitleTopSpace;
    double _cardItemTitleRightSpace;
    double _cardItemTitleHeight;
    double _cardItemDateToImageSpace;
    double _cardItemDateBottomSpace;
    double _cardItemDateRightSpace;
    double _cardItemDateHeight;
}

@property(nonatomic) double cardItemDateHeight; // @synthesize cardItemDateHeight=_cardItemDateHeight;
@property(nonatomic) double cardItemDateRightSpace; // @synthesize cardItemDateRightSpace=_cardItemDateRightSpace;
@property(nonatomic) double cardItemDateBottomSpace; // @synthesize cardItemDateBottomSpace=_cardItemDateBottomSpace;
@property(nonatomic) double cardItemDateToImageSpace; // @synthesize cardItemDateToImageSpace=_cardItemDateToImageSpace;
@property(nonatomic) double cardItemTitleHeight; // @synthesize cardItemTitleHeight=_cardItemTitleHeight;
@property(nonatomic) double cardItemTitleRightSpace; // @synthesize cardItemTitleRightSpace=_cardItemTitleRightSpace;
@property(nonatomic) double cardItemTitleTopSpace; // @synthesize cardItemTitleTopSpace=_cardItemTitleTopSpace;
@property(nonatomic) double cardItemTitleToImageSpace; // @synthesize cardItemTitleToImageSpace=_cardItemTitleToImageSpace;
@property(nonatomic) double cardItemImageWidth; // @synthesize cardItemImageWidth=_cardItemImageWidth;
@property(nonatomic) double cardItemImageBottomSpace; // @synthesize cardItemImageBottomSpace=_cardItemImageBottomSpace;
@property(nonatomic) double cardItemImageTopSpace; // @synthesize cardItemImageTopSpace=_cardItemImageTopSpace;
@property(nonatomic) double cardItemImageLeftSpace; // @synthesize cardItemImageLeftSpace=_cardItemImageLeftSpace;
@property(nonatomic) double cardItemHeight; // @synthesize cardItemHeight=_cardItemHeight;
@property(retain, nonatomic) NSDictionary *attributedText; // @synthesize attributedText=_attributedText;
@property(retain, nonatomic) UIFont *dateFont; // @synthesize dateFont=_dateFont;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) UIColor *dateColor; // @synthesize dateColor=_dateColor;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
- (void).cxx_destruct;
- (void)setStatusViewSize:(struct CGSize)arg1;
- (void)setStatusViewAlignment:(long long)arg1;
- (void)setContentViewInset:(struct UIEdgeInsets)arg1;
- (void)setBubbleBottomSpace:(double)arg1;
- (void)setBubbleTopSpace:(double)arg1;
- (void)setBubbleToAvatarSpace:(double)arg1;
- (void)setBubbleCapInsets:(struct UIEdgeInsets)arg1;
- (void)setAvatarImageViewFrame:(struct CGRect)arg1;
- (void)setCustomAvatarImage:(id)arg1;
- (id)initWithSender:(_Bool)arg1;

@end

