//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, UIColor, UIImage;

@interface XIConversationConfiguration : NSObject
{
    _Bool _takePhotoSaveInPhotoLibrary;
    _Bool _firstIn;
    _Bool _showGuideView;
    _Bool _showFirstInWelcomeString;
    _Bool _showOpenWelcomeString;
    UIImage *_navigationBackgroundImage;
    UIColor *_navigationBackgroundColor;
    NSDictionary *_navigationTitleTextAttributes;
    NSString *_title;
    UIImage *_backgroundImage;
    UIColor *_backgroundColor;
    NSDictionary *_userInfo;
    NSString *_firstInWelcomeString;
    NSString *_openWelcomeString;
}

@property(retain, nonatomic) NSString *openWelcomeString; // @synthesize openWelcomeString=_openWelcomeString;
@property(nonatomic, getter=isShowOpenWelcomeString) _Bool showOpenWelcomeString; // @synthesize showOpenWelcomeString=_showOpenWelcomeString;
@property(retain, nonatomic) NSString *firstInWelcomeString; // @synthesize firstInWelcomeString=_firstInWelcomeString;
@property(nonatomic, getter=isShowFirstInWelcomeString) _Bool showFirstInWelcomeString; // @synthesize showFirstInWelcomeString=_showFirstInWelcomeString;
@property(nonatomic, getter=isShowGuideView) _Bool showGuideView; // @synthesize showGuideView=_showGuideView;
@property(nonatomic, getter=isFirstIn) _Bool firstIn; // @synthesize firstIn=_firstIn;
@property(readonly, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic, getter=isTakePhotoSaveInPhotoLibrary) _Bool takePhotoSaveInPhotoLibrary; // @synthesize takePhotoSaveInPhotoLibrary=_takePhotoSaveInPhotoLibrary;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSDictionary *navigationTitleTextAttributes; // @synthesize navigationTitleTextAttributes=_navigationTitleTextAttributes;
@property(retain, nonatomic) UIColor *navigationBackgroundColor; // @synthesize navigationBackgroundColor=_navigationBackgroundColor;
@property(retain, nonatomic) UIImage *navigationBackgroundImage; // @synthesize navigationBackgroundImage=_navigationBackgroundImage;
- (void).cxx_destruct;
- (void)setUserInfo:(id)arg1;
- (id)init;

@end

