//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, UIColor, UIFont;

@interface XIConversationTipsCellConfigurations : NSObject
{
    double _tipsHeight;
    double _cornerRadius;
    UIColor *_backgroundColor;
    UIColor *_tipsTextColor;
    UIFont *_font;
    NSDictionary *_attributedText;
    struct UIEdgeInsets _tipsInset;
}

@property(retain, nonatomic) NSDictionary *attributedText; // @synthesize attributedText=_attributedText;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) UIColor *tipsTextColor; // @synthesize tipsTextColor=_tipsTextColor;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) struct UIEdgeInsets tipsInset; // @synthesize tipsInset=_tipsInset;
@property(nonatomic) double tipsHeight; // @synthesize tipsHeight=_tipsHeight;
- (void).cxx_destruct;
- (id)init;

@end

