//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface XIDefaultStyle : NSObject
{
    NSDictionary *_styleDict;
}

+ (id)valueForKey:(id)arg1 type:(unsigned long long)arg2;
+ (id)imageForKey:(id)arg1 type:(unsigned long long)arg2;
+ (id)fontForKey:(id)arg1 type:(unsigned long long)arg2;
+ (_Bool)boolForKey:(id)arg1 type:(unsigned long long)arg2;
+ (id)colorForKey:(id)arg1 type:(unsigned long long)arg2;
+ (id)stringForKey:(id)arg1 type:(unsigned long long)arg2;
+ (double)floatForKey:(id)arg1 type:(unsigned long long)arg2;
+ (long long)integerForKey:(id)arg1 type:(unsigned long long)arg2;
+ (id)instance;
@property(retain, nonatomic) NSDictionary *styleDict; // @synthesize styleDict=_styleDict;
- (void).cxx_destruct;
- (id)init;

@end

