//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSArray, NSString, UIColor, UIFont, UIView, UIViewController, XILanguage;
@protocol IXILanguageFilter;

@interface XIDropBox : UIButton
{
    _Bool _isFullScreen;
    _Bool _isSourceLanguage;
    NSArray *_dataSource;
    NSArray *_historyList;
    XILanguage *_currentValue;
    UIViewController *_viewController;
    UIView *_parentView;
    CDUnknownBlockType _selectValueChangeAction;
    NSString *_recentLanguageDesc;
    NSString *_allLanguageDesc;
    NSString *_originalLanguageDesc;
    NSString *_targetLanguageDesc;
    id <IXILanguageFilter> _languageFilter;
    NSString *_kCellId;
    UIView *_maskView;
    UIView *_backView;
    double _tableWidth;
    double _tableHeight;
    double _triangleWidth;
    double _hPadding;
    double _topBarHeight;
    double _cornerRadius;
    UIFont *_textFont;
    UIFont *_headerFont;
    UIColor *_maskViewColor;
    UIColor *_headerBackColor;
    UIColor *_selectTextColor;
    UIColor *_commonTextColor;
}

@property(retain, nonatomic) UIColor *commonTextColor; // @synthesize commonTextColor=_commonTextColor;
@property(retain, nonatomic) UIColor *selectTextColor; // @synthesize selectTextColor=_selectTextColor;
@property(retain, nonatomic) UIColor *headerBackColor; // @synthesize headerBackColor=_headerBackColor;
@property(retain, nonatomic) UIColor *maskViewColor; // @synthesize maskViewColor=_maskViewColor;
@property(retain, nonatomic) UIFont *headerFont; // @synthesize headerFont=_headerFont;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double topBarHeight; // @synthesize topBarHeight=_topBarHeight;
@property(nonatomic) double hPadding; // @synthesize hPadding=_hPadding;
@property(nonatomic) double triangleWidth; // @synthesize triangleWidth=_triangleWidth;
@property(nonatomic) double tableHeight; // @synthesize tableHeight=_tableHeight;
@property(nonatomic) double tableWidth; // @synthesize tableWidth=_tableWidth;
@property(nonatomic) __weak UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) __weak UIView *maskView; // @synthesize maskView=_maskView;
@property(copy, nonatomic) NSString *kCellId; // @synthesize kCellId=_kCellId;
@property(nonatomic) __weak id <IXILanguageFilter> languageFilter; // @synthesize languageFilter=_languageFilter;
@property(copy, nonatomic) NSString *targetLanguageDesc; // @synthesize targetLanguageDesc=_targetLanguageDesc;
@property(copy, nonatomic) NSString *originalLanguageDesc; // @synthesize originalLanguageDesc=_originalLanguageDesc;
@property(copy, nonatomic) NSString *allLanguageDesc; // @synthesize allLanguageDesc=_allLanguageDesc;
@property(copy, nonatomic) NSString *recentLanguageDesc; // @synthesize recentLanguageDesc=_recentLanguageDesc;
@property(copy, nonatomic) CDUnknownBlockType selectValueChangeAction; // @synthesize selectValueChangeAction=_selectValueChangeAction;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) _Bool isSourceLanguage; // @synthesize isSourceLanguage=_isSourceLanguage;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(retain, nonatomic) XILanguage *currentValue; // @synthesize currentValue=_currentValue;
@property(retain, nonatomic) NSArray *historyList; // @synthesize historyList=_historyList;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)withdrawList;
- (id)getBackView;
- (void)showDropBox;
- (void)setup;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

