//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IXITextTranslatorProtocol-Protocol.h"

@class NSString;
@protocol IXITextRequestProtocol, IXITranslateListener;

@interface XIGatewayTextTranslator : NSObject <IXITextTranslatorProtocol>
{
    id <IXITextRequestProtocol> _textRequest;
    NSString *_content;
    NSString *_sourceLanguage;
    NSString *_targetLanguage;
    id <IXITranslateListener> _listener;
}

+ (id)translatorWithTextRequest:(id)arg1;
@property(nonatomic) __weak id <IXITranslateListener> listener; // @synthesize listener=_listener;
@property(copy, nonatomic) NSString *targetLanguage; // @synthesize targetLanguage=_targetLanguage;
@property(copy, nonatomic) NSString *sourceLanguage; // @synthesize sourceLanguage=_sourceLanguage;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) id <IXITextRequestProtocol> textRequest; // @synthesize textRequest=_textRequest;
- (void).cxx_destruct;
- (void)translateContent:(id)arg1;
- (void)setTranslateResultListener:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)setupLanguage;
- (void)setupRequest;
- (id)init;
- (id)initWithTextRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

