//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IXIRealtimeSpeechTranslatorProtocol-Protocol.h"
#import "SRWebSocketDelegate-Protocol.h"

@class NSString, SRWebSocket;
@protocol IXIRealtimeRecorderProtocol, IXITranslateListener;

@interface XIGatewayRealtimeSpeechTranslator : NSObject <SRWebSocketDelegate, IXIRealtimeSpeechTranslatorProtocol>
{
    Class _RecorderClass;
    id <IXIRealtimeRecorderProtocol> _recorder;
    NSString *_sourceLanguage;
    NSString *_targetLanguage;
    id <IXITranslateListener> _listener;
    SRWebSocket *_webSocket;
}

+ (id)translatorWithRecorderClass:(Class)arg1;
@property(retain, nonatomic) SRWebSocket *webSocket; // @synthesize webSocket=_webSocket;
@property(nonatomic) __weak id <IXITranslateListener> listener; // @synthesize listener=_listener;
@property(copy, nonatomic) NSString *targetLanguage; // @synthesize targetLanguage=_targetLanguage;
@property(copy, nonatomic) NSString *sourceLanguage; // @synthesize sourceLanguage=_sourceLanguage;
@property(retain, nonatomic) id <IXIRealtimeRecorderProtocol> recorder; // @synthesize recorder=_recorder;
@property(nonatomic) Class RecorderClass; // @synthesize RecorderClass=_RecorderClass;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)setupLanguage;
- (void)setupRealtimeRecorder;
- (void)updateWebSocket;
- (void)webSocket:(id)arg1 didFailWithError:(id)arg2;
- (void)webSocket:(id)arg1 didCloseWithError:(id)arg2;
- (void)webSocketDidOpen:(id)arg1;
- (void)webSocket:(id)arg1 didReceiveMessage:(id)arg2;
- (_Bool)webSocketShouldConvertTextFrameToString:(id)arg1;
- (void)end;
- (void)begin;
- (void)setTranslateResultListener:(id)arg1;
- (id)init;
- (id)initWithRecorderClass:(Class)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

