//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IXIResponseModelProtocol-Protocol.h"

@class NSString;

@interface XIGatewayRealtimeResponseModel : NSObject <IXIResponseModelProtocol>
{
    NSString *_type;
    NSString *_audiourl;
    NSString *_impressionID;
    NSString *_responseType;
    NSString *_text;
    NSString *_srText;
    NSString *_errorMessage;
}

+ (id)modelWithDict:(id)arg1;
@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(copy, nonatomic) NSString *srText; // @synthesize srText=_srText;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *responseType; // @synthesize responseType=_responseType;
@property(copy, nonatomic) NSString *impressionID; // @synthesize impressionID=_impressionID;
@property(copy, nonatomic) NSString *audiourl; // @synthesize audiourl=_audiourl;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithDict:(id)arg1;

// Remaining properties
@property(copy, nonatomic) NSString *audio;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

