//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IXIHttpRequestManagerProtocol-Protocol.h"

@class NSDictionary, NSHTTPURLResponse, NSString, NSURLSessionTask;

@interface XIHttpRequestManager : NSObject <IXIHttpRequestManagerProtocol>
{
    _Bool _isFinished;
    NSHTTPURLResponse *_httpResponse;
    unsigned long long _requestMethod;
    unsigned long long _cachePolicy;
    NSDictionary *_customHeader;
    CDUnknownBlockType _response;
    NSString *_url;
    unsigned long long _responseState;
    NSDictionary *_params;
    unsigned long long _startTime;
    unsigned long long _contentType;
    CDUnknownBlockType OnResponseData;
    CDUnknownBlockType OnResponseError;
    double _timeoutInterval;
    unsigned long long _endTime;
    unsigned long long _constTime;
    NSURLSessionTask *_task;
}

@property(retain, nonatomic) NSURLSessionTask *task; // @synthesize task=_task;
@property(nonatomic) unsigned long long constTime; // @synthesize constTime=_constTime;
@property(nonatomic) unsigned long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
@property(copy, nonatomic) CDUnknownBlockType OnResponseError; // @synthesize OnResponseError;
@property(copy, nonatomic) CDUnknownBlockType OnResponseData; // @synthesize OnResponseData;
@property(nonatomic) unsigned long long contentType; // @synthesize contentType=_contentType;
@property(nonatomic) unsigned long long startTime; // @synthesize startTime=_startTime;
@property(nonatomic) _Bool isFinished; // @synthesize isFinished=_isFinished;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(nonatomic) unsigned long long responseState; // @synthesize responseState=_responseState;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) CDUnknownBlockType response; // @synthesize response=_response;
@property(retain, nonatomic) NSDictionary *customHeader; // @synthesize customHeader=_customHeader;
@property(nonatomic) unsigned long long cachePolicy; // @synthesize cachePolicy=_cachePolicy;
@property(nonatomic) unsigned long long requestMethod; // @synthesize requestMethod=_requestMethod;
@property(retain, nonatomic) NSHTTPURLResponse *httpResponse; // @synthesize httpResponse=_httpResponse;
- (void).cxx_destruct;
- (id)contentTypeString;
- (id)requestMethodString;
- (void)createRequest:(id)arg1;
- (void)appendHeaderField:(id *)arg1;
- (void)beginRequestWithBody:(id)arg1;
- (void)beginRequest;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

