//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface XIInputAccessoryView : UIView
{
}

+ (id)viewWithLeftBtn:(id)arg1 rightBtn:(id)arg2 height:(double)arg3 isHideBtnNeeded:(_Bool)arg4;
- (void)hideKeyboard;
- (id)initWithLeftBtn:(id)arg1 rightBtn:(id)arg2 height:(double)arg3 isHideBtnNeeded:(_Bool)arg4;

@end

