//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSURLProtocol.h>

#import "NSURLSessionDataDelegate-Protocol.h"

@class NSMutableData, NSString, NSURLResponse, NSURLSession, NSURLSessionConfiguration;

@interface XILandingpageCacheURLProtocol : NSURLProtocol <NSURLSessionDataDelegate>
{
    NSURLSessionConfiguration *_config;
    long long _updateInterval;
    NSURLSession *_session;
    NSMutableData *_data;
    NSURLResponse *_response;
}

+ (id)canonicalRequestForRequest:(id)arg1;
+ (_Bool)canInitWithRequest:(id)arg1;
+ (void)clearUrlDict;
+ (void)setUpdateInterval:(long long)arg1;
+ (void)setConfig:(id)arg1;
+ (void)cancelListeningNetWorking;
+ (void)startListeningNetWorking;
@property(retain, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) NSMutableData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
@property(nonatomic) long long updateInterval; // @synthesize updateInterval=_updateInterval;
@property(retain, nonatomic) NSURLSessionConfiguration *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)appendData:(id)arg1;
- (_Bool)isUseCache;
- (void)stopLoading;
- (void)startLoading;
- (void)netRequestWithRequest:(id)arg1;
- (void)backgroundCheckUpdate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

