//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface XILanguageListHelper : NSObject
{
    NSString *_folderPath;
    NSString *_sourcePath;
    NSString *_targetPath;
    NSString *_ocrPath;
}

+ (id)pathForType:(unsigned long long)arg1;
+ (id)stringForType:(unsigned long long)arg1;
+ (void)initialize;
+ (id)shared;
+ (_Bool)isExchangeable:(id)arg1 target:(id)arg2;
+ (void)cleanRecentLanguage:(unsigned long long)arg1;
+ (void)updateRecentLanguage:(id)arg1 type:(unsigned long long)arg2;
+ (id)getRecentLanguageList:(unsigned long long)arg1;
+ (id)getSupportLanguageList:(unsigned long long)arg1;
@property(copy, nonatomic) NSString *ocrPath; // @synthesize ocrPath=_ocrPath;
@property(copy, nonatomic) NSString *targetPath; // @synthesize targetPath=_targetPath;
@property(copy, nonatomic) NSString *sourcePath; // @synthesize sourcePath=_sourcePath;
@property(copy, nonatomic) NSString *folderPath; // @synthesize folderPath=_folderPath;
- (void).cxx_destruct;

@end

