//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UILabel;

@interface XILoadView : UIView
{
    UIActivityIndicatorView *activityIndicatorView;
    UILabel *messageLabel;
    float opacity;
}

+ (void)hideForView:(id)arg1 animated:(_Bool)arg2;
+ (id)showToView:(id)arg1 animated:(_Bool)arg2;
+ (id)showToView:(id)arg1 message:(id)arg2 animated:(_Bool)arg3;
@property(nonatomic) float opacity; // @synthesize opacity;
- (void).cxx_destruct;
- (void)fillRoundedRect:(struct CGRect)arg1 inContext:(struct CGContext *)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)hideUsingAnimated:(_Bool)arg1;
- (void)messageForShow:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 message:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

