//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

#import "IXIRoutable-Protocol.h"
#import "IXIRouterPathable-Protocol.h"

@class NSDictionary;

@interface XINavigationController : UINavigationController <IXIRouterPathable, IXIRoutable>
{
    Class any;
    NSDictionary *params;
}

+ (id)controllerWithParams:(id)arg1;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params;
@property(nonatomic) Class any; // @synthesize any;
- (void).cxx_destruct;

@end

