//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AVCapturePhotoCaptureDelegate-Protocol.h"
#import "IXIOCRNetworkListener-Protocol.h"
#import "XIPhotoTranslateContentViewDelegate-Protocol.h"

@class AVCaptureDevice, AVCaptureSession, AVCaptureStillImageOutput, AVCaptureVideoPreviewLayer, NSLayoutConstraint, NSString, UIButton, UIImage, UIScrollView, UIView, XIDropBox, XIGatewayOCRRequest, XIOCRCompressConfig, XIPhotoTranslateContentView;
@protocol IXILanguageSelectorClickListener, IXIOCRProcessListener;

@interface XIOCRController : UIViewController <IXIOCRNetworkListener, AVCapturePhotoCaptureDelegate, XIPhotoTranslateContentViewDelegate>
{
    id <IXILanguageSelectorClickListener> _languageListener;
    id <IXIOCRProcessListener> _processListener;
    XIOCRCompressConfig *_compressConfig;
    NSLayoutConstraint *_consTopMargin;
    NSLayoutConstraint *_consBottomMargin;
    UIScrollView *_scrollView;
    XIPhotoTranslateContentView *_translateContentView;
    UIButton *_closeButton;
    UIButton *_cameraButton;
    UIButton *_albumButton;
    UIButton *_flashButton;
    UIView *_bottomView;
    UIButton *_changeButton;
    UIButton *_sourceLanguageButton;
    XIDropBox *_targetLanguageButton;
    UIButton *_leftBackButton;
    AVCaptureDevice *_device;
    AVCaptureSession *_session;
    AVCaptureStillImageOutput *_imageOutput;
    AVCaptureVideoPreviewLayer *_previewLayer;
    UIImage *_originImage;
    XIGatewayOCRRequest *_request;
}

@property(retain, nonatomic) XIGatewayOCRRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) UIImage *originImage; // @synthesize originImage=_originImage;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(retain, nonatomic) AVCaptureStillImageOutput *imageOutput; // @synthesize imageOutput=_imageOutput;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
@property(nonatomic) __weak UIButton *leftBackButton; // @synthesize leftBackButton=_leftBackButton;
@property(nonatomic) __weak XIDropBox *targetLanguageButton; // @synthesize targetLanguageButton=_targetLanguageButton;
@property(nonatomic) __weak UIButton *sourceLanguageButton; // @synthesize sourceLanguageButton=_sourceLanguageButton;
@property(nonatomic) __weak UIButton *changeButton; // @synthesize changeButton=_changeButton;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak UIButton *flashButton; // @synthesize flashButton=_flashButton;
@property(nonatomic) __weak UIButton *albumButton; // @synthesize albumButton=_albumButton;
@property(nonatomic) __weak UIButton *cameraButton; // @synthesize cameraButton=_cameraButton;
@property(nonatomic) __weak UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak XIPhotoTranslateContentView *translateContentView; // @synthesize translateContentView=_translateContentView;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak NSLayoutConstraint *consBottomMargin; // @synthesize consBottomMargin=_consBottomMargin;
@property(nonatomic) __weak NSLayoutConstraint *consTopMargin; // @synthesize consTopMargin=_consTopMargin;
@property(retain, nonatomic) XIOCRCompressConfig *compressConfig; // @synthesize compressConfig=_compressConfig;
@property(nonatomic) __weak id <IXIOCRProcessListener> processListener; // @synthesize processListener=_processListener;
@property(nonatomic) __weak id <IXILanguageSelectorClickListener> languageListener; // @synthesize languageListener=_languageListener;
- (void).cxx_destruct;
- (void)initAVCaptureDevice;
- (void)beginTranslate;
- (void)initLanguageButton;
- (void)requestVideoAuth;
- (void)resetViewStatus;
- (void)userInteractionEnabled:(_Bool)arg1;
- (void)showResults;
- (void)setupSubviews;
- (_Bool)shouldPhotoTranslateContentViewShowResultsView;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)onOCRTranslateError:(id)arg1;
- (void)onOCRTranslateResult:(id)arg1;
- (void)targetLanguageButtonClicked:(id)arg1;
- (void)sourceLanguageButtonClicked:(id)arg1;
- (void)changeButtonClicked:(id)arg1;
- (void)flashButtonClicked:(id)arg1;
- (void)albumButtonClicked:(id)arg1;
- (void)cameraButtonClicked:(id)arg1;
- (void)closeButtonClicked:(id)arg1;
- (void)setOnProcessListener:(id)arg1;
- (void)setOnLanguageChangeListener:(id)arg1;
- (void)dealloc;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

