//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@class NSMutableArray, UIView;
@protocol XIPhotoTranslateContentViewDelegate;

@interface XIPhotoTranslateContentView : UIImageView
{
    id <XIPhotoTranslateContentViewDelegate> _delegate;
    UIView *_resultView;
    UIView *_coverView;
    NSMutableArray *_translateResults;
    double _textAngle;
    NSMutableArray *_positionArr;
    NSMutableArray *_translateTextLabels;
    struct CGAffineTransform _resultsViewTransform;
}

@property(retain, nonatomic) NSMutableArray *translateTextLabels; // @synthesize translateTextLabels=_translateTextLabels;
@property(retain, nonatomic) NSMutableArray *positionArr; // @synthesize positionArr=_positionArr;
@property(nonatomic) double textAngle; // @synthesize textAngle=_textAngle;
@property(nonatomic) struct CGAffineTransform resultsViewTransform; // @synthesize resultsViewTransform=_resultsViewTransform;
@property(retain, nonatomic) NSMutableArray *translateResults; // @synthesize translateResults=_translateResults;
@property(nonatomic) __weak UIView *coverView; // @synthesize coverView=_coverView;
@property(nonatomic) __weak UIView *resultView; // @synthesize resultView=_resultView;
@property(nonatomic) __weak id <XIPhotoTranslateContentViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)resultsViewTapped;
- (void)setupResults;
- (void)setupSubViews;
- (void)dismissResults;
- (void)showResults;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

