//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IXIRealtimeRecorderProtocol-Protocol.h"

@class NSMutableData, NSTimer;

@interface XIRealtimeRecorder : NSObject <IXIRealtimeRecorderProtocol>
{
    struct AudioStreamBasicDescription _mRecordFormat;
    struct OpaqueAudioQueue *_mQueue;
    struct AudioQueueBuffer *_mBuffers[3];
    struct OpaqueAudioFileID *_mAudioFile;
    unsigned int _bufferByteSize;
    long long _mCurrentPacket;
    _Bool _isRecording;
    _Bool _isPaused;
    unsigned int _audioFormat;
    unsigned int _fileType;
    const char *_filePath;
    NSMutableData *_file;
    CDUnknownBlockType _realtimeCallback;
    CDUnknownBlockType _metersCallback;
    CDUnknownBlockType _finishCallback;
    NSTimer *_timer;
}

+ (id)recorderWithAudioFormat:(unsigned int)arg1 fileType:(unsigned int)arg2 filePath:(id)arg3 realtimeCallback:(CDUnknownBlockType)arg4 metersCallback:(CDUnknownBlockType)arg5;
+ (id)recorderWithAudioFormat:(unsigned int)arg1 fileType:(unsigned int)arg2 filePath:(id)arg3 realtimeCallback:(CDUnknownBlockType)arg4;
+ (id)recorderWithAudioFormat:(unsigned int)arg1 realtimeCallback:(CDUnknownBlockType)arg2 metersCallback:(CDUnknownBlockType)arg3;
+ (id)recorderWithAudioFormat:(unsigned int)arg1 realtimeCallback:(CDUnknownBlockType)arg2;
+ (id)recorderWithMetersCallback:(CDUnknownBlockType)arg1 finishCallback:(CDUnknownBlockType)arg2;
+ (id)recorderWithRealtimeCallback:(CDUnknownBlockType)arg1 metersCallback:(CDUnknownBlockType)arg2;
+ (id)recorderWithRealtimeCallback:(CDUnknownBlockType)arg1;
+ (id)recorderWithRealtimeCallback:(CDUnknownBlockType)arg1 metersCallback:(CDUnknownBlockType)arg2 finishCallback:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) _Bool isPaused; // @synthesize isPaused=_isPaused;
@property(nonatomic) _Bool isRecording; // @synthesize isRecording=_isRecording;
@property(copy, nonatomic) CDUnknownBlockType finishCallback; // @synthesize finishCallback=_finishCallback;
@property(copy, nonatomic) CDUnknownBlockType metersCallback; // @synthesize metersCallback=_metersCallback;
@property(copy, nonatomic) CDUnknownBlockType realtimeCallback; // @synthesize realtimeCallback=_realtimeCallback;
@property(retain, nonatomic) NSMutableData *file; // @synthesize file=_file;
@property(nonatomic) const char *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) unsigned int fileType; // @synthesize fileType=_fileType;
@property(nonatomic) unsigned int audioFormat; // @synthesize audioFormat=_audioFormat;
- (void).cxx_destruct;
- (double)getMeteringPower;
- (void)updateMeter;
- (void)prepareAudioQueueBufferGroup;
- (void)setAudioQueueBufferSize;
- (void)createAuidoFileIfNeeded;
- (void)createAudioQueueAndUpdateConig;
- (void)setupRecorderState;
- (void)prepare;
- (void)clean;
- (void)pause;
- (void)stopWithFinish:(_Bool)arg1;
- (void)stop;
- (void)stopNoFinish;
- (void)start;
- (id)init;
- (id)initWithAudioFormat:(unsigned int)arg1 fileType:(unsigned int)arg2 filePath:(id)arg3 realtimeCallback:(CDUnknownBlockType)arg4 metersCallback:(CDUnknownBlockType)arg5 finishCallback:(CDUnknownBlockType)arg6;
- (id)initWithAudioFormat:(unsigned int)arg1 realtimeCallback:(CDUnknownBlockType)arg2 metersCallback:(CDUnknownBlockType)arg3;
- (id)initWithRealtimeCallback:(CDUnknownBlockType)arg1 metersCallback:(CDUnknownBlockType)arg2 finishCallback:(CDUnknownBlockType)arg3;

@end

