//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface XIUrlCacheManager : NSObject
{
    NSString *_kMSACacheDate;
    double _kMSAMaxTimeInterval;
}

+ (void)clearCache;
+ (void)storeInMemoryResponse:(id)arg1 data:(id)arg2 forRequest:(id)arg3;
+ (void)storeResponse:(id)arg1 data:(id)arg2 forRequest:(id)arg3;
+ (id)cachedDataForRequest:(id)arg1;
+ (id)instance;
@property(nonatomic) double kMSAMaxTimeInterval; // @synthesize kMSAMaxTimeInterval=_kMSAMaxTimeInterval;
@property(copy, nonatomic) NSString *kMSACacheDate; // @synthesize kMSACacheDate=_kMSACacheDate;
- (void).cxx_destruct;
- (id)init;

@end

