//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface XIVoiceMetersView : UIView
{
    NSMutableArray *_metersLevels;
}

@property(retain, nonatomic) NSMutableArray *metersLevels; // @synthesize metersLevels=_metersLevels;
- (void).cxx_destruct;
- (void)reloadMetersViewWithLevel:(double)arg1;
- (void)reloadMetersViewWithLevels:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

