//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ImageCacheDelegate-Protocol.h"

@class ImageCacheService, NSString, ScalingOperation, UIImage, UIImageView, UIScrollView;
@protocol ZoomableImageDelegate;

@interface ZoomableImage : UIView <ImageCacheDelegate>
{
    UIImageView *imageView;
    UIScrollView *scrollView;
    UIView *backgroundView;
    struct CGSize maxImageSize;
    NSString *thumbnailUrl;
    NSString *fullImageUrl;
    struct CGSize fullImageSize;
    _Bool hasFullImage;
    _Bool hasThumbnail;
    _Bool fullImageRendered;
    ScalingOperation *scalingOperation;
    float maxZoomScale;
    ImageCacheService *cacheService;
    id <ZoomableImageDelegate> delegate;
    _Bool zoomEnabled;
    _Bool scaleToFitParent;
    UIImage *thumbnailImage;
    float previousScale;
    _Bool ignoreZooms;
    _Bool isFromFullScreenSlideshow;
}

+ (id)newInstance;
@property _Bool isFromFullScreenSlideshow; // @synthesize isFromFullScreenSlideshow;
@property(readonly, nonatomic) struct CGSize fullImageSize; // @synthesize fullImageSize;
@property(retain, nonatomic) ScalingOperation *scalingOperation; // @synthesize scalingOperation;
@property(nonatomic) _Bool scaleToFitParent; // @synthesize scaleToFitParent;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage;
@property(nonatomic) _Bool fullImageRendered; // @synthesize fullImageRendered;
@property(nonatomic) _Bool zoomEnabled; // @synthesize zoomEnabled;
@property(nonatomic) id <ZoomableImageDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
@property(retain, nonatomic) ImageCacheService *cacheService; // @synthesize cacheService;
@property(nonatomic) float maxZoomScale; // @synthesize maxZoomScale;
@property(readonly, nonatomic) _Bool hasThumbnail; // @synthesize hasThumbnail;
@property(readonly, nonatomic) _Bool hasFullImage; // @synthesize hasFullImage;
@property(retain, nonatomic) NSString *fullImageUrl; // @synthesize fullImageUrl;
@property(retain, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl;
@property(nonatomic) struct CGSize maxImageSize; // @synthesize maxImageSize;
- (void)resetToThumbnail;
- (void)computeMaximumZoomScale;
- (void)imageReceived:(id)arg1 isFresh:(_Bool)arg2;
- (void)dataReceived:(id)arg1 isFresh:(_Bool)arg2;
- (struct CGRect)centeredFrameForScrollView:(id)arg1 andUIView:(id)arg2;
- (void)resetZoom;
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3;
- (void)scrollViewDidZoom:(id)arg1;
- (id)viewForZoomingInScrollView:(id)arg1;
- (_Bool)isZoomed;
- (void)waitForThumbnailUrl:(id)arg1 forFullImageUrl:(id)arg2 withSize:(struct CGSize)arg3 withCacheService:(id)arg4;
- (void)setImage:(id)arg1 withAnimation:(_Bool)arg2;
- (void)setImageData:(id)arg1 withSize:(struct CGSize)arg2 withAnimation:(_Bool)arg3;
- (struct CGRect)getFrameSize;
- (void)handlePinch:(id)arg1;
- (void)scalingOperation:(id)arg1 doneWithImage:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

